In [2]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.service import Service as ChromeService
from bs4 import BeautifulSoup
import pandas as pd
import requests

In [3]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36'
}

cookies = {
    'cookie_name': 'cookie_value'
}

# Semana 2

In [4]:
# Especifica la ubicación del controlador de Chrome (chromedriver.exe)
chromedriver_path = 'chromedriver.exe'

# Configura el servicio de Chrome con el argumento executable_path
chrome_service = ChromeService(executable_path=chromedriver_path)

# Crea una instancia del navegador Chrome con el servicio configurado
driver = webdriver.Chrome(service=chrome_service)

# Abre la página web
url = 'https://web.archive.org/web/20230921141353/https://www.espn.com/nfl/stats/team/_/view/defense'
driver.get(url)

# Espera a que la tabla esté presente en la página
wait = WebDriverWait(driver, 10)
tabla_presente = EC.presence_of_element_located((By.CSS_SELECTOR, '.Table.Table--align-right.Table--fixed.Table--fixed-left'))
tabla = wait.until(tabla_presente)

# Obtén el contenido HTML de la ta bla
tabla_html = tabla.get_attribute('outerHTML')

# Utiliza BeautifulSoup para analizar el contenido HTML
soup = BeautifulSoup(tabla_html, 'html.parser')

# Encuentra todas las filas de la tabla
filas = soup.find_all('tr')

# Inicializa una lista para almacenar los datos
datos = []

# Recorre las filas y obtén los datos de cada celda
for fila in filas:
    celdas = fila.find_all('td')
    if celdas:  # Verifica si hay al menos una celda de datos en la fila
        fila_datos = [celda.text.strip() for celda in celdas]
        datos.append(fila_datos)

# Crea un DataFrame de Pandas con los datos filtrados
columnas = ['Equipo']  # Reemplaza con el nombre de tu columna
dfdefsem2 = pd.DataFrame(datos, columns=columnas)


# Cierra el navegador
driver.quit()

In [5]:
dfdefsem2

                   Equipo
0          Dallas Cowboys
1        Cleveland Browns
2         Atlanta Falcons
3      New Orleans Saints
4           Buffalo Bills
5        Los Angeles Rams
6        Baltimore Ravens
7       Carolina Panthers
8    Tampa Bay Buccaneers
9   Washington Commanders
10         Houston Texans
11    San Francisco 49ers
12     Kansas City Chiefs
13   New England Patriots
14        New York Giants
15         Denver Broncos
16      Minnesota Vikings
17   Jacksonville Jaguars
18      Arizona Cardinals
19       Tennessee Titans
20          New York Jets
21          Detroit Lions
22      Las Vegas Raiders
23         Miami Dolphins
24     Indianapolis Colts
25    Philadelphia Eagles
26      Green Bay Packers
27     Cincinnati Bengals
28          Chicago Bears
29    Pittsburgh Steelers
30       Seattle Seahawks
31   Los Angeles Chargers

In [16]:
urldefsem2 = "https://web.archive.org/web/20230921141353/https://www.espn.com/nfl/stats/team/_/view/defense"

In [17]:
rdefsem2 = requests.get(urldefsem2, cookies=cookies, headers=headers)
html_contentsdefsem2 = rdefsem2.text

In [18]:
html_soupdefsem2 = BeautifulSoup(html_contentsdefsem2, 'html.parser')

In [19]:
tabla_puntajedefsem2 = html_soupdefsem2.find_all('table', class_='Table Table--align-right')

In [20]:
columnasdefsem2 =  ['GP','YDS','YDS/G','YDS','YDS/G',
             'YDS','YDS/G','PTS','PTS/G',]

In [21]:
infdefsem2 = pd.DataFrame(columns = columnasdefsem2)

In [22]:
for table in tabla_puntajedefsem2:
    for row in table.find_all('tr')[2:]:
        values = []
        for col in row.find_all(['th','td']):
            values.append(col.text)
        if len(values) == len(columnasdefsem2):
            infdefsem2.loc[len(infdefsem2)] = values

In [23]:
infdefsem2

   GP  YDS  YDS/G  YDS  YDS/G  YDS  YDS/G PTS PTS/G
0   2  386  193.0  214  107.0  172   86.0  10   5.0
1   2  397  198.5  267  133.5  130   65.0  29  14.5
2   2  505  252.5  267  133.5  238  119.0  34  17.0
3   2  524  262.0  320  160.0  204  102.0  32  16.0
4   2  529  264.5  302  151.0  227  113.5  32  16.0
5   2  545  272.5  301  150.5  244  122.0  43  21.5
6   2  550  275.0  412  206.0  138   69.0  33  16.5
7   2  562  281.0  298  149.0  264  132.0  44  22.0
8   2  605  302.5  497  248.5  108   54.0  34  17.0
9   2  609  304.5  391  195.5  218  109.0  49  24.5
10  2  618  309.0  382  191.0  236  118.0  56  28.0
11  2  625  312.5  495  247.5  130   65.0  30  15.0
12  2  639  319.5  447  223.5  192   96.0  30  15.0
13  2  640  320.0  398  199.0  242  121.0  49  24.5
14  2  644  322.0  371  185.5  273  136.5  68  34.0
15  2  649  324.5  466  233.0  183   91.5  52  26.0
16  2  672  336.0  340  170.0  332  166.0  54  27.0
17  2  679  339.5  513  256.5  166   83.0  38  19.0
18  2  687  343.5  468  234.0  219  109.5  51  25.5
19  2  693  346.5  563  281.5  130   65.0  40  20.0
20  2  696  348.0  465  232.5  231  115.5  46  23.0
21  2  709  354.5  537  268.5  172   86.0  57  28.5
22  2  710  355.0  433  216.5  277  138.5  54  27.0
23  2  721  360.5  400  200.0  321  160.5  51  25.5
24  2  731  365.5  574  287.0  157   78.5  51  25.5
25  2  756  378.0  652  326.0  104   52.0  48  24.0
26  2  757  378.5  424  212.0  333  166.5  45  22.5
27  2  765  382.5  381  190.5  384  192.0  51  25.5
28  2  766  383.0  554  277.0  212  106.0  65  32.5
29  1  799  399.5  413  206.5  386  193.0  52  26.0
30  2  844  422.0  650  325.0  194   97.0  61  30.5
31  2  877  438.5  666  333.0  211  105.5  63  31.5

In [24]:
columnsUnidsem2 = pd.concat([dfdefsem2,infdefsem2], axis=1)

In [25]:
columnsUnidsem2

                   Equipo GP  YDS  YDS/G  YDS  YDS/G  YDS  YDS/G PTS PTS/G
0          Dallas Cowboys  2  386  193.0  214  107.0  172   86.0  10   5.0
1        Cleveland Browns  2  397  198.5  267  133.5  130   65.0  29  14.5
2         Atlanta Falcons  2  505  252.5  267  133.5  238  119.0  34  17.0
3      New Orleans Saints  2  524  262.0  320  160.0  204  102.0  32  16.0
4           Buffalo Bills  2  529  264.5  302  151.0  227  113.5  32  16.0
5        Los Angeles Rams  2  545  272.5  301  150.5  244  122.0  43  21.5
6        Baltimore Ravens  2  550  275.0  412  206.0  138   69.0  33  16.5
7       Carolina Panthers  2  562  281.0  298  149.0  264  132.0  44  22.0
8    Tampa Bay Buccaneers  2  605  302.5  497  248.5  108   54.0  34  17.0
9   Washington Commanders  2  609  304.5  391  195.5  218  109.0  49  24.5
10         Houston Texans  2  618  309.0  382  191.0  236  118.0  56  28.0
11    San Francisco 49ers  2  625  312.5  495  247.5  130   65.0  30  15.0
12     Kansas City Chiefs  2  639  319.5  447  223.5  192   96.0  30  15.0
13   New England Patriots  2  640  320.0  398  199.0  242  121.0  49  24.5
14        New York Giants  2  644  322.0  371  185.5  273  136.5  68  34.0
15         Denver Broncos  2  649  324.5  466  233.0  183   91.5  52  26.0
16      Minnesota Vikings  2  672  336.0  340  170.0  332  166.0  54  27.0
17   Jacksonville Jaguars  2  679  339.5  513  256.5  166   83.0  38  19.0
18      Arizona Cardinals  2  687  343.5  468  234.0  219  109.5  51  25.5
19       Tennessee Titans  2  693  346.5  563  281.5  130   65.0  40  20.0
20          New York Jets  2  696  348.0  465  232.5  231  115.5  46  23.0
21          Detroit Lions  2  709  354.5  537  268.5  172   86.0  57  28.5
22      Las Vegas Raiders  2  710  355.0  433  216.5  277  138.5  54  27.0
23         Miami Dolphins  2  721  360.5  400  200.0  321  160.5  51  25.5
24     Indianapolis Colts  2  731  365.5  574  287.0  157   78.5  51  25.5
25    Philadelphia Eagles  2  756  378.0  652  326.0  104   52.0  48  24.0
26      Green Bay Packers  2  757  378.5  424  212.0  333  166.5  45  22.5
27     Cincinnati Bengals  2  765  382.5  381  190.5  384  192.0  51  25.5
28          Chicago Bears  2  766  383.0  554  277.0  212  106.0  65  32.5
29    Pittsburgh Steelers  1  799  399.5  413  206.5  386  193.0  52  26.0
30       Seattle Seahawks  2  844  422.0  650  325.0  194   97.0  61  30.5
31   Los Angeles Chargers  2  877  438.5  666  333.0  211  105.5  63  31.5

In [26]:
columnsUnidsem2.to_excel('Export\\defsemana2ESPN.xlsx')

# Semana 3

In [46]:
# Especifica la ubicación del controlador de Chrome (chromedriver.exe)
chromedriver_path = 'chromedriver.exe'

# Configura el servicio de Chrome con el argumento executable_path
chrome_service = ChromeService(executable_path=chromedriver_path)

# Crea una instancia del navegador Chrome con el servicio configurado
driver = webdriver.Chrome(service=chrome_service)

# Abre la página web
url = 'https://web.archive.org/web/20230928160036/https://www.espn.com/nfl/stats/team/_/view/defense'
driver.get(url)

# Espera a que la tabla esté presente en la página
wait = WebDriverWait(driver, 10)
tabla_presente = EC.presence_of_element_located((By.CSS_SELECTOR, '.Table.Table--align-right.Table--fixed.Table--fixed-left'))
tabla = wait.until(tabla_presente)

# Obtén el contenido HTML de la ta bla
tabla_html = tabla.get_attribute('outerHTML')

# Utiliza BeautifulSoup para analizar el contenido HTML
soup = BeautifulSoup(tabla_html, 'html.parser')

# Encuentra todas las filas de la tabla
filas = soup.find_all('tr')

# Inicializa una lista para almacenar los datos
datos = []

# Recorre las filas y obtén los datos de cada celda
for fila in filas:
    celdas = fila.find_all('td')
    if celdas:  # Verifica si hay al menos una celda de datos en la fila
        fila_datos = [celda.text.strip() for celda in celdas]
        datos.append(fila_datos)

# Crea un DataFrame de Pandas con los datos filtrados
columnas = ['Equipo']  # Reemplaza con el nombre de tu columna
dfdefsem3 = pd.DataFrame(datos, columns=columnas)


# Cierra el navegador
driver.quit()

In [47]:
dfdefsem3

                   Equipo
0        Cleveland Browns
1           Buffalo Bills
2     San Francisco 49ers
3          Dallas Cowboys
4    New England Patriots
5      Kansas City Chiefs
6        Los Angeles Rams
7         Atlanta Falcons
8      New Orleans Saints
9        Baltimore Ravens
10          Detroit Lions
11    Philadelphia Eagles
12      Carolina Panthers
13  Washington Commanders
14      Green Bay Packers
15         Houston Texans
16       Tennessee Titans
17      Las Vegas Raiders
18   Jacksonville Jaguars
19          New York Jets
20     Cincinnati Bengals
21   Tampa Bay Buccaneers
22         Miami Dolphins
23        New York Giants
24     Indianapolis Colts
25      Arizona Cardinals
26      Minnesota Vikings
27    Pittsburgh Steelers
28          Chicago Bears
29       Seattle Seahawks
30   Los Angeles Chargers
31         Denver Broncos

In [36]:
urldefsem3 = "https://web.archive.org/web/20230928160036/https://www.espn.com/nfl/stats/team/_/view/defense"

In [37]:
rdefsem3 = requests.get(urldefsem3, cookies=cookies, headers=headers)
html_contentsdefsem3 = rdefsem3.text

In [38]:
html_soupdefsem3 = BeautifulSoup(html_contentsdefsem3, 'html.parser')

In [39]:
tabla_puntajedefsem3 = html_soupdefsem3.find_all('table', class_='Table Table--align-right')

In [40]:
columnasdefsem3 =  ['GP','YDS','YDS/G','YDS','YDS/G',
             'YDS','YDS/G','PTS','PTS/G',]

In [41]:
infdefsem3 = pd.DataFrame(columns = columnasdefsem3)

In [42]:
for table in tabla_puntajedefsem3:
    for row in table.find_all('tr')[2:]:
        values = []
        for col in row.find_all(['th','td']):
            values.append(col.text)
        if len(values) == len(columnasdefsem3):
            infdefsem3.loc[len(infdefsem3)] = values

In [43]:
infdefsem3

   GP    YDS  YDS/G    YDS  YDS/G  YDS  YDS/G  PTS PTS/G
0   3    491  163.7    335  111.7  156   52.0   32  10.7
1   3    759  253.0    427  142.3  332  110.7   35  11.7
2   3    775  258.3    616  205.3  159   53.0   42  14.0
3   3    786  262.0    392  130.7  394  131.3   38  12.7
4   3    811  270.3    531  177.0  280   93.3   59  19.7
5   3    842  280.7    534  178.0  308  102.7   40  13.3
6   3    854  284.7    543  181.0  311  103.7   62  20.7
7   3    863  287.7    510  170.0  353  117.7   54  18.0
8   3    864  288.0    565  188.3  299   99.7   50  16.7
9   3    877  292.3    600  200.0  277   92.3   55  18.3
10  3    892  297.3    676  225.3  216   72.0   63  21.0
11  3    930  310.0    785  261.7  145   48.3   59  19.7
12  3    987  329.0    577  192.3  410  136.7   81  27.0
13  3    995  331.7    609  203.0  386  128.7   86  28.7
14  3  1,009  336.3    599  199.7  410  136.7   62  20.7
15  3  1,022  340.7    670  223.3  352  117.3   73  24.3
16  3  1,034  344.7    826  275.3  208   69.3   67  22.3
17  3  1,043  347.7    661  220.3  382  127.3   77  25.7
18  3  1,045  348.3    793  264.3  252   84.0   75  25.0
19  3  1,054  351.3    666  222.0  388  129.3   61  20.3
20  3  1,057  352.3    602  200.7  455  151.7   67  22.3
21  3  1,077  359.0    768  256.0  309  103.0   59  19.7
22  3  1,084  361.3    694  231.3  390  130.0   71  23.7
23  3  1,085  361.7    671  223.7  414  138.0   98  32.7
24  3  1,095  365.0    752  250.7  343  114.3   70  23.3
25  3  1,103  367.7    699  233.0  404  134.7   67  22.3
26  3  1,147  382.3    785  261.7  362  120.7   82  27.3
27  3  1,161  387.0    706  235.3  455  151.7   70  23.3
28  3  1,222  407.3    857  285.7  365  121.7  106  35.3
29  3  1,222  407.3    984  328.0  238   79.3   88  29.3
30  3  1,352  450.7  1,011  337.0  341  113.7   87  29.0
31  3  1,375  458.3    842  280.7  533  177.7  122  40.7

In [48]:
columnsUnidsem3 = pd.concat([dfdefsem3,infdefsem3], axis=1)

In [49]:
columnsUnidsem3

,Equipo,GP,YDS,YDS/G,YDS,YDS/G,YDS,YDS/G,PTS,PTS/G
0,Cleveland Browns,3,491,163.7,335,111.7,156,52.0,32,10.7
1,Buffalo Bills,3,759,253.0,427,142.3,332,110.7,35,11.7
2,San Francisco 49ers,3,775,258.3,616,205.3,159,53.0,42,14.0
3,Dallas Cowboys,3,786,262.0,392,130.7,394,131.3,38,12.7
4,New England Patriots,3,811,270.3,531,177.0,280,93.3,59,19.7
5,Kansas City Chiefs,3,842,280.7,534,178.0,308,102.7,40,13.3
6,Los Angeles Rams,3,854,284.7,543,181.0,311,103.7,62,20.7
7,Atlanta Falcons,3,863,287.7,510,170.0,353,117.7,54,18.0
8,New Orleans Saints,3,864,288.0,565,188.3,299,99.7,50,16.7
9,Baltimore Ravens,3,877,292.3,600,200.0,277,92.3,55,18.3
10,Detroit Lions,3,892,297.3,676,225.3,216,72.0,63,21.0
11,Philadelphia Eagles,3,930,310.0,785,261.7,145,48.3,59,19.7
12,Carolina Panthers,3,987,329.0,577,192.3,410,136.7,81,27.0
13,Washington Commanders,3,995,331.7,609,203.0,386,128.7,86,28.7
14,Green Bay Packers,3,"1,009",336.3,599,199.7,410,136.7,62,20.7
15,Houston Texans,3,"1,022",340.7,670,223.3,352,117.3,73,24.3
16,Tennessee Titans,3,"1,034",344.7,826,275.3,208,69.3,67,22.3
17,Las Vegas Raiders,3,"1,043",347.7,661,220.3,382,127.3,77,25.7
18,Jacksonville Jaguars,3,"1,045",348.3,793,264.3,252,84.0,75,25.0
19,New York Jets,3,"1,054",351.3,666,222.0,388,129.3,61,20.3
20,Cincinnati Bengals,3,"1,057",352.3,602,200.7,455,151.7,67,22.3
21,Tampa Bay Buccaneers,3,"1,077",359.0,768,256.0,309,103.0,59,19.7
22,Miami Dolphins,3,"1,084",361.3,694,231.3,390,130.0,71,23.7
23,New York Giants,3,"1,085",361.7,671,223.7,414,138.0,98,32.7
24,Indianapolis Colts,3,"1,095",365.0,752,250.7,343,114.3,70,23.3
25,Arizona Cardinals,3,"1,103",367.7,699,233.0,404,134.7,67,22.3
26,Minnesota Vikings,3,"1,147",382.3,785,261.7,362,120.7,82,27.3
27,Pittsburgh Steelers,3,"1,161",387.0,706,235.3,455,151.7,70,23.3
28,Chicago Bears,3,"1,222",407.3,857,285.7,365,121.7,106,35.3
29,Seattle Seahawks,3,"1,222",407.3,984,328.0,238,79.3,88,29.3
30,Los Angeles Chargers,3,"1,352",450.7,"1,011",337.0,341,113.7,87,29.0
31,Denver Broncos,3,"1,375",458.3,842,280.7,533,177.7,122,40.7

In [63]:
columnsUnidsem3.to_excel('Export\\defsemana3ESPN.xlsx')

# Semana 4

In [4]:
# Especifica la ubicación del controlador de Chrome (chromedriver.exe)
chromedriver_path = 'chromedriver.exe'

# Configura el servicio de Chrome con el argumento executable_path
chrome_service = ChromeService(executable_path=chromedriver_path)

# Crea una instancia del navegador Chrome con el servicio configurado
driver = webdriver.Chrome(service=chrome_service)

# Abre la página web
url = 'https://www.espn.com.mx/futbol-americano/nfl/estadisticas/equipo'
driver.get(url)

# Espera a que la tabla esté presente en la página
wait = WebDriverWait(driver, 10)
tabla_presente = EC.presence_of_element_located((By.CSS_SELECTOR, '.Table.Table--align-right.Table--fixed.Table--fixed-left'))
tabla = wait.until(tabla_presente)

# Obtén el contenido HTML de la ta bla
tabla_html = tabla.get_attribute('outerHTML')

# Utiliza BeautifulSoup para analizar el contenido HTML
soup = BeautifulSoup(tabla_html, 'html.parser')

# Encuentra todas las filas de la tabla
filas = soup.find_all('tr')

# Inicializa una lista para almacenar los datos
datos = []

# Recorre las filas y obtén los datos de cada celda
for fila in filas:
    celdas = fila.find_all('td')
    if celdas:  # Verifica si hay al menos una celda de datos en la fila
        fila_datos = [celda.text.strip() for celda in celdas]
        datos.append(fila_datos)

# Crea un DataFrame de Pandas con los datos filtrados
columnas = ['Equipo']  # Reemplaza con el nombre de tu columna
dfdefsem4 = pd.DataFrame(datos, columns=columnas)


# Cierra el navegador
driver.quit()

WebDriverException: Message: disconnected: received Inspector.detached event
  (failed to check if window was closed: disconnected: Unable to receive message from renderer)
  (Session info: chrome=117.0.5938.150)
Stacktrace:
	GetHandleVerifier [0x00007FF6A2EE7D12+55474]
	(No symbol) [0x00007FF6A2E577C2]
	(No symbol) [0x00007FF6A2D0E0EB]
	(No symbol) [0x00007FF6A2CFDC45]
	(No symbol) [0x00007FF6A2CFD5FB]
	(No symbol) [0x00007FF6A2CFC64E]
	(No symbol) [0x00007FF6A2CFC5F3]
	(No symbol) [0x00007FF6A2CFBEC5]
	(No symbol) [0x00007FF6A2D18813]
	(No symbol) [0x00007FF6A2D87F59]
	(No symbol) [0x00007FF6A2D6EF33]
	(No symbol) [0x00007FF6A2D43D41]
	(No symbol) [0x00007FF6A2D44F84]
	GetHandleVerifier [0x00007FF6A324B762+3609346]
	GetHandleVerifier [0x00007FF6A32A1A80+3962400]
	GetHandleVerifier [0x00007FF6A3299F0F+3930799]
	GetHandleVerifier [0x00007FF6A2F83CA6+694342]
	(No symbol) [0x00007FF6A2E62218]
	(No symbol) [0x00007FF6A2E5E484]
	(No symbol) [0x00007FF6A2E5E5B2]
	(No symbol) [0x00007FF6A2E4EE13]
	BaseThreadInitThunk [0x00007FF85A277344+20]
	RtlUserThreadStart [0x00007FF85A3E26B1+33]

In [52]:
dfdefsem4

                   Equipo
0          Miami Dolphins
1     San Francisco 49ers
2      Kansas City Chiefs
3        Los Angeles Rams
4     Philadelphia Eagles
5           Buffalo Bills
6    Los Angeles Chargers
7           Detroit Lions
8       Minnesota Vikings
9          Houston Texans
10         Dallas Cowboys
11      Arizona Cardinals
12       Baltimore Ravens
13          Chicago Bears
14         Denver Broncos
15   Jacksonville Jaguars
16  Washington Commanders
17     Indianapolis Colts
18   New England Patriots
19       Seattle Seahawks
20       Cleveland Browns
21   Tampa Bay Buccaneers
22     New Orleans Saints
23        Atlanta Falcons
24      Carolina Panthers
25      Las Vegas Raiders
26      Green Bay Packers
27       Tennessee Titans
28    Pittsburgh Steelers
29          New York Jets
30        New York Giants
31     Cincinnati Bengals

In [53]:
urldefsem4 = "https://www.espn.com.mx/futbol-americano/nfl/estadisticas/equipo"

In [54]:
rdefsem4 = requests.get(urldefsem4, cookies=cookies, headers=headers)
html_contentsdefsem4 = rdefsem4.text

In [55]:
html_soupdefsem4 = BeautifulSoup(html_contentsdefsem4, 'html.parser')

In [56]:
tabla_puntajedefsem4 = html_soupdefsem4.find_all('table', class_='Table Table--align-right')

In [57]:
columnasdefsem4 =  ['GP','YDS','YDS/G','YDS','YDS/G',
             'YDS','YDS/G','PTS','PTS/G',]

In [58]:
infdefsem4 = pd.DataFrame(columns = columnasdefsem4)

In [59]:
for table in tabla_puntajedefsem4:
    for row in table.find_all('tr')[2:]:
        values = []
        for col in row.find_all(['th','td']):
            values.append(col.text)
        if len(values) == len(columnasdefsem4):
            infdefsem4.loc[len(infdefsem4)] = values

In [60]:
infdefsem4

   GP    YDS  YDS/G    YDS  YDS/G  YDS  YDS/G  PTS PTS/G
0   4  2,044  511.0  1,337  334.3  707  176.8  150  37.5
1   4  1,592  398.0    980  245.0  612  153.0  125  31.3
2   4  1,572  393.0  1,024  256.0  548  137.0  101  25.3
3   4  1,571  392.8  1,155  288.8  416  104.0   98  24.5
4   4  1,568  392.0    907  226.8  661  165.3  118  29.5
5   4  1,564  391.0  1,012  253.0  552  138.0  139  34.8
6   4  1,555  388.8  1,076  269.0  479  119.8  110  27.5
7   4  1,545  386.3    999  249.8  546  136.5  106  26.5
8   4  1,483  370.8  1,149  287.3  334   83.5   90  22.5
9   4  1,474  368.5  1,125  281.3  349   87.3   96  24.0
10  4  1,440  360.0    875  218.8  565  141.3  124  31.0
11  4  1,351  337.8    777  194.3  574  143.5   88  22.0
12  4  1,340  335.0    735  183.8  605  151.3   99  24.8
13  5  1,672  334.4  1,018  203.6  654  130.8  115  23.0
14  4  1,333  333.3    951  237.8  382   95.5  100  25.0
15  4  1,317  329.3    917  229.3  400  100.0   80  20.0
16  5  1,619  323.8  1,164  232.8  455   91.0  109  21.8
17  4  1,289  322.3    826  206.5  463  115.8   97  24.3
18  4  1,281  320.3    907  226.8  374   93.5   55  13.8
19  4  1,279  319.8    845  211.3  434  108.5  111  27.8
20  4  1,265  316.3    690  172.5  575  143.8   76  19.0
21  4  1,206  301.5    858  214.5  348   87.0   84  21.0
22  4  1,141  285.3    791  197.8  350   87.5   62  15.5
23  4  1,137  284.3    625  156.3  512  128.0   62  15.5
24  4  1,130  282.5    749  187.3  381   95.3   67  16.8
25  4  1,127  281.8    866  216.5  261   65.3   62  15.5
26  4  1,123  280.8    825  206.3  298   74.5  100  25.0
27  4  1,120  280.0    676  169.0  444  111.0   72  18.0
28  4  1,052  263.0    737  184.3  315   78.8   62  15.5
29  4  1,011  252.8    629  157.3  382   95.5   62  15.5
30  4  1,008  252.0    632  158.0  376   94.0   46  11.5
31  4    944  236.0    664  166.0  280   70.0   49  12.3

In [61]:
columnsUnidsem4 = pd.concat([dfdefsem4,infdefsem4], axis=1)

In [62]:
columnsUnidsem4

,Equipo,GP,YDS,YDS/G,YDS,YDS/G,YDS,YDS/G,PTS,PTS/G
0,Miami Dolphins,4,"2,044",511.0,"1,337",334.3,707,176.8,150,37.5
1,San Francisco 49ers,4,"1,592",398.0,980,245.0,612,153.0,125,31.3
2,Kansas City Chiefs,4,"1,572",393.0,"1,024",256.0,548,137.0,101,25.3
3,Los Angeles Rams,4,"1,571",392.8,"1,155",288.8,416,104.0,98,24.5
4,Philadelphia Eagles,4,"1,568",392.0,907,226.8,661,165.3,118,29.5
5,Buffalo Bills,4,"1,564",391.0,"1,012",253.0,552,138.0,139,34.8
6,Los Angeles Chargers,4,"1,555",388.8,"1,076",269.0,479,119.8,110,27.5
7,Detroit Lions,4,"1,545",386.3,999,249.8,546,136.5,106,26.5
8,Minnesota Vikings,4,"1,483",370.8,"1,149",287.3,334,83.5,90,22.5
9,Houston Texans,4,"1,474",368.5,"1,125",281.3,349,87.3,96,24.0
10,Dallas Cowboys,4,"1,440",360.0,875,218.8,565,141.3,124,31.0
11,Arizona Cardinals,4,"1,351",337.8,777,194.3,574,143.5,88,22.0
12,Baltimore Ravens,4,"1,340",335.0,735,183.8,605,151.3,99,24.8
13,Chicago Bears,5,"1,672",334.4,"1,018",203.6,654,130.8,115,23.0
14,Denver Broncos,4,"1,333",333.3,951,237.8,382,95.5,100,25.0
15,Jacksonville Jaguars,4,"1,317",329.3,917,229.3,400,100.0,80,20.0
16,Washington Commanders,5,"1,619",323.8,"1,164",232.8,455,91.0,109,21.8
17,Indianapolis Colts,4,"1,289",322.3,826,206.5,463,115.8,97,24.3
18,New England Patriots,4,"1,281",320.3,907,226.8,374,93.5,55,13.8
19,Seattle Seahawks,4,"1,279",319.8,845,211.3,434,108.5,111,27.8
20,Cleveland Browns,4,"1,265",316.3,690,172.5,575,143.8,76,19.0
21,Tampa Bay Buccaneers,4,"1,206",301.5,858,214.5,348,87.0,84,21.0
22,New Orleans Saints,4,"1,141",285.3,791,197.8,350,87.5,62,15.5
23,Atlanta Falcons,4,"1,137",284.3,625,156.3,512,128.0,62,15.5
24,Carolina Panthers,4,"1,130",282.5,749,187.3,381,95.3,67,16.8
25,Las Vegas Raiders,4,"1,127",281.8,866,216.5,261,65.3,62,15.5
26,Green Bay Packers,4,"1,123",280.8,825,206.3,298,74.5,100,25.0
27,Tennessee Titans,4,"1,120",280.0,676,169.0,444,111.0,72,18.0
28,Pittsburgh Steelers,4,"1,052",263.0,737,184.3,315,78.8,62,15.5
29,New York Jets,4,"1,011",252.8,629,157.3,382,95.5,62,15.5
30,New York Giants,4,"1,008",252.0,632,158.0,376,94.0,46,11.5
31,Cincinnati Bengals,4,944,236.0,664,166.0,280,70.0,49,12.3

In [64]:
columnsUnidsem4.to_excel('Export\\defsemana4ESPN.xlsx')

In [5]:
# Especifica la ubicación del controlador de Chrome (chromedriver.exe)
chromedriver_path = 'chromedriver.exe'

# Configura el servicio de Chrome con el argumento executable_path
chrome_service = ChromeService(executable_path=chromedriver_path)

# Crea una instancia del navegador Chrome con el servicio configurado
driver = webdriver.Chrome(service=chrome_service)

# Abre la página web
url = 'https://www.espn.com.mx/futbol-americano/nfl/estadisticas/equipo/_/vista/defensiva'
driver.get(url)

# Espera a que la tabla esté presente en la página
wait = WebDriverWait(driver, 10)
tabla_presente = EC.presence_of_element_located((By.CSS_SELECTOR, '.Table.Table--align-right.Table--fixed.Table--fixed-left'))
tabla = wait.until(tabla_presente)

# Obtén el contenido HTML de la ta bla
tabla_html = tabla.get_attribute('outerHTML')

# Utiliza BeautifulSoup para analizar el contenido HTML
soup = BeautifulSoup(tabla_html, 'html.parser')

# Encuentra todas las filas de la tabla
filas = soup.find_all('tr')

# Inicializa una lista para almacenar los datos
datos = []

# Recorre las filas y obtén los datos de cada celda
for fila in filas:
    celdas = fila.find_all('td')
    if celdas:  # Verifica si hay al menos una celda de datos en la fila
        fila_datos = [celda.text.strip() for celda in celdas]
        datos.append(fila_datos)

# Crea un DataFrame de Pandas con los datos filtrados
columnas = ['Equipo']  # Reemplaza con el nombre de tu columna
dfdefsem5 = pd.DataFrame(datos, columns=columnas)


# Cierra el navegador
driver.quit()

In [6]:
dfdefsem5

                   Equipo
0        Cleveland Browns
1        Baltimore Ravens
2     San Francisco 49ers
3      New Orleans Saints
4          Dallas Cowboys
5           Detroit Lions
6         Atlanta Falcons
7    New England Patriots
8      Kansas City Chiefs
9     Philadelphia Eagles
10   Tampa Bay Buccaneers
11          Buffalo Bills
12      Carolina Panthers
13      Las Vegas Raiders
14       Los Angeles Rams
15       Tennessee Titans
16      Green Bay Packers
17         Houston Texans
18      Minnesota Vikings
19   Jacksonville Jaguars
20     Cincinnati Bengals
21          New York Jets
22         Miami Dolphins
23       Seattle Seahawks
24  Washington Commanders
25      Arizona Cardinals
26        New York Giants
27     Indianapolis Colts
28          Chicago Bears
29    Pittsburgh Steelers
30   Los Angeles Chargers
31         Denver Broncos

In [7]:
urldefsem5 = "https://www.espn.com.mx/futbol-americano/nfl/estadisticas/equipo/_/vista/defensiva"

In [8]:
rdefsem5 = requests.get(urldefsem5, cookies=cookies, headers=headers)
html_contentsdefsem5 = rdefsem5.text

In [9]:
html_soupdefsem5 = BeautifulSoup(html_contentsdefsem5, 'html.parser')

In [10]:
tabla_puntajedefsem5 = html_soupdefsem5.find_all('table', class_='Table Table--align-right')

In [11]:
columnasdefsem5 =  ['GP','YDS','YDS/G','YDS','YDS/G',
             'YDS','YDS/G','PTS','PTS/G',]

In [12]:
infdefsem5 = pd.DataFrame(columns = columnasdefsem5)

In [13]:
for table in tabla_puntajedefsem5:
    for row in table.find_all('tr')[2:]:
        values = []
        for col in row.find_all(['th','td']):
            values.append(col.text)
        if len(values) == len(columnasdefsem5):
            infdefsem5.loc[len(infdefsem5)] = values

In [14]:
infdefsem5

   GP    YDS  YDS/G    YDS  YDS/G  YDS  YDS/G  PTS PTS/G
0   4    787  196.8    500  125.0  287   71.8   60  15.0
1   5  1,332  266.4    875  175.0  457   91.4   75  15.0
2   5  1,334  266.8  1,013  202.6  321   64.2   68  13.6
3   5  1,373  274.6    915  183.0  458   91.6   76  15.2
4   5  1,460  292.0    843  168.6  617  123.4   83  16.6
5   5  1,464  292.8  1,122  224.4  342   68.4  107  21.4
6   5  1,476  295.2    954  190.8  522  104.4   96  19.2
7   5  1,492  298.4    952  190.4  540  108.0  131  26.2
8   5  1,507  301.4  1,021  204.2  486   97.2   80  16.0
9   5  1,544  308.8  1,238  247.6  306   61.2  104  20.8
10  4  1,274  318.5    895  223.8  379   94.8   68  17.0
11  5  1,626  325.2    956  191.2  670  134.0   80  16.0
12  5  1,629  325.8    925  185.0  704  140.8  144  28.8
13  5  1,633  326.6    986  197.2  647  129.4  114  22.8
14  5  1,637  327.4  1,034  206.8  603  120.6  108  21.6
15  5  1,674  334.8  1,201  240.2  473   94.6   93  18.6
16  5  1,689  337.8    972  194.4  717  143.4  113  22.6
17  5  1,694  338.8  1,132  226.4  562  112.4  100  20.0
18  5  1,712  342.4  1,200  240.0  512  102.4  122  24.4
19  5  1,720  344.0  1,312  262.4  408   81.6  102  20.4
20  5  1,751  350.2    981  196.2  770  154.0  114  22.8
21  5  1,763  352.6  1,032  206.4  731  146.2  105  21.0
22  5  1,766  353.2  1,187  237.4  579  115.8  135  27.0
23  4  1,470  367.5  1,120  280.0  350   87.5   91  22.8
24  5  1,861  372.2  1,193  238.6  668  133.6  160  32.0
25  5  1,878  375.6  1,257  251.4  621  124.2  136  27.2
26  5  1,890  378.0  1,133  226.6  757  151.4  153  30.6
27  5  1,910  382.0  1,314  262.8  596  119.2  115  23.0
28  5  1,921  384.2  1,430  286.0  491   98.2  157  31.4
29  5  1,947  389.4  1,228  245.6  719  143.8  110  22.0
30  4  1,616  404.0  1,199  299.8  417  104.3  104  26.0
31  5  2,253  450.6  1,315  263.0  938  187.6  181  36.2

In [15]:
columnsUnidsem5 = pd.concat([dfdefsem5,infdefsem5], axis=1)

In [16]:
columnsUnidsem5

,Equipo,GP,YDS,YDS/G,YDS,YDS/G,YDS,YDS/G,PTS,PTS/G
0,Cleveland Browns,4,787,196.8,500,125.0,287,71.8,60,15.0
1,Baltimore Ravens,5,"1,332",266.4,875,175.0,457,91.4,75,15.0
2,San Francisco 49ers,5,"1,334",266.8,"1,013",202.6,321,64.2,68,13.6
3,New Orleans Saints,5,"1,373",274.6,915,183.0,458,91.6,76,15.2
4,Dallas Cowboys,5,"1,460",292.0,843,168.6,617,123.4,83,16.6
5,Detroit Lions,5,"1,464",292.8,"1,122",224.4,342,68.4,107,21.4
6,Atlanta Falcons,5,"1,476",295.2,954,190.8,522,104.4,96,19.2
7,New England Patriots,5,"1,492",298.4,952,190.4,540,108.0,131,26.2
8,Kansas City Chiefs,5,"1,507",301.4,"1,021",204.2,486,97.2,80,16.0
9,Philadelphia Eagles,5,"1,544",308.8,"1,238",247.6,306,61.2,104,20.8
10,Tampa Bay Buccaneers,4,"1,274",318.5,895,223.8,379,94.8,68,17.0
11,Buffalo Bills,5,"1,626",325.2,956,191.2,670,134.0,80,16.0
12,Carolina Panthers,5,"1,629",325.8,925,185.0,704,140.8,144,28.8
13,Las Vegas Raiders,5,"1,633",326.6,986,197.2,647,129.4,114,22.8
14,Los Angeles Rams,5,"1,637",327.4,"1,034",206.8,603,120.6,108,21.6
15,Tennessee Titans,5,"1,674",334.8,"1,201",240.2,473,94.6,93,18.6
16,Green Bay Packers,5,"1,689",337.8,972,194.4,717,143.4,113,22.6
17,Houston Texans,5,"1,694",338.8,"1,132",226.4,562,112.4,100,20.0
18,Minnesota Vikings,5,"1,712",342.4,"1,200",240.0,512,102.4,122,24.4
19,Jacksonville Jaguars,5,"1,720",344.0,"1,312",262.4,408,81.6,102,20.4
20,Cincinnati Bengals,5,"1,751",350.2,981,196.2,770,154.0,114,22.8
21,New York Jets,5,"1,763",352.6,"1,032",206.4,731,146.2,105,21.0
22,Miami Dolphins,5,"1,766",353.2,"1,187",237.4,579,115.8,135,27.0
23,Seattle Seahawks,4,"1,470",367.5,"1,120",280.0,350,87.5,91,22.8
24,Washington Commanders,5,"1,861",372.2,"1,193",238.6,668,133.6,160,32.0
25,Arizona Cardinals,5,"1,878",375.6,"1,257",251.4,621,124.2,136,27.2
26,New York Giants,5,"1,890",378.0,"1,133",226.6,757,151.4,153,30.6
27,Indianapolis Colts,5,"1,910",382.0,"1,314",262.8,596,119.2,115,23.0
28,Chicago Bears,5,"1,921",384.2,"1,430",286.0,491,98.2,157,31.4
29,Pittsburgh Steelers,5,"1,947",389.4,"1,228",245.6,719,143.8,110,22.0
30,Los Angeles Chargers,4,"1,616",404.0,"1,199",299.8,417,104.3,104,26.0
31,Denver Broncos,5,"2,253",450.6,"1,315",263.0,938,187.6,181,36.2

In [18]:
columnsUnidsem5.to_excel('Export\\defsemana5ESPN.xlsx')