In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from sqlalchemy import create_engine
from collections import namedtuple
import pymysql
import mysql.connector

In [2]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36'
}

cookies = {
    'cookie_name': 'cookie_value'
}

In [3]:
url = "https://www.espn.com.mx/futbol-americano/nfl/posiciones/_/grupo/liga"

In [4]:
r = requests.get(url, cookies=cookies, headers=headers)
html_contents = r.text

In [ ]:
html_soup = BeautifulSoup(html_contents, 'html.parser')

In [ ]:
# Encuentra todos los elementos span con la clase hide-mobile
elementos_equipo = html_soup.find_all('span', class_='hide-mobile')
elementos_equipo_cont = html_soup.find_all('span', class_='dn show-mobile')
# Inicializa una lista para almacenar los nombres de los equipos
nombres_equipos = []
nom_cont = []
# Itera sobre los elementos y obtén el texto de cada uno
for elemento_equipo in elementos_equipo:
    nombre_equipo = elemento_equipo.text
    nombres_equipos.append(nombre_equipo)

for elemento_equipo_cont in elementos_equipo_cont:
    nombre_cont = elemento_equipo_cont.text
    nom_cont.append(nombre_cont)

# Ahora, nombres_equipos contendrá los nombres de todos los equipos

In [ ]:
# Crea un DataFrame con una columna llamada 'Nombre_Equipo'
df = pd.DataFrame({'Nombre_Abreviado': nom_cont   ,'Nombre_Equipo': nombres_equipos})

# Si deseas agregar un índice numérico, puedes hacerlo así:
df.index = range(1, len(df) + 1)  # Índice de 1 a n (número de equipos)

In [ ]:
df

   Nombre_Abreviado          Nombre_Equipo
1               DAL         Dallas Cowboys
2               MIA         Miami Dolphins
3                SF    San Francisco 49ers
4               BAL       Baltimore Ravens
5               ATL        Atlanta Falcons
6                NO     New Orleans Saints
7                TB   Tampa Bay Buccaneers
8               PHI    Philadelphia Eagles
9               WSH  Washington Commanders
10              JAX   Jacksonville Jaguars
11               GB      Green Bay Packers
12               LV      Las Vegas Raiders
13              PIT    Pittsburgh Steelers
14              NYJ          New York Jets
15               KC     Kansas City Chiefs
16              BUF          Buffalo Bills
17              IND     Indianapolis Colts
18              LAR       Los Angeles Rams
19              TEN       Tennessee Titans
20              SEA       Seattle Seahawks
21              CLE       Cleveland Browns
22              NYG        New York Giants
23              DET          Detroit Lions
24               NE   New England Patriots
25              MIN      Minnesota Vikings
26              LAC   Los Angeles Chargers
27              CAR      Carolina Panthers
28              HOU         Houston Texans
29              CIN     Cincinnati Bengals
30              ARI      Arizona Cardinals
31              CHI          Chicago Bears
32              DEN         Denver Broncos

In [ ]:
df.to_excel('Export\\NombresNFL.xlsx')

In [ ]:
my_conn = create_engine("mysql+pymysql://root:Edgar821@localhost/nfl")

In [ ]:
df.to_sql(con=my_conn , name = 'nombrescort', if_exists='replace', index=True )

32