In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.service import Service as ChromeService
from bs4 import BeautifulSoup
import pandas as pd
import requests

In [2]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36'
}

cookies = {
    'cookie_name': 'cookie_value'
}

# Semana 1

In [3]:
# Especifica la ubicación del controlador de Chrome (chromedriver.exe)
chromedriver_path = 'chromedriver.exe'

# Configura el servicio de Chrome con el argumento executable_path
chrome_service = ChromeService(executable_path=chromedriver_path)

# Crea una instancia del navegador Chrome con el servicio configurado
driver = webdriver.Chrome(service=chrome_service)

# Abre la página web
url = 'https://web.archive.org/web/20230912201251/https://www.espn.com/nfl/stats/team'
driver.get(url)

# Espera a que la tabla esté presente en la página
wait = WebDriverWait(driver, 10)
tabla_presente = EC.presence_of_element_located((By.CSS_SELECTOR, '.Table.Table--align-right.Table--fixed.Table--fixed-left'))
tabla = wait.until(tabla_presente)

# Obtén el contenido HTML de la ta bla
tabla_html = tabla.get_attribute('outerHTML')

# Utiliza BeautifulSoup para analizar el contenido HTML
soup = BeautifulSoup(tabla_html, 'html.parser')

# Encuentra todas las filas de la tabla
filas = soup.find_all('tr')

# Inicializa una lista para almacenar los datos
datos = []

# Recorre las filas y obtén los datos de cada celda
for fila in filas:
    celdas = fila.find_all('td')
    if celdas:  # Verifica si hay al menos una celda de datos en la fila
        fila_datos = [celda.text.strip() for celda in celdas]
        datos.append(fila_datos)

# Crea un DataFrame de Pandas con los datos filtrados
columnas = ['Equipo']  # Reemplaza con el nombre de tu columna
dfoffsem1 = pd.DataFrame(datos, columns=columnas)


# Cierra el navegador
driver.quit()

In [4]:
dfoffsem1

                   Equipo
0          Miami Dolphins
1    Los Angeles Chargers
2        Los Angeles Rams
3     San Francisco 49ers
4    New England Patriots
5       Minnesota Vikings
6           Detroit Lions
7      New Orleans Saints
8        Cleveland Browns
9    Jacksonville Jaguars
10      Green Bay Packers
11     Kansas City Chiefs
12          Buffalo Bills
13          Chicago Bears
14          New York Jets
15       Tennessee Titans
16      Carolina Panthers
17     Indianapolis Colts
18         Houston Texans
19         Dallas Cowboys
20       Baltimore Ravens
21      Las Vegas Raiders
22         Denver Broncos
23    Philadelphia Eagles
24  Washington Commanders
25   Tampa Bay Buccaneers
26    Pittsburgh Steelers
27        Atlanta Falcons
28      Arizona Cardinals
29       Seattle Seahawks
30        New York Giants
31     Cincinnati Bengals

In [105]:
urloffsem1 = "https://web.archive.org/web/20230912201251/https://www.espn.com/nfl/stats/team"

In [106]:
roffsem1 = requests.get(urloffsem1, cookies=cookies, headers=headers)
html_contentsoffsem1 = roffsem1.text

In [107]:
html_soupoffsem1 = BeautifulSoup(html_contentsoffsem1, 'html.parser')

In [108]:
tabla_puntajeoffsem1 = html_soupoffsem1.find_all('table', class_='Table Table--align-right')

In [109]:
columnasoffsem1 =  ['GP','YDS','YDS/G','YDS','YDS/G',
             'YDS','YDS/G','PTS','PTS/G',]

In [111]:
infoffsem1 = pd.DataFrame(columns = columnasoffsem1)

In [112]:
for table in tabla_puntajeoffsem1:
    for row in table.find_all('tr')[2:]:
        values = []
        for col in row.find_all(['th','td']):
            values.append(col.text)
        if len(values) == len(columnasoffsem1):
            infoffsem1.loc[len(infoffsem1)] = values

In [113]:
infoffsem1

   GP  YDS  YDS/G  YDS  YDS/G  YDS  YDS/G PTS PTS/G
0   1  536  536.0  466  466.0   70   70.0  36  36.0
1   1  433  433.0  199  199.0  234  234.0  34  34.0
2   1  426  426.0  334  334.0   92   92.0  30  30.0
3   1  391  391.0  203  203.0  188  188.0  30  30.0
4   1  382  382.0  306  306.0   76   76.0  20  20.0
5   1  369  369.0  328  328.0   41   41.0  17  17.0
6   1  368  368.0  250  250.0  118  118.0  21  21.0
7   1  351  351.0  282  282.0   69   69.0  16  16.0
8   1  350  350.0  144  144.0  206  206.0  24  24.0
9   1  342  342.0  237  237.0  105  105.0  31  31.0
10  1  329  329.0  237  237.0   92   92.0  38  38.0
11  1  316  316.0  226  226.0   90   90.0  20  20.0
12  1  314  314.0  217  217.0   97   97.0  16  16.0
13  1  311  311.0  189  189.0  122  122.0  20  20.0
14  1  289  289.0  117  117.0  172  172.0  22  22.0
15  1  285  285.0  181  181.0  104  104.0  15  15.0
16  1  281  281.0  127  127.0  154  154.0  10  10.0
17  1  280  280.0  215  215.0   65   65.0  21  21.0
18  1  268  268.0  196  196.0   72   72.0   9   9.0
19  1  265  265.0  143  143.0  122  122.0  40  40.0
20  1  265  265.0  155  155.0  110  110.0  25  25.0
21  1  261  261.0  200  200.0   61   61.0  17  17.0
22  1  260  260.0  166  166.0   94   94.0  16  16.0
23  1  251  251.0  154  154.0   97   97.0  25  25.0
24  1  248  248.0  156  156.0   92   92.0  20  20.0
25  1  242  242.0  169  169.0   73   73.0  20  20.0
26  1  239  239.0  198  198.0   41   41.0   7   7.0
27  1  221  221.0   91   91.0  130  130.0  24  24.0
28  1  210  210.0  114  114.0   96   96.0  16  16.0
29  1  180  180.0   95   95.0   85   85.0  13  13.0
30  1  171  171.0   63   63.0  108  108.0   0   0.0
31  1  142  142.0   67   67.0   75   75.0   3   3.0

In [114]:
columnsUnid = pd.concat([dfoffsem1,infoffsem1], axis=1)

In [115]:
columnsUnid

                   Equipo GP  YDS  YDS/G  YDS  YDS/G  YDS  YDS/G PTS PTS/G
0          Miami Dolphins  1  536  536.0  466  466.0   70   70.0  36  36.0
1    Los Angeles Chargers  1  433  433.0  199  199.0  234  234.0  34  34.0
2        Los Angeles Rams  1  426  426.0  334  334.0   92   92.0  30  30.0
3     San Francisco 49ers  1  391  391.0  203  203.0  188  188.0  30  30.0
4    New England Patriots  1  382  382.0  306  306.0   76   76.0  20  20.0
5       Minnesota Vikings  1  369  369.0  328  328.0   41   41.0  17  17.0
6           Detroit Lions  1  368  368.0  250  250.0  118  118.0  21  21.0
7      New Orleans Saints  1  351  351.0  282  282.0   69   69.0  16  16.0
8        Cleveland Browns  1  350  350.0  144  144.0  206  206.0  24  24.0
9    Jacksonville Jaguars  1  342  342.0  237  237.0  105  105.0  31  31.0
10      Green Bay Packers  1  329  329.0  237  237.0   92   92.0  38  38.0
11     Kansas City Chiefs  1  316  316.0  226  226.0   90   90.0  20  20.0
12          Buffalo Bills  1  314  314.0  217  217.0   97   97.0  16  16.0
13          Chicago Bears  1  311  311.0  189  189.0  122  122.0  20  20.0
14          New York Jets  1  289  289.0  117  117.0  172  172.0  22  22.0
15       Tennessee Titans  1  285  285.0  181  181.0  104  104.0  15  15.0
16      Carolina Panthers  1  281  281.0  127  127.0  154  154.0  10  10.0
17     Indianapolis Colts  1  280  280.0  215  215.0   65   65.0  21  21.0
18         Houston Texans  1  268  268.0  196  196.0   72   72.0   9   9.0
19         Dallas Cowboys  1  265  265.0  143  143.0  122  122.0  40  40.0
20       Baltimore Ravens  1  265  265.0  155  155.0  110  110.0  25  25.0
21      Las Vegas Raiders  1  261  261.0  200  200.0   61   61.0  17  17.0
22         Denver Broncos  1  260  260.0  166  166.0   94   94.0  16  16.0
23    Philadelphia Eagles  1  251  251.0  154  154.0   97   97.0  25  25.0
24  Washington Commanders  1  248  248.0  156  156.0   92   92.0  20  20.0
25   Tampa Bay Buccaneers  1  242  242.0  169  169.0   73   73.0  20  20.0
26    Pittsburgh Steelers  1  239  239.0  198  198.0   41   41.0   7   7.0
27        Atlanta Falcons  1  221  221.0   91   91.0  130  130.0  24  24.0
28      Arizona Cardinals  1  210  210.0  114  114.0   96   96.0  16  16.0
29       Seattle Seahawks  1  180  180.0   95   95.0   85   85.0  13  13.0
30        New York Giants  1  171  171.0   63   63.0  108  108.0   0   0.0
31     Cincinnati Bengals  1  142  142.0   67   67.0   75   75.0   3   3.0

In [116]:
columnsUnid.to_excel('Export\\Ofensemana1ESPN.xlsx')

# Semana 2

In [131]:
# Especifica la ubicación del controlador de Chrome (chromedriver.exe)
chromedriver_path = 'chromedriver.exe'

# Configura el servicio de Chrome con el argumento executable_path
chrome_service = ChromeService(executable_path=chromedriver_path)

# Crea una instancia del navegador Chrome con el servicio configurado
driver = webdriver.Chrome(service=chrome_service)

# Abre la página web
url = 'https://web.archive.org/web/20230920202615/https://www.espn.com/nfl/stats/team'
driver.get(url)

# Espera a que la tabla esté presente en la página
wait = WebDriverWait(driver, 10)
tabla_presente = EC.presence_of_element_located((By.CSS_SELECTOR, '.Table.Table--align-right.Table--fixed.Table--fixed-left'))
tabla = wait.until(tabla_presente)

# Obtén el contenido HTML de la ta bla
tabla_html = tabla.get_attribute('outerHTML')

# Utiliza BeautifulSoup para analizar el contenido HTML
soup = BeautifulSoup(tabla_html, 'html.parser')

# Encuentra todas las filas de la tabla
filas = soup.find_all('tr')

# Inicializa una lista para almacenar los datos
datos = []

# Recorre las filas y obtén los datos de cada celda
for fila in filas:
    celdas = fila.find_all('td')
    if celdas:  # Verifica si hay al menos una celda de datos en la fila
        fila_datos = [celda.text.strip() for celda in celdas]
        datos.append(fila_datos)

# Crea un DataFrame de Pandas con los datos filtrados
columnas = ['Equipo']  # Reemplaza con el nombre de tu columna
dfoffsem2 = pd.DataFrame(datos, columns=columnas)


# Cierra el navegador
driver.quit()

In [133]:
dfoffsem2

                   Equipo
0          Miami Dolphins
1        Los Angeles Rams
2           Detroit Lions
3    Los Angeles Chargers
4           Buffalo Bills
5        Cleveland Browns
6     San Francisco 49ers
7       Minnesota Vikings
8      Kansas City Chiefs
9      New Orleans Saints
10    Philadelphia Eagles
11       Baltimore Ravens
12   Tampa Bay Buccaneers
13   New England Patriots
14        Atlanta Falcons
15         Denver Broncos
16         Houston Texans
17         Dallas Cowboys
18  Washington Commanders
19     Indianapolis Colts
20       Tennessee Titans
21   Jacksonville Jaguars
22        New York Giants
23      Arizona Cardinals
24       Seattle Seahawks
25      Green Bay Packers
26          Chicago Bears
27      Carolina Panthers
28          New York Jets
29      Las Vegas Raiders
30    Pittsburgh Steelers
31     Cincinnati Bengals

In [134]:
urloffsem2 = "https://web.archive.org/web/20230920202615/https://www.espn.com/nfl/stats/team"

In [135]:
roffsem2 = requests.get(urloffsem2, cookies=cookies, headers=headers)
html_contentsoffsem2 = roffsem2.text

In [136]:
html_soupoffsem2 = BeautifulSoup(html_contentsoffsem2, 'html.parser')

In [137]:
tabla_puntajeoffsem2 = html_soupoffsem2.find_all('table', class_='Table Table--align-right')

In [138]:
columnasoffsem2 =  ['GP','YDS','YDS/G','YDS','YDS/G',
             'YDS','YDS/G','PTS','PTS/G',]

In [139]:
infoffsem2 = pd.DataFrame(columns = columnasoffsem2)

In [140]:
for table in tabla_puntajeoffsem2:
    for row in table.find_all('tr')[2:]:
        values = []
        for col in row.find_all(['th','td']):
            values.append(col.text)
        if len(values) == len(columnasoffsem2):
            infoffsem2.loc[len(infoffsem2)] = values

In [141]:
infoffsem2

   GP  YDS  YDS/G  YDS  YDS/G  YDS  YDS/G PTS PTS/G
0   2  925  462.5  710  355.0  215  107.5  60  30.0
1   2  812  406.0  631  315.5  181   90.5  53  26.5
2   2  786  393.0  566  283.0  220  110.0  52  26.0
3   2  775  387.5  481  240.5  294  147.0  58  29.0
4   2  764  382.0  484  242.0  280  140.0  54  27.0
5   2  758  379.0  354  177.0  404  202.0  46  23.0
6   2  756  378.0  409  204.5  347  173.5  60  30.0
7   2  743  371.5  674  337.0   69   34.5  45  22.5
8   2  715  357.5  524  262.0  191   95.5  37  18.5
9   2  692  346.0  489  244.5  203  101.5  36  18.0
10  2  681  340.5  325  162.5  356  178.0  59  29.5
11  2  680  340.0  392  196.0  288  144.0  52  26.0
12  2  679  339.5  486  243.0  193   96.5  47  23.5
13  2  670  335.0  506  253.0  164   82.0  37  18.5
14  2  667  333.5  326  163.0  341  170.5  49  24.5
15  2  659  329.5  443  221.5  216  108.0  49  24.5
16  2  657  328.5  533  266.5  124   62.0  29  14.5
17  2  647  323.5  391  195.5  256  128.0  70  35.0
18  2  636  318.0  422  211.0  214  107.0  55  27.5
19  2  633  316.5  442  221.0  191   95.5  52  26.0
20  2  626  313.0  381  190.5  245  122.5  42  21.0
21  2  613  306.5  434  217.0  179   89.5  40  20.0
22  2  610  305.0  375  187.5  235  117.5  31  15.5
23  2  589  294.5  342  171.0  247  123.5  44  22.0
24  2  573  286.5  406  203.0  167   83.5  50  25.0
25  2  553  276.5  377  188.5  176   88.0  62  31.0
26  2  547  273.5  358  179.0  189   94.5  37  18.5
27  2  520  260.0  266  133.0  254  127.0  27  13.5
28  2  504  252.0  268  134.0  236  118.0  32  16.0
29  2  501  250.5  385  192.5  116   58.0  27  13.5
30  2  494  247.0  398  199.0   96   48.0  33  16.5
31  2  424  212.0  283  141.5  141   70.5  27  13.5

In [142]:
columnsUnidsem2 = pd.concat([dfoffsem2,infoffsem2], axis=1)

In [144]:
columnsUnidsem2

                   Equipo GP  YDS  YDS/G  YDS  YDS/G  YDS  YDS/G PTS PTS/G
0          Miami Dolphins  2  925  462.5  710  355.0  215  107.5  60  30.0
1        Los Angeles Rams  2  812  406.0  631  315.5  181   90.5  53  26.5
2           Detroit Lions  2  786  393.0  566  283.0  220  110.0  52  26.0
3    Los Angeles Chargers  2  775  387.5  481  240.5  294  147.0  58  29.0
4           Buffalo Bills  2  764  382.0  484  242.0  280  140.0  54  27.0
5        Cleveland Browns  2  758  379.0  354  177.0  404  202.0  46  23.0
6     San Francisco 49ers  2  756  378.0  409  204.5  347  173.5  60  30.0
7       Minnesota Vikings  2  743  371.5  674  337.0   69   34.5  45  22.5
8      Kansas City Chiefs  2  715  357.5  524  262.0  191   95.5  37  18.5
9      New Orleans Saints  2  692  346.0  489  244.5  203  101.5  36  18.0
10    Philadelphia Eagles  2  681  340.5  325  162.5  356  178.0  59  29.5
11       Baltimore Ravens  2  680  340.0  392  196.0  288  144.0  52  26.0
12   Tampa Bay Buccaneers  2  679  339.5  486  243.0  193   96.5  47  23.5
13   New England Patriots  2  670  335.0  506  253.0  164   82.0  37  18.5
14        Atlanta Falcons  2  667  333.5  326  163.0  341  170.5  49  24.5
15         Denver Broncos  2  659  329.5  443  221.5  216  108.0  49  24.5
16         Houston Texans  2  657  328.5  533  266.5  124   62.0  29  14.5
17         Dallas Cowboys  2  647  323.5  391  195.5  256  128.0  70  35.0
18  Washington Commanders  2  636  318.0  422  211.0  214  107.0  55  27.5
19     Indianapolis Colts  2  633  316.5  442  221.0  191   95.5  52  26.0
20       Tennessee Titans  2  626  313.0  381  190.5  245  122.5  42  21.0
21   Jacksonville Jaguars  2  613  306.5  434  217.0  179   89.5  40  20.0
22        New York Giants  2  610  305.0  375  187.5  235  117.5  31  15.5
23      Arizona Cardinals  2  589  294.5  342  171.0  247  123.5  44  22.0
24       Seattle Seahawks  2  573  286.5  406  203.0  167   83.5  50  25.0
25      Green Bay Packers  2  553  276.5  377  188.5  176   88.0  62  31.0
26          Chicago Bears  2  547  273.5  358  179.0  189   94.5  37  18.5
27      Carolina Panthers  2  520  260.0  266  133.0  254  127.0  27  13.5
28          New York Jets  2  504  252.0  268  134.0  236  118.0  32  16.0
29      Las Vegas Raiders  2  501  250.5  385  192.5  116   58.0  27  13.5
30    Pittsburgh Steelers  2  494  247.0  398  199.0   96   48.0  33  16.5
31     Cincinnati Bengals  2  424  212.0  283  141.5  141   70.5  27  13.5

In [145]:
columnsUnidsem2.to_excel('Export\\Ofensemana2ESPN.xlsx')

# Semana 3

In [4]:
# Especifica la ubicación del controlador de Chrome (chromedriver.exe)
chromedriver_path = 'chromedriver.exe'

# Configura el servicio de Chrome con el argumento executable_path
chrome_service = ChromeService(executable_path=chromedriver_path)

# Crea una instancia del navegador Chrome con el servicio configurado
driver = webdriver.Chrome(service=chrome_service)

# Abre la página web
url = 'https://web.archive.org/web/20230928172328/https://www.espn.com/nfl/stats/team'
driver.get(url)

# Espera a que la tabla esté presente en la página
wait = WebDriverWait(driver, 10)
tabla_presente = EC.presence_of_element_located((By.CSS_SELECTOR, '.Table.Table--align-right.Table--fixed.Table--fixed-left'))
tabla = wait.until(tabla_presente)

# Obtén el contenido HTML de la ta bla
tabla_html = tabla.get_attribute('outerHTML')

# Utiliza BeautifulSoup para analizar el contenido HTML
soup = BeautifulSoup(tabla_html, 'html.parser')

# Encuentra todas las filas de la tabla
filas = soup.find_all('tr')

# Inicializa una lista para almacenar los datos
datos = []

# Recorre las filas y obtén los datos de cada celda
for fila in filas:
    celdas = fila.find_all('td')
    if celdas:  # Verifica si hay al menos una celda de datos en la fila
        fila_datos = [celda.text.strip() for celda in celdas]
        datos.append(fila_datos)

# Crea un DataFrame de Pandas con los datos filtrados
columnas = ['Equipo']  # Reemplaza con el nombre de tu columna
dfoffsem3 = pd.DataFrame(datos, columns=columnas)


# Cierra el navegador
driver.quit()

In [5]:
dfoffsem3

                   Equipo
0          Miami Dolphins
1    Los Angeles Chargers
2       Minnesota Vikings
3     San Francisco 49ers
4      Kansas City Chiefs
5     Philadelphia Eagles
6           Buffalo Bills
7           Detroit Lions
8        Los Angeles Rams
9        Cleveland Browns
10         Dallas Cowboys
11       Baltimore Ravens
12   New England Patriots
13         Houston Texans
14         Denver Broncos
15   Jacksonville Jaguars
16       Seattle Seahawks
17      Arizona Cardinals
18     Indianapolis Colts
19     New Orleans Saints
20      Carolina Panthers
21      Green Bay Packers
22  Washington Commanders
23      Las Vegas Raiders
24   Tampa Bay Buccaneers
25        Atlanta Falcons
26    Pittsburgh Steelers
27        New York Giants
28          Chicago Bears
29     Cincinnati Bengals
30       Tennessee Titans
31          New York Jets

In [6]:
urloffsem3 = "https://web.archive.org/web/20230928172328/https://www.espn.com/nfl/stats/team"

In [7]:
roffsem3 = requests.get(urloffsem3, cookies=cookies, headers=headers)
html_contentsoffsem3 = roffsem3.text

In [8]:
html_soupoffsem3 = BeautifulSoup(html_contentsoffsem3, 'html.parser')

In [9]:
tabla_puntajeoffsem3 = html_soupoffsem3.find_all('table', class_='Table Table--align-right')

In [10]:
columnasoffsem3 =  ['GP','YDS','YDS/G','YDS','YDS/G',
             'YDS','YDS/G','PTS','PTS/G',]

In [11]:
infoffsem3 = pd.DataFrame(columns = columnasoffsem3)

In [12]:
for table in tabla_puntajeoffsem3:
    for row in table.find_all('tr')[2:]:
        values = []
        for col in row.find_all(['th','td']):
            values.append(col.text)
        if len(values) == len(columnasoffsem3):
            infoffsem3.loc[len(infoffsem3)] = values

In [13]:
infoffsem3

   GP    YDS  YDS/G    YDS  YDS/G  YDS  YDS/G  PTS PTS/G
0   3  1,651  550.3  1,086  362.0  565  188.3  130  43.3
1   3  1,250  416.7    926  308.7  324  108.0   86  28.7
2   3  1,218  406.0  1,019  339.7  199   66.3   69  23.0
3   3  1,197  399.0    709  236.3  488  162.7   90  30.0
4   3  1,171  390.3    827  275.7  344  114.7   78  26.0
5   3  1,153  384.3    596  198.7  557  185.7   84  28.0
6   3  1,150  383.3    702  234.0  448  149.3   91  30.3
7   3  1,144  381.3    809  269.7  335  111.7   72  24.0
8   3  1,104  368.0    852  284.0  252   84.0   69  23.0
9   3  1,099  366.3    617  205.7  482  160.7   73  24.3
10  3  1,063  354.3    622  207.3  441  147.0   86  28.7
11  3  1,044  348.0    570  190.0  474  158.0   71  23.7
12  3  1,028  342.7    707  235.7  321  107.0   52  17.3
13  3  1,023  341.0    813  271.0  210   70.0   66  22.0
14  3  1,022  340.7    737  245.7  285   95.0   69  23.0
15  3  1,017  339.0    722  240.7  295   98.3   57  19.0
16  3    998  332.7    685  228.3  313  104.3   87  29.0
17  3    989  329.7    520  173.3  469  156.3   72  24.0
18  3    960  320.0    630  210.0  330  110.0   74  24.7
19  3    944  314.7    664  221.3  280   93.3   53  17.7
20  3    898  299.3    600  200.0  298   99.3   54  18.0
21  3    893  297.7    622  207.3  271   90.3   80  26.7
22  3    866  288.7    547  182.3  319  106.3   58  19.3
23  3    863  287.7    678  226.0  185   61.7   45  15.0
24  3    853  284.3    619  206.3  234   78.0   58  19.3
25  3    850  283.3    465  155.0  385  128.3   55  18.3
26  3    827  275.7    626  208.7  201   67.0   56  18.7
27  3    760  253.3    496  165.3  264   88.0   43  14.3
28  3    750  250.0    445  148.3  305  101.7   47  15.7
29  3    733  244.3    525  175.0  208   69.3   46  15.3
30  3    720  240.0    449  149.7  271   90.3   45  15.0
31  3    675  225.0    401  133.7  274   91.3   42  14.0

In [14]:
columnsUnidsem3 = pd.concat([dfoffsem3,infoffsem3], axis=1)

In [15]:
columnsUnidsem3

,Equipo,GP,YDS,YDS/G,YDS,YDS/G,YDS,YDS/G,PTS,PTS/G
0,Miami Dolphins,3,"1,651",550.3,"1,086",362.0,565,188.3,130,43.3
1,Los Angeles Chargers,3,"1,250",416.7,926,308.7,324,108.0,86,28.7
2,Minnesota Vikings,3,"1,218",406.0,"1,019",339.7,199,66.3,69,23.0
3,San Francisco 49ers,3,"1,197",399.0,709,236.3,488,162.7,90,30.0
4,Kansas City Chiefs,3,"1,171",390.3,827,275.7,344,114.7,78,26.0
5,Philadelphia Eagles,3,"1,153",384.3,596,198.7,557,185.7,84,28.0
6,Buffalo Bills,3,"1,150",383.3,702,234.0,448,149.3,91,30.3
7,Detroit Lions,3,"1,144",381.3,809,269.7,335,111.7,72,24.0
8,Los Angeles Rams,3,"1,104",368.0,852,284.0,252,84.0,69,23.0
9,Cleveland Browns,3,"1,099",366.3,617,205.7,482,160.7,73,24.3
10,Dallas Cowboys,3,"1,063",354.3,622,207.3,441,147.0,86,28.7
11,Baltimore Ravens,3,"1,044",348.0,570,190.0,474,158.0,71,23.7
12,New England Patriots,3,"1,028",342.7,707,235.7,321,107.0,52,17.3
13,Houston Texans,3,"1,023",341.0,813,271.0,210,70.0,66,22.0
14,Denver Broncos,3,"1,022",340.7,737,245.7,285,95.0,69,23.0
15,Jacksonville Jaguars,3,"1,017",339.0,722,240.7,295,98.3,57,19.0
16,Seattle Seahawks,3,998,332.7,685,228.3,313,104.3,87,29.0
17,Arizona Cardinals,3,989,329.7,520,173.3,469,156.3,72,24.0
18,Indianapolis Colts,3,960,320.0,630,210.0,330,110.0,74,24.7
19,New Orleans Saints,3,944,314.7,664,221.3,280,93.3,53,17.7
20,Carolina Panthers,3,898,299.3,600,200.0,298,99.3,54,18.0
21,Green Bay Packers,3,893,297.7,622,207.3,271,90.3,80,26.7
22,Washington Commanders,3,866,288.7,547,182.3,319,106.3,58,19.3
23,Las Vegas Raiders,3,863,287.7,678,226.0,185,61.7,45,15.0
24,Tampa Bay Buccaneers,3,853,284.3,619,206.3,234,78.0,58,19.3
25,Atlanta Falcons,3,850,283.3,465,155.0,385,128.3,55,18.3
26,Pittsburgh Steelers,3,827,275.7,626,208.7,201,67.0,56,18.7
27,New York Giants,3,760,253.3,496,165.3,264,88.0,43,14.3
28,Chicago Bears,3,750,250.0,445,148.3,305,101.7,47,15.7
29,Cincinnati Bengals,3,733,244.3,525,175.0,208,69.3,46,15.3
30,Tennessee Titans,3,720,240.0,449,149.7,271,90.3,45,15.0
31,New York Jets,3,675,225.0,401,133.7,274,91.3,42,14.0

In [17]:
columnsUnidsem3.to_excel('Export\\Ofensemana3ESPN.xlsx')

# Semana 4

In [117]:
# Especifica la ubicación del controlador de Chrome (chromedriver.exe)
chromedriver_path = 'chromedriver.exe'

# Configura el servicio de Chrome con el argumento executable_path
chrome_service = ChromeService(executable_path=chromedriver_path)

# Crea una instancia del navegador Chrome con el servicio configurado
driver = webdriver.Chrome(service=chrome_service)

# Abre la página web
url = 'https://www.espn.com.co/futbol-americano/nfl/estadisticas/equipo'
driver.get(url)

# Espera a que la tabla esté presente en la página
wait = WebDriverWait(driver, 10)
tabla_presente = EC.presence_of_element_located((By.CSS_SELECTOR, '.Table.Table--align-right.Table--fixed.Table--fixed-left'))
tabla = wait.until(tabla_presente)

# Obtén el contenido HTML de la tabla
tabla_html = tabla.get_attribute('outerHTML')

# Utiliza BeautifulSoup para analizar el contenido HTML
soup = BeautifulSoup(tabla_html, 'html.parser')

# Encuentra todas las filas de la tabla
filas = soup.find_all('tr')

# Inicializa una lista para almacenar los datos
datos = []

# Recorre las filas y obtén los datos de cada celda
for fila in filas:
    celdas = fila.find_all('td')
    if celdas:  # Verifica si hay al menos una celda de datos en la fila
        fila_datos = [celda.text.strip() for celda in celdas]
        datos.append(fila_datos)

# Crea un DataFrame de Pandas con los datos filtrados
columnas = ['Equipo']  # Reemplaza con el nombre de tu columna
dfoffsem4 = pd.DataFrame(datos, columns=columnas)


# Cierra el navegador
driver.quit()

In [118]:
dfoffsem4

                   Equipo
0          Miami Dolphins
1     San Francisco 49ers
2      Kansas City Chiefs
3        Los Angeles Rams
4     Philadelphia Eagles
5           Buffalo Bills
6    Los Angeles Chargers
7           Detroit Lions
8       Minnesota Vikings
9          Houston Texans
10         Dallas Cowboys
11      Arizona Cardinals
12       Baltimore Ravens
13          Chicago Bears
14         Denver Broncos
15   Jacksonville Jaguars
16  Washington Commanders
17     Indianapolis Colts
18   New England Patriots
19       Seattle Seahawks
20       Cleveland Browns
21   Tampa Bay Buccaneers
22     New Orleans Saints
23        Atlanta Falcons
24      Carolina Panthers
25      Las Vegas Raiders
26      Green Bay Packers
27       Tennessee Titans
28    Pittsburgh Steelers
29          New York Jets
30        New York Giants
31     Cincinnati Bengals

In [119]:
urloffsem4 = "https://www.espn.com.mx/futbol-americano/nfl/estadisticas/equipo"

In [120]:
roffsem4 = requests.get(urloffsem4, cookies=cookies, headers=headers)
html_contentsoffsem4 = roffsem4.text

In [121]:
html_soupoffsem4 = BeautifulSoup(html_contentsoffsem4, 'html.parser')

In [122]:
tabla_puntajeoffsem4 = html_soupoffsem4.find_all('table', class_='Table Table--align-right')

In [123]:
columnasoffsem4 =  ['GP','YDS','YDS/G','YDS','YDS/G',
             'YDS','YDS/G','PTS','PTS/G',]

In [124]:
infoffsem4 = pd.DataFrame(columns = columnasoffsem4)

In [125]:
for table in tabla_puntajeoffsem4:
    for row in table.find_all('tr')[2:]:
        values = []
        for col in row.find_all(['th','td']):
            values.append(col.text)
        if len(values) == len(columnasoffsem4):
            infoffsem4.loc[len(infoffsem4)] = values

In [126]:
infoffsem4

   GP    YDS  YDS/G    YDS  YDS/G  YDS  YDS/G  PTS PTS/G
0   4  2,044  511.0  1,337  334.3  707  176.8  150  37.5
1   4  1,592  398.0    980  245.0  612  153.0  125  31.3
2   4  1,572  393.0  1,024  256.0  548  137.0  101  25.3
3   4  1,571  392.8  1,155  288.8  416  104.0   98  24.5
4   4  1,568  392.0    907  226.8  661  165.3  118  29.5
5   4  1,564  391.0  1,012  253.0  552  138.0  139  34.8
6   4  1,555  388.8  1,076  269.0  479  119.8  110  27.5
7   4  1,545  386.3    999  249.8  546  136.5  106  26.5
8   4  1,483  370.8  1,149  287.3  334   83.5   90  22.5
9   4  1,474  368.5  1,125  281.3  349   87.3   96  24.0
10  4  1,440  360.0    875  218.8  565  141.3  124  31.0
11  4  1,351  337.8    777  194.3  574  143.5   88  22.0
12  4  1,340  335.0    735  183.8  605  151.3   99  24.8
13  5  1,672  334.4  1,018  203.6  654  130.8  115  23.0
14  4  1,333  333.3    951  237.8  382   95.5  100  25.0
15  4  1,317  329.3    917  229.3  400  100.0   80  20.0
16  5  1,619  323.8  1,164  232.8  455   91.0  109  21.8
17  4  1,289  322.3    826  206.5  463  115.8   97  24.3
18  4  1,281  320.3    907  226.8  374   93.5   55  13.8
19  4  1,279  319.8    845  211.3  434  108.5  111  27.8
20  4  1,265  316.3    690  172.5  575  143.8   76  19.0
21  4  1,206  301.5    858  214.5  348   87.0   84  21.0
22  4  1,141  285.3    791  197.8  350   87.5   62  15.5
23  4  1,137  284.3    625  156.3  512  128.0   62  15.5
24  4  1,130  282.5    749  187.3  381   95.3   67  16.8
25  4  1,127  281.8    866  216.5  261   65.3   62  15.5
26  4  1,123  280.8    825  206.3  298   74.5  100  25.0
27  4  1,120  280.0    676  169.0  444  111.0   72  18.0
28  4  1,052  263.0    737  184.3  315   78.8   62  15.5
29  4  1,011  252.8    629  157.3  382   95.5   62  15.5
30  4  1,008  252.0    632  158.0  376   94.0   46  11.5
31  4    944  236.0    664  166.0  280   70.0   49  12.3

In [127]:
columnsUnid = pd.concat([dfoffsem4,infoffsem4], axis=1)

In [128]:
columnsUnid

,Equipo,GP,YDS,YDS/G,YDS,YDS/G,YDS,YDS/G,PTS,PTS/G
0,Miami Dolphins,4,"2,044",511.0,"1,337",334.3,707,176.8,150,37.5
1,San Francisco 49ers,4,"1,592",398.0,980,245.0,612,153.0,125,31.3
2,Kansas City Chiefs,4,"1,572",393.0,"1,024",256.0,548,137.0,101,25.3
3,Los Angeles Rams,4,"1,571",392.8,"1,155",288.8,416,104.0,98,24.5
4,Philadelphia Eagles,4,"1,568",392.0,907,226.8,661,165.3,118,29.5
5,Buffalo Bills,4,"1,564",391.0,"1,012",253.0,552,138.0,139,34.8
6,Los Angeles Chargers,4,"1,555",388.8,"1,076",269.0,479,119.8,110,27.5
7,Detroit Lions,4,"1,545",386.3,999,249.8,546,136.5,106,26.5
8,Minnesota Vikings,4,"1,483",370.8,"1,149",287.3,334,83.5,90,22.5
9,Houston Texans,4,"1,474",368.5,"1,125",281.3,349,87.3,96,24.0
10,Dallas Cowboys,4,"1,440",360.0,875,218.8,565,141.3,124,31.0
11,Arizona Cardinals,4,"1,351",337.8,777,194.3,574,143.5,88,22.0
12,Baltimore Ravens,4,"1,340",335.0,735,183.8,605,151.3,99,24.8
13,Chicago Bears,5,"1,672",334.4,"1,018",203.6,654,130.8,115,23.0
14,Denver Broncos,4,"1,333",333.3,951,237.8,382,95.5,100,25.0
15,Jacksonville Jaguars,4,"1,317",329.3,917,229.3,400,100.0,80,20.0
16,Washington Commanders,5,"1,619",323.8,"1,164",232.8,455,91.0,109,21.8
17,Indianapolis Colts,4,"1,289",322.3,826,206.5,463,115.8,97,24.3
18,New England Patriots,4,"1,281",320.3,907,226.8,374,93.5,55,13.8
19,Seattle Seahawks,4,"1,279",319.8,845,211.3,434,108.5,111,27.8
20,Cleveland Browns,4,"1,265",316.3,690,172.5,575,143.8,76,19.0
21,Tampa Bay Buccaneers,4,"1,206",301.5,858,214.5,348,87.0,84,21.0
22,New Orleans Saints,4,"1,141",285.3,791,197.8,350,87.5,62,15.5
23,Atlanta Falcons,4,"1,137",284.3,625,156.3,512,128.0,62,15.5
24,Carolina Panthers,4,"1,130",282.5,749,187.3,381,95.3,67,16.8
25,Las Vegas Raiders,4,"1,127",281.8,866,216.5,261,65.3,62,15.5
26,Green Bay Packers,4,"1,123",280.8,825,206.3,298,74.5,100,25.0
27,Tennessee Titans,4,"1,120",280.0,676,169.0,444,111.0,72,18.0
28,Pittsburgh Steelers,4,"1,052",263.0,737,184.3,315,78.8,62,15.5
29,New York Jets,4,"1,011",252.8,629,157.3,382,95.5,62,15.5
30,New York Giants,4,"1,008",252.0,632,158.0,376,94.0,46,11.5
31,Cincinnati Bengals,4,944,236.0,664,166.0,280,70.0,49,12.3

In [129]:
columnsUnid.to_excel('Export\\Ofensemana4ESPN.xlsx')