In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import psycopg2

In [2]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36'
}

cookies = {
    'cookie_name': 'cookie_value'
}

In [3]:
urlDal = "https://www.espn.com.mx/futbol-americano/nfl/equipo/calendario/_/nombre/dal"

In [4]:
urlGb = "https://www.espn.com.mx/futbol-americano/nfl/equipo/calendario/_/nombre/gb"

In [5]:
urlMia = "https://www.espn.com.mx/futbol-americano/nfl/equipo/calendario/_/nombre/mia"

In [6]:
urlJax = "https://www.espn.com.mx/futbol-americano/nfl/equipo/calendario/_/nombre/jax"

In [7]:
urlLar = "https://www.espn.com.mx/futbol-americano/nfl/equipo/calendario/_/nombre/lar"

In [8]:
urlSf = "https://www.espn.com.mx/futbol-americano/nfl/equipo/calendario/_/nombre/sf"

In [9]:
urlBal = "https://www.espn.com.mx/futbol-americano/nfl/equipo/calendario/_/nombre/bal"

In [10]:
urlPhi = "https://www.espn.com.mx/futbol-americano/nfl/equipo/calendario/_/nombre/phi"

In [11]:
urlAtl = "https://www.espn.com.mx/futbol-americano/nfl/equipo/calendario/_/nombre/atl"

In [12]:
urlCle = "https://www.espn.com.mx/futbol-americano/nfl/equipo/calendario/_/nombre/cle"

In [13]:
urlNyj = "https://www.espn.com.mx/futbol-americano/nfl/equipo/calendario/_/nombre/nyj"

In [14]:
urlDet = "https://www.espn.com.mx/futbol-americano/nfl/equipo/calendario/_/nombre/det"

In [15]:
urlTb = "https://www.espn.com.mx/futbol-americano/nfl/equipo/calendario/_/nombre/tb"

In [16]:
urlWsh = "https://www.espn.com.mx/futbol-americano/nfl/equipo/calendario/_/nombre/wsh"

In [17]:
urlLv = "https://www.espn.com.mx/futbol-americano/nfl/equipo/calendario/_/nombre/lv"

In [18]:
urlNo = "https://www.espn.com.mx/futbol-americano/nfl/equipo/calendario/_/nombre/no"

In [19]:
urlLac = "https://www.espn.com.mx/futbol-americano/nfl/equipo/calendario/_/nombre/lac"

In [20]:
urlInd = "https://www.espn.com.mx/futbol-americano/nfl/equipo/calendario/_/nombre/ind"

In [21]:
urlChi = "https://www.espn.com.mx/futbol-americano/nfl/equipo/calendario/_/nombre/chi"

In [22]:
urlKc = "https://www.espn.com.mx/futbol-americano/nfl/equipo/calendario/_/nombre/kc"

In [23]:
urlNe = "https://www.espn.com.mx/futbol-americano/nfl/equipo/calendario/_/nombre/ne"

In [24]:
urlMin = "https://www.espn.com.mx/futbol-americano/nfl/equipo/calendario/_/nombre/min"

In [25]:
urlAri = "https://www.espn.com.mx/futbol-americano/nfl/equipo/calendario/_/nombre/ari"

In [26]:
urlBuf = "https://www.espn.com.mx/futbol-americano/nfl/equipo/calendario/_/nombre/buf"

In [27]:
urlDen = "https://www.espn.com.mx/futbol-americano/nfl/equipo/calendario/_/nombre/den"

In [28]:
urlTen = "https://www.espn.com.mx/futbol-americano/nfl/equipo/calendario/_/nombre/ten"

In [29]:
urlSea = "https://www.espn.com.mx/futbol-americano/nfl/equipo/calendario/_/nombre/sea"

In [30]:
urlCar = "https://www.espn.com.mx/futbol-americano/nfl/equipo/calendario/_/nombre/car"

In [31]:
urlHou = "https://www.espn.com.mx/futbol-americano/nfl/equipo/calendario/_/nombre/hou"

In [32]:
urlPit = "https://www.espn.com.mx/futbol-americano/nfl/equipo/calendario/_/nombre/pit"

In [33]:
urlCin = "https://www.espn.com.mx/futbol-americano/nfl/equipo/calendario/_/nombre/cin"

In [34]:
urlNyg = "https://www.espn.com.mx/futbol-americano/nfl/equipo/calendario/_/nombre/nyg"

In [35]:
TabGen = ['Semana','Fecha', 'Oponente','Resultado','G-P','L.Pases','L. Corr','L. Recib']

In [36]:
rDal = requests.get(urlDal, cookies=cookies, headers=headers)
html_contentsDal = rDal.text

In [37]:
html_soupDal = BeautifulSoup(html_contentsDal, 'html.parser')

In [38]:
calendarioDal = html_soupDal.find_all('table', class_='Table')

In [39]:
Dallas = pd.DataFrame(columns = TabGen)

In [40]:
for table in calendarioDal:
    for row in table.find_all('tr')[2:21]:
        values = []
        for col in row.find_all(['th','td']):
            values.append(col.text)
        if len(values) == len(TabGen):
            Dallas.loc[len(Dallas)] = values

In [41]:
Dallas.insert(0, 'Equipo', 'Dallas')
Dallas['Resultado_L'] = Dallas['Resultado'].str.extract(r'([A-Za-z]+)')
Dallas['Resultado_Numeros'] = Dallas['Resultado'].str.extract(r'(\d+-\d+)')
Dallas[['R1', 'R2']] = Dallas['Resultado_Numeros'].str.split('-', expand=True)
Dallas['Local/Visitante'] = Dallas['Oponente'].str.split().str[0].str.replace('.', '')
Dallas['Local/Visitante'] = Dallas['Local/Visitante'].str.replace('vs', 'local').str.replace('en', 'visitante')
Dallas['Equipo_Oponente'] = Dallas['Oponente'].str.extract(r'(vs\.|en\s)([^,]+)')[1]
# Agregar las columnas "G," "P," y "E" basadas en la columna "Resultado_L"
Dallas['G'] = (Dallas['Resultado_L'] == 'G').astype(int)
Dallas['P'] = (Dallas['Resultado_L'] == 'P').astype(int)
Dallas['E'] = (Dallas['Resultado_L'] == 'E').astype(int)
columnas_deseadas = ['Equipo', 'Semana', 'Fecha', 'Resultado_L', 'R1', 'R2', 'Local/Visitante', 'Equipo_Oponente', 'G', 'P', 'E']
Dallas_select = Dallas[columnas_deseadas]
Dallas_select.loc[:, ['Semana', 'R1', 'R2', 'G', 'P', 'E']] = Dallas_select[['Semana', 'R1', 'R2', 'G', 'P', 'E']].astype(int)
Dallas_select = Dallas_select.copy()
Dallas_select['Diferencia_Pts.'] = Dallas_select['R1'] - Dallas_select['R2']

In [42]:
Dallas_select

,Equipo,Semana,Fecha,Resultado_L,R1,R2,Local/Visitante,Equipo_Oponente,G,P,E,Diferencia_Pts.
0,Dallas,1,"Dom., 10 de Sep.",G,40,0,visitante,New York,1,0,0,40
1,Dallas,2,"Dom., 17 de Sep.",G,30,10,local,New York,1,0,0,20
2,Dallas,3,"Dom., 24 de Sep.",P,28,16,visitante,Arizona,0,1,0,12
3,Dallas,4,"Dom., 1 de Oct.",G,38,3,local,New England,1,0,0,35
4,Dallas,5,"Dom., 8 de Oct.",P,42,10,visitante,San Francisco,0,1,0,32
5,Dallas,6,"Lun., 16 de Oct.",G,20,17,visitante,Los Angeles,1,0,0,3
6,Dallas,8,"Dom., 29 de Oct.",G,43,20,local,Los Angeles,1,0,0,23

In [43]:
rGb = requests.get(urlGb, cookies=cookies, headers=headers)
html_contentsGb = rGb.text

In [44]:
html_soupGb = BeautifulSoup(html_contentsGb, 'html.parser')

In [45]:
calendarioGb = html_soupGb.find_all('table', class_='Table')

In [46]:
Green_Bay = pd.DataFrame(columns = TabGen)

In [47]:
for table in calendarioGb:
    for row in table.find_all('tr')[2:21]:
        values = []
        for col in row.find_all(['th','td']):
            values.append(col.text)
        if len(values) == len(TabGen):
            Green_Bay.loc[len(Green_Bay)] = values

In [48]:
Green_Bay.insert(0, 'Equipo', 'Green Bay')
Green_Bay['Resultado_L'] = Green_Bay['Resultado'].str.extract(r'([A-Za-z]+)')
Green_Bay['Resultado_Numeros'] = Green_Bay['Resultado'].str.extract(r'(\d+-\d+)')
Green_Bay[['R1', 'R2']] = Green_Bay['Resultado_Numeros'].str.split('-', expand=True)
Green_Bay['Local/Visitante'] = Green_Bay['Oponente'].str.split().str[0].str.replace('.', '')
Green_Bay['Local/Visitante'] = Green_Bay['Local/Visitante'].str.replace('vs', 'local').str.replace('en', 'visitante')
Green_Bay['Equipo_Oponente'] = Green_Bay['Oponente'].str.extract(r'(vs\.|en\s)([^,]+)')[1]
# Agregar las columnas "G," "P," y "E" basadas en la columna "Resultado_L"
Green_Bay['G'] = (Green_Bay['Resultado_L'] == 'G').astype(int)
Green_Bay['P'] = (Green_Bay['Resultado_L'] == 'P').astype(int)
Green_Bay['E'] = (Green_Bay['Resultado_L'] == 'E').astype(int)
columnas_deseadas = ['Equipo', 'Semana', 'Fecha', 'Resultado_L', 'R1', 'R2', 'Local/Visitante', 'Equipo_Oponente', 'G', 'P', 'E']
Green_Bay_select = Green_Bay[columnas_deseadas]
Green_Bay_select.loc[:, ['Semana', 'R1', 'R2', 'G', 'P', 'E']] = Green_Bay_select[['Semana', 'R1', 'R2', 'G', 'P', 'E']].astype(int)
Green_Bay_select = Green_Bay_select.copy()
Green_Bay_select['Diferencia_Pts.'] = Green_Bay_select['R1'] - Green_Bay_select['R2']

In [49]:
Green_Bay_select

,Equipo,Semana,Fecha,Resultado_L,R1,R2,Local/Visitante,Equipo_Oponente,G,P,E,Diferencia_Pts.
0,Green Bay,1,"Dom., 10 de Sep.",G,38,20,visitante,Chicago,1,0,0,18
1,Green Bay,2,"Dom., 17 de Sep.",P,25,24,visitante,Atlanta,0,1,0,1
2,Green Bay,3,"Dom., 24 de Sep.",G,18,17,local,New Orleans,1,0,0,1
3,Green Bay,4,"Jue., 28 de Sep.",P,34,20,local,Detroit,0,1,0,14
4,Green Bay,5,"Lun., 9 de Oct.",P,17,13,visitante,Las Vegas,0,1,0,4
5,Green Bay,7,"Dom., 22 de Oct.",P,19,17,visitante,Denver,0,1,0,2
6,Green Bay,8,"Dom., 29 de Oct.",P,24,10,local,Minnesota,0,1,0,14

In [50]:
rMia = requests.get(urlMia, cookies=cookies, headers=headers)
html_contentsMia = rMia.text

In [51]:
html_soupMia = BeautifulSoup(html_contentsMia, 'html.parser')

In [52]:
calendarioMia = html_soupMia.find_all('table', class_='Table')

In [53]:
Miami = pd.DataFrame(columns = TabGen)

In [54]:
for table in calendarioMia:
    for row in table.find_all('tr')[2:21]:
        values = []
        for col in row.find_all(['th','td']):
            values.append(col.text)
        if len(values) == len(TabGen):
            Miami.loc[len(Miami)] = values

In [55]:
Miami.insert(0, 'Equipo', 'Miami')
Miami['Resultado_L'] = Miami['Resultado'].str.extract(r'([A-Za-z]+)')
Miami['Resultado_Numeros'] = Miami['Resultado'].str.extract(r'(\d+-\d+)')
Miami[['R1', 'R2']] = Miami['Resultado_Numeros'].str.split('-', expand=True)
Miami['Local/Visitante'] = Miami['Oponente'].str.split().str[0].str.replace('.', '')
Miami['Local/Visitante'] = Miami['Local/Visitante'].str.replace('vs', 'local').str.replace('en', 'visitante')
Miami['Equipo_Oponente'] = Miami['Oponente'].str.extract(r'(vs\.|en\s)([^,]+)')[1]
# Agregar las columnas "G," "P," y "E" basadas en la columna "Resultado_L"
Miami['G'] = (Miami['Resultado_L'] == 'G').astype(int)
Miami['P'] = (Miami['Resultado_L'] == 'P').astype(int)
Miami['E'] = (Miami['Resultado_L'] == 'E').astype(int)
columnas_deseadas = ['Equipo', 'Semana', 'Fecha', 'Resultado_L', 'R1', 'R2', 'Local/Visitante', 'Equipo_Oponente', 'G', 'P', 'E']
Miami_select = Miami[columnas_deseadas]
Miami_select.loc[:, ['Semana', 'R1', 'R2', 'G', 'P', 'E']] = Miami_select[['Semana', 'R1', 'R2', 'G', 'P', 'E']].astype(int)
Miami_select = Miami_select.copy()
Miami_select['Diferencia_Pts.'] = Miami_select['R1'] - Miami_select['R2']

In [56]:
Miami_select

,Equipo,Semana,Fecha,Resultado_L,R1,R2,Local/Visitante,Equipo_Oponente,G,P,E,Diferencia_Pts.
0,Miami,1,"Dom., 10 de Sep.",G,36,34,visitante,Los Angeles,1,0,0,2
1,Miami,2,"Dom., 17 de Sep.",G,24,17,visitante,New England,1,0,0,7
2,Miami,3,"Dom., 24 de Sep.",G,70,20,local,Denver,1,0,0,50
3,Miami,4,"Dom., 1 de Oct.",P,48,20,visitante,Buffalo,0,1,0,28
4,Miami,5,"Dom., 8 de Oct.",G,31,16,local,New York,1,0,0,15
5,Miami,6,"Dom., 15 de Oct.",G,42,21,local,Carolina,1,0,0,21
6,Miami,7,"Dom., 22 de Oct.",P,31,17,visitante,Philadelphia,0,1,0,14
7,Miami,8,"Dom., 29 de Oct.",G,31,17,local,New England,1,0,0,14

In [57]:
rJax = requests.get(urlJax, cookies=cookies, headers=headers)
html_contentsJax = rJax.text

In [58]:
html_soupJax = BeautifulSoup(html_contentsJax, 'html.parser')

In [59]:
calendarioJax = html_soupJax.find_all('table', class_='Table')

In [60]:
Jacksonville = pd.DataFrame(columns = TabGen)

In [61]:
for table in calendarioJax:
    for row in table.find_all('tr')[2:21]:
        values = []
        for col in row.find_all(['th','td']):
            values.append(col.text)
        if len(values) == len(TabGen):
            Jacksonville.loc[len(Jacksonville)] = values

In [62]:
Jacksonville.insert(0, 'Equipo', 'Jacksonville')
Jacksonville['Resultado_L'] = Jacksonville['Resultado'].str.extract(r'([A-Za-z]+)')
Jacksonville['Resultado_Numeros'] = Jacksonville['Resultado'].str.extract(r'(\d+-\d+)')
Jacksonville[['R1', 'R2']] = Jacksonville['Resultado_Numeros'].str.split('-', expand=True)
Jacksonville['Local/Visitante'] = Jacksonville['Oponente'].str.split().str[0].str.replace('.', '')
Jacksonville['Local/Visitante'] = Jacksonville['Local/Visitante'].str.replace('vs', 'local').str.replace('en', 'visitante')
Jacksonville['Equipo_Oponente'] = Jacksonville['Oponente'].str.extract(r'(vs\.|en\s)([^,]+)')[1]
# Agregar las columnas "G," "P," y "E" basadas en la columna "Resultado_L"
Jacksonville['G'] = (Jacksonville['Resultado_L'] == 'G').astype(int)
Jacksonville['P'] = (Jacksonville['Resultado_L'] == 'P').astype(int)
Jacksonville['E'] = (Jacksonville['Resultado_L'] == 'E').astype(int)
columnas_deseadas = ['Equipo', 'Semana', 'Fecha', 'Resultado_L', 'R1', 'R2', 'Local/Visitante', 'Equipo_Oponente', 'G', 'P', 'E']
Jacksonville_select = Jacksonville[columnas_deseadas]
Jacksonville_select.loc[:, ['Semana', 'R1', 'R2', 'G', 'P', 'E']] = Jacksonville_select[['Semana', 'R1', 'R2', 'G', 'P', 'E']].astype(int)
Jacksonville_select = Jacksonville_select.copy()
Jacksonville_select['Diferencia_Pts.'] = Jacksonville_select['R1'] - Jacksonville_select['R2']

In [63]:
Jacksonville_select

,Equipo,Semana,Fecha,Resultado_L,R1,R2,Local/Visitante,Equipo_Oponente,G,P,E,Diferencia_Pts.
0,Jacksonville,1,"Dom., 10 de Sep.",G,31,21,visitante,Indianapolis,1,0,0,10
1,Jacksonville,2,"Dom., 17 de Sep.",P,17,9,local,Kansas City,0,1,0,8
2,Jacksonville,3,"Dom., 24 de Sep.",P,37,17,local,Houston,0,1,0,20
3,Jacksonville,4,"Dom., 1 de Oct.",G,23,7,local,Atlanta *,1,0,0,16
4,Jacksonville,5,"Dom., 8 de Oct.",G,25,20,local,Buffalo *,1,0,0,5
5,Jacksonville,6,"Dom., 15 de Oct.",G,37,20,local,Indianapolis,1,0,0,17
6,Jacksonville,7,"Jue., 19 de Oct.",G,31,24,visitante,New Orleans,1,0,0,7
7,Jacksonville,8,"Dom., 29 de Oct.",G,20,10,visitante,Pittsburgh,1,0,0,10

In [64]:
rLar = requests.get(urlLar, cookies=cookies, headers=headers)
html_contentsLar = rLar.text

In [65]:
html_soupLar = BeautifulSoup(html_contentsLar, 'html.parser')

In [66]:
calendarioLar = html_soupLar.find_all('table', class_='Table')

In [67]:
Los_Angeles_Rams = pd.DataFrame(columns = TabGen)

In [68]:
for table in calendarioLar:
    for row in table.find_all('tr')[2:21]:
        values = []
        for col in row.find_all(['th','td']):
            values.append(col.text)
        if len(values) == len(TabGen):
            Los_Angeles_Rams.loc[len(Los_Angeles_Rams)] = values

In [69]:
Los_Angeles_Rams.insert(0, 'Equipo', 'Los Angeles Rams')
Los_Angeles_Rams['Resultado_L'] = Los_Angeles_Rams['Resultado'].str.extract(r'([A-Za-z]+)')
Los_Angeles_Rams['Resultado_Numeros'] = Los_Angeles_Rams['Resultado'].str.extract(r'(\d+-\d+)')
Los_Angeles_Rams[['R1', 'R2']] = Los_Angeles_Rams['Resultado_Numeros'].str.split('-', expand=True)
Los_Angeles_Rams['Local/Visitante'] = Los_Angeles_Rams['Oponente'].str.split().str[0].str.replace('.', '')
Los_Angeles_Rams['Local/Visitante'] = Los_Angeles_Rams['Local/Visitante'].str.replace('vs', 'local').str.replace('en', 'visitante')
Los_Angeles_Rams['Equipo_Oponente'] = Los_Angeles_Rams['Oponente'].str.extract(r'(vs\.|en\s)([^,]+)')[1]
# Agregar las columnas "G," "P," y "E" basadas en la columna "Resultado_L"
Los_Angeles_Rams['G'] = (Los_Angeles_Rams['Resultado_L'] == 'G').astype(int)
Los_Angeles_Rams['P'] = (Los_Angeles_Rams['Resultado_L'] == 'P').astype(int)
Los_Angeles_Rams['E'] = (Los_Angeles_Rams['Resultado_L'] == 'E').astype(int)
columnas_deseadas = ['Equipo', 'Semana', 'Fecha', 'Resultado_L', 'R1', 'R2', 'Local/Visitante', 'Equipo_Oponente', 'G', 'P', 'E']
Los_Angeles_Rams_select = Los_Angeles_Rams[columnas_deseadas]
Los_Angeles_Rams_select.loc[:, ['Semana', 'R1', 'R2', 'G', 'P', 'E']] = Los_Angeles_Rams_select[['Semana', 'R1', 'R2', 'G', 'P', 'E']].astype(int)
Los_Angeles_Rams_select = Los_Angeles_Rams_select.copy()
Los_Angeles_Rams_select['Diferencia_Pts.'] = Los_Angeles_Rams_select['R1'] - Los_Angeles_Rams_select['R2']

In [70]:
Los_Angeles_Rams_select

,Equipo,Semana,Fecha,Resultado_L,R1,R2,Local/Visitante,Equipo_Oponente,G,P,E,Diferencia_Pts.
0,Los Angeles Rams,1,"Dom., 10 de Sep.",G,30,13,visitante,Seattle,1,0,0,17
1,Los Angeles Rams,2,"Dom., 17 de Sep.",P,30,23,local,San Francisco,0,1,0,7
2,Los Angeles Rams,3,"Lun., 25 de Sep.",P,19,16,visitante,Cincinnati,0,1,0,3
3,Los Angeles Rams,4,"Dom., 1 de Oct.",G,29,23,visitante,Indianapolis,1,0,0,6
4,Los Angeles Rams,5,"Dom., 8 de Oct.",P,23,14,local,Philadelphia,0,1,0,9
5,Los Angeles Rams,6,"Dom., 15 de Oct.",G,26,9,local,Arizona,1,0,0,17
6,Los Angeles Rams,7,"Dom., 22 de Oct.",P,24,17,local,Pittsburgh,0,1,0,7
7,Los Angeles Rams,8,"Dom., 29 de Oct.",P,43,20,visitante,Dallas,0,1,0,23

In [71]:
rSf = requests.get(urlSf, cookies=cookies, headers=headers)
html_contentsSf = rSf.text

In [72]:
html_soupSf = BeautifulSoup(html_contentsSf, 'html.parser')

In [73]:
calendarioSf = html_soupSf.find_all('table', class_='Table')

In [74]:
San_Francisco = pd.DataFrame(columns = TabGen)

In [75]:
for table in calendarioSf:
    for row in table.find_all('tr')[2:21]:
        values = []
        for col in row.find_all(['th','td']):
            values.append(col.text)
        if len(values) == len(TabGen):
            San_Francisco.loc[len(San_Francisco)] = values

In [76]:
San_Francisco.insert(0, 'Equipo', 'San Francisco')
San_Francisco['Resultado_L'] = San_Francisco['Resultado'].str.extract(r'([A-Za-z]+)')
San_Francisco['Resultado_Numeros'] = San_Francisco['Resultado'].str.extract(r'(\d+-\d+)')
San_Francisco[['R1', 'R2']] = San_Francisco['Resultado_Numeros'].str.split('-', expand=True)
San_Francisco['Local/Visitante'] = San_Francisco['Oponente'].str.split().str[0].str.replace('.', '')
San_Francisco['Local/Visitante'] = San_Francisco['Local/Visitante'].str.replace('vs', 'local').str.replace('en', 'visitante')
San_Francisco['Equipo_Oponente'] = San_Francisco['Oponente'].str.extract(r'(vs\.|en\s)([^,]+)')[1]
# Agregar las columnas "G," "P," y "E" basadas en la columna "Resultado_L"
San_Francisco['G'] = (San_Francisco['Resultado_L'] == 'G').astype(int)
San_Francisco['P'] = (San_Francisco['Resultado_L'] == 'P').astype(int)
San_Francisco['E'] = (San_Francisco['Resultado_L'] == 'E').astype(int)
columnas_deseadas = ['Equipo', 'Semana', 'Fecha', 'Resultado_L', 'R1', 'R2', 'Local/Visitante', 'Equipo_Oponente', 'G', 'P', 'E']
San_Francisco_select = San_Francisco[columnas_deseadas]
San_Francisco_select.loc[:, ['Semana', 'R1', 'R2', 'G', 'P', 'E']] = San_Francisco_select[['Semana', 'R1', 'R2', 'G', 'P', 'E']].astype(int)
San_Francisco_select = San_Francisco_select.copy()
San_Francisco_select['Diferencia_Pts.'] = San_Francisco_select['R1'] - San_Francisco_select['R2']

In [77]:
San_Francisco_select

,Equipo,Semana,Fecha,Resultado_L,R1,R2,Local/Visitante,Equipo_Oponente,G,P,E,Diferencia_Pts.
0,San Francisco,1,"Dom., 10 de Sep.",G,30,7,visitante,Pittsburgh,1,0,0,23
1,San Francisco,2,"Dom., 17 de Sep.",G,30,23,visitante,Los Angeles,1,0,0,7
2,San Francisco,3,"Jue., 21 de Sep.",G,30,12,local,New York,1,0,0,18
3,San Francisco,4,"Dom., 1 de Oct.",G,35,16,local,Arizona,1,0,0,19
4,San Francisco,5,"Dom., 8 de Oct.",G,42,10,local,Dallas,1,0,0,32
5,San Francisco,6,"Dom., 15 de Oct.",P,19,17,visitante,Cleveland,0,1,0,2
6,San Francisco,7,"Lun., 23 de Oct.",P,22,17,visitante,Minnesota,0,1,0,5
7,San Francisco,8,"Dom., 29 de Oct.",P,31,17,local,Cincinnati,0,1,0,14

In [78]:
rBal = requests.get(urlBal, cookies=cookies, headers=headers)
html_contentsBal = rBal.text

In [79]:
html_soupBal = BeautifulSoup(html_contentsBal, 'html.parser')

In [80]:
calendarioBal = html_soupBal.find_all('table', class_='Table')

In [81]:
Baltimore_Ravens = pd.DataFrame(columns = TabGen)

In [82]:
for table in calendarioBal:
    for row in table.find_all('tr')[2:21]:
        values = []
        for col in row.find_all(['th','td']):
            values.append(col.text)
        if len(values) == len(TabGen):
            Baltimore_Ravens.loc[len(Baltimore_Ravens)] = values

In [83]:
Baltimore_Ravens.insert(0, 'Equipo', 'Baltimore Ravens')
Baltimore_Ravens['Resultado_L'] = Baltimore_Ravens['Resultado'].str.extract(r'([A-Za-z]+)')
Baltimore_Ravens['Resultado_Numeros'] = Baltimore_Ravens['Resultado'].str.extract(r'(\d+-\d+)')
Baltimore_Ravens[['R1', 'R2']] = Baltimore_Ravens['Resultado_Numeros'].str.split('-', expand=True)
Baltimore_Ravens['Local/Visitante'] = Baltimore_Ravens['Oponente'].str.split().str[0].str.replace('.', '')
Baltimore_Ravens['Local/Visitante'] = Baltimore_Ravens['Local/Visitante'].str.replace('vs', 'local').str.replace('en', 'visitante')
Baltimore_Ravens['Equipo_Oponente'] = Baltimore_Ravens['Oponente'].str.extract(r'(vs\.|en\s)([^,]+)')[1]
# Agregar las columnas "G," "P," y "E" basadas en la columna "Resultado_L"
Baltimore_Ravens['G'] = (Baltimore_Ravens['Resultado_L'] == 'G').astype(int)
Baltimore_Ravens['P'] = (Baltimore_Ravens['Resultado_L'] == 'P').astype(int)
Baltimore_Ravens['E'] = (Baltimore_Ravens['Resultado_L'] == 'E').astype(int)
columnas_deseadas = ['Equipo', 'Semana', 'Fecha', 'Resultado_L', 'R1', 'R2', 'Local/Visitante', 'Equipo_Oponente', 'G', 'P', 'E']
Baltimore_Ravens_select = Baltimore_Ravens[columnas_deseadas]
Baltimore_Ravens_select.loc[:, ['Semana', 'R1', 'R2', 'G', 'P', 'E']] = Baltimore_Ravens_select[['Semana', 'R1', 'R2', 'G', 'P', 'E']].astype(int)
Baltimore_Ravens_select = Baltimore_Ravens_select.copy()
Baltimore_Ravens_select['Diferencia_Pts.'] = Baltimore_Ravens_select['R1'] - Baltimore_Ravens_select['R2']

In [84]:
Baltimore_Ravens_select

,Equipo,Semana,Fecha,Resultado_L,R1,R2,Local/Visitante,Equipo_Oponente,G,P,E,Diferencia_Pts.
0,Baltimore Ravens,1,"Dom., 10 de Sep.",G,25,9,local,Houston,1,0,0,16
1,Baltimore Ravens,2,"Dom., 17 de Sep.",G,27,24,visitante,Cincinnati,1,0,0,3
2,Baltimore Ravens,3,"Dom., 24 de Sep.",P,22,19,local,Indianapolis,0,1,0,3
3,Baltimore Ravens,4,"Dom., 1 de Oct.",G,28,3,visitante,Cleveland,1,0,0,25
4,Baltimore Ravens,5,"Dom., 8 de Oct.",P,17,10,visitante,Pittsburgh,0,1,0,7
5,Baltimore Ravens,6,"Dom., 15 de Oct.",G,24,16,local,Tennessee *,1,0,0,8
6,Baltimore Ravens,7,"Dom., 22 de Oct.",G,38,6,local,Detroit,1,0,0,32
7,Baltimore Ravens,8,"Dom., 29 de Oct.",G,31,24,visitante,Arizona,1,0,0,7

In [85]:
rPhi = requests.get(urlPhi, cookies=cookies, headers=headers)
html_contentsPhi = rPhi.text

In [86]:
html_soupPhi = BeautifulSoup(html_contentsPhi, 'html.parser')

In [87]:
calendarioPhi = html_soupPhi.find_all('table', class_='Table')

In [88]:
Philadelphia = pd.DataFrame(columns = TabGen)

In [89]:
for table in calendarioPhi:
    for row in table.find_all('tr')[2:21]:
        values = []
        for col in row.find_all(['th','td']):
            values.append(col.text)
        if len(values) == len(TabGen):
            Philadelphia.loc[len(Philadelphia)] = values

In [90]:
Philadelphia.insert(0, 'Equipo', 'Philadelphia')
Philadelphia['Resultado_L'] = Philadelphia['Resultado'].str.extract(r'([A-Za-z]+)')
Philadelphia['Resultado_Numeros'] = Philadelphia['Resultado'].str.extract(r'(\d+-\d+)')
Philadelphia[['R1', 'R2']] = Philadelphia['Resultado_Numeros'].str.split('-', expand=True)
Philadelphia['Local/Visitante'] = Philadelphia['Oponente'].str.split().str[0].str.replace('.', '')
Philadelphia['Local/Visitante'] = Philadelphia['Local/Visitante'].str.replace('vs', 'local').str.replace('en', 'visitante')
Philadelphia['Equipo_Oponente'] = Philadelphia['Oponente'].str.extract(r'(vs\.|en\s)([^,]+)')[1]
# Agregar las columnas "G," "P," y "E" basadas en la columna "Resultado_L"
Philadelphia['G'] = (Philadelphia['Resultado_L'] == 'G').astype(int)
Philadelphia['P'] = (Philadelphia['Resultado_L'] == 'P').astype(int)
Philadelphia['E'] = (Philadelphia['Resultado_L'] == 'E').astype(int)
columnas_deseadas = ['Equipo', 'Semana', 'Fecha', 'Resultado_L', 'R1', 'R2', 'Local/Visitante', 'Equipo_Oponente', 'G', 'P', 'E']
Philadelphia_select = Philadelphia[columnas_deseadas]
Philadelphia_select.loc[:, ['Semana', 'R1', 'R2', 'G', 'P', 'E']] = Philadelphia_select[['Semana', 'R1', 'R2', 'G', 'P', 'E']].astype(int)
Philadelphia_select = Philadelphia_select.copy()
Philadelphia_select['Diferencia_Pts.'] = Philadelphia_select['R1'] - Philadelphia_select['R2']

In [91]:
Philadelphia_select

,Equipo,Semana,Fecha,Resultado_L,R1,R2,Local/Visitante,Equipo_Oponente,G,P,E,Diferencia_Pts.
0,Philadelphia,1,"Dom., 10 de Sep.",G,25,20,visitante,New England,1,0,0,5
1,Philadelphia,2,"Jue., 14 de Sep.",G,34,28,local,Minnesota,1,0,0,6
2,Philadelphia,3,"Lun., 25 de Sep.",G,25,11,visitante,Tampa Bay,1,0,0,14
3,Philadelphia,4,"Dom., 1 de Oct.",G,34,31,local,Washington,1,0,0,3
4,Philadelphia,5,"Dom., 8 de Oct.",G,23,14,visitante,Los Angeles,1,0,0,9
5,Philadelphia,6,"Dom., 15 de Oct.",P,20,14,visitante,New York,0,1,0,6
6,Philadelphia,7,"Dom., 22 de Oct.",G,31,17,local,Miami,1,0,0,14
7,Philadelphia,8,"Dom., 29 de Oct.",G,38,31,visitante,Washington,1,0,0,7

In [92]:
rAtl = requests.get(urlAtl, cookies=cookies, headers=headers)
html_contentsAtl = rAtl.text

In [93]:
html_soupAtl = BeautifulSoup(html_contentsAtl, 'html.parser')

In [94]:
calendarioAtl = html_soupAtl.find_all('table', class_='Table')

In [95]:
Atlanta = pd.DataFrame(columns = TabGen)

In [96]:
for table in calendarioAtl:
    for row in table.find_all('tr')[2:21]:
        values = []
        for col in row.find_all(['th','td']):
            values.append(col.text)
        if len(values) == len(TabGen):
            Atlanta.loc[len(Atlanta)] = values

In [97]:
Atlanta.insert(0, 'Equipo', 'Atlanta')
Atlanta['Resultado_L'] = Atlanta['Resultado'].str.extract(r'([A-Za-z]+)')
Atlanta['Resultado_Numeros'] = Atlanta['Resultado'].str.extract(r'(\d+-\d+)')
Atlanta[['R1', 'R2']] = Atlanta['Resultado_Numeros'].str.split('-', expand=True)
Atlanta['Local/Visitante'] = Atlanta['Oponente'].str.split().str[0].str.replace('.', '')
Atlanta['Local/Visitante'] = Atlanta['Local/Visitante'].str.replace('vs', 'local').str.replace('en', 'visitante')
Atlanta['Equipo_Oponente'] = Atlanta['Oponente'].str.extract(r'(vs\.|en\s)([^,]+)')[1]
# Agregar las columnas "G," "P," y "E" basadas en la columna "Resultado_L"
Atlanta['G'] = (Atlanta['Resultado_L'] == 'G').astype(int)
Atlanta['P'] = (Atlanta['Resultado_L'] == 'P').astype(int)
Atlanta['E'] = (Atlanta['Resultado_L'] == 'E').astype(int)
columnas_deseadas = ['Equipo', 'Semana', 'Fecha', 'Resultado_L', 'R1', 'R2', 'Local/Visitante', 'Equipo_Oponente', 'G', 'P', 'E']
Atlanta_select = Atlanta[columnas_deseadas]
Atlanta_select.loc[:, ['Semana', 'R1', 'R2', 'G', 'P', 'E']] = Atlanta_select[['Semana', 'R1', 'R2', 'G', 'P', 'E']].astype(int)
Atlanta_select = Atlanta_select.copy()
Atlanta_select['Diferencia_Pts.'] = Atlanta_select['R1'] - Atlanta_select['R2']

In [98]:
Atlanta_select

,Equipo,Semana,Fecha,Resultado_L,R1,R2,Local/Visitante,Equipo_Oponente,G,P,E,Diferencia_Pts.
0,Atlanta,1,"Dom., 10 de Sep.",G,24,10,local,Carolina,1,0,0,14
1,Atlanta,2,"Dom., 17 de Sep.",G,25,24,local,Green Bay,1,0,0,1
2,Atlanta,3,"Dom., 24 de Sep.",P,20,6,visitante,Detroit,0,1,0,14
3,Atlanta,4,"Dom., 1 de Oct.",P,23,7,local,Jacksonville *,0,1,0,16
4,Atlanta,5,"Dom., 8 de Oct.",G,21,19,local,Houston,1,0,0,2
5,Atlanta,6,"Dom., 15 de Oct.",P,24,16,local,Washington,0,1,0,8
6,Atlanta,7,"Dom., 22 de Oct.",G,16,13,visitante,Tampa Bay,1,0,0,3
7,Atlanta,8,"Dom., 29 de Oct.",P,28,23,visitante,Tennessee,0,1,0,5

In [99]:
rCle = requests.get(urlCle, cookies=cookies, headers=headers)
html_contentsCle = rCle.text

In [100]:
html_soupCle = BeautifulSoup(html_contentsCle, 'html.parser')

In [101]:
calendarioCle = html_soupCle.find_all('table', class_='Table')

In [102]:
Cleveland = pd.DataFrame(columns = TabGen)

In [103]:
for table in calendarioCle:
    for row in table.find_all('tr')[2:21]:
        values = []
        for col in row.find_all(['th','td']):
            values.append(col.text)
        if len(values) == len(TabGen):
            Cleveland.loc[len(Cleveland)] = values

In [104]:
Cleveland.insert(0, 'Equipo', 'Cleveland')
Cleveland['Resultado_L'] = Cleveland['Resultado'].str.extract(r'([A-Za-z]+)')
Cleveland['Resultado_Numeros'] = Cleveland['Resultado'].str.extract(r'(\d+-\d+)')
Cleveland[['R1', 'R2']] = Cleveland['Resultado_Numeros'].str.split('-', expand=True)
Cleveland['Local/Visitante'] = Cleveland['Oponente'].str.split().str[0].str.replace('.', '')
Cleveland['Local/Visitante'] = Cleveland['Local/Visitante'].str.replace('vs', 'local').str.replace('en', 'visitante')
Cleveland['Equipo_Oponente'] = Cleveland['Oponente'].str.extract(r'(vs\.|en\s)([^,]+)')[1]
# Agregar las columnas "G," "P," y "E" basadas en la columna "Resultado_L"
Cleveland['G'] = (Cleveland['Resultado_L'] == 'G').astype(int)
Cleveland['P'] = (Cleveland['Resultado_L'] == 'P').astype(int)
Cleveland['E'] = (Cleveland['Resultado_L'] == 'E').astype(int)
columnas_deseadas = ['Equipo', 'Semana', 'Fecha', 'Resultado_L', 'R1', 'R2', 'Local/Visitante', 'Equipo_Oponente', 'G', 'P', 'E']
Cleveland_select = Cleveland[columnas_deseadas]
Cleveland_select.loc[:, ['Semana', 'R1', 'R2', 'G', 'P', 'E']] = Cleveland_select[['Semana', 'R1', 'R2', 'G', 'P', 'E']].astype(int)
Cleveland_select = Cleveland_select.copy()
Cleveland_select['Diferencia_Pts.'] = Cleveland_select['R1'] - Cleveland_select['R2']

In [105]:
Cleveland_select

,Equipo,Semana,Fecha,Resultado_L,R1,R2,Local/Visitante,Equipo_Oponente,G,P,E,Diferencia_Pts.
0,Cleveland,1,"Dom., 10 de Sep.",G,24,3,local,Cincinnati,1,0,0,21
1,Cleveland,2,"Lun., 18 de Sep.",P,26,22,visitante,Pittsburgh,0,1,0,4
2,Cleveland,3,"Dom., 24 de Sep.",G,27,3,local,Tennessee,1,0,0,24
3,Cleveland,4,"Dom., 1 de Oct.",P,28,3,local,Baltimore,0,1,0,25
4,Cleveland,6,"Dom., 15 de Oct.",G,19,17,local,San Francisco,1,0,0,2
5,Cleveland,7,"Dom., 22 de Oct.",G,39,38,visitante,Indianapolis,1,0,0,1
6,Cleveland,8,"Dom., 29 de Oct.",P,24,20,visitante,Seattle,0,1,0,4

In [106]:
rNyj = requests.get(urlNyj, cookies=cookies, headers=headers)
html_contentsNyj = rNyj.text

In [107]:
html_soupNyj = BeautifulSoup(html_contentsNyj, 'html.parser')

In [108]:
calendarioNyj = html_soupNyj.find_all('table', class_='Table')

In [109]:
New_York_Jets = pd.DataFrame(columns = TabGen)

In [110]:
for table in calendarioNyj:
    for row in table.find_all('tr')[2:21]:
        values = []
        for col in row.find_all(['th','td']):
            values.append(col.text)
        if len(values) == len(TabGen):
            New_York_Jets.loc[len(New_York_Jets)] = values

In [111]:
New_York_Jets.insert(0, 'Equipo', 'New York Jets')
New_York_Jets['Resultado_L'] = New_York_Jets['Resultado'].str.extract(r'([A-Za-z]+)')
New_York_Jets['Resultado_Numeros'] = New_York_Jets['Resultado'].str.extract(r'(\d+-\d+)')
New_York_Jets[['R1', 'R2']] = New_York_Jets['Resultado_Numeros'].str.split('-', expand=True)
New_York_Jets['Local/Visitante'] = New_York_Jets['Oponente'].str.split().str[0].str.replace('.', '')
New_York_Jets['Local/Visitante'] = New_York_Jets['Local/Visitante'].str.replace('vs', 'local').str.replace('en', 'visitante')
New_York_Jets['Equipo_Oponente'] = New_York_Jets['Oponente'].str.extract(r'(vs\.|en\s)([^,]+)')[1]
# Agregar las columnas "G," "P," y "E" basadas en la columna "Resultado_L"
New_York_Jets['G'] = (New_York_Jets['Resultado_L'] == 'G').astype(int)
New_York_Jets['P'] = (New_York_Jets['Resultado_L'] == 'P').astype(int)
New_York_Jets['E'] = (New_York_Jets['Resultado_L'] == 'E').astype(int)
columnas_deseadas = ['Equipo', 'Semana', 'Fecha', 'Resultado_L', 'R1', 'R2', 'Local/Visitante', 'Equipo_Oponente', 'G', 'P', 'E']
New_York_Jets_select = New_York_Jets[columnas_deseadas]
New_York_Jets_select.loc[:, ['Semana', 'R1', 'R2', 'G', 'P', 'E']] = New_York_Jets_select[['Semana', 'R1', 'R2', 'G', 'P', 'E']].astype(int)
New_York_Jets_select = New_York_Jets_select.copy()
New_York_Jets_select['Diferencia_Pts.'] = New_York_Jets_select['R1'] - New_York_Jets_select['R2']

In [112]:
New_York_Jets_select

,Equipo,Semana,Fecha,Resultado_L,R1,R2,Local/Visitante,Equipo_Oponente,G,P,E,Diferencia_Pts.
0,New York Jets,1,"Lun., 11 de Sep.",G,22,16,local,Buffalo,1,0,0,6
1,New York Jets,2,"Dom., 17 de Sep.",P,30,10,visitante,Dallas,0,1,0,20
2,New York Jets,3,"Dom., 24 de Sep.",P,15,10,local,New England,0,1,0,5
3,New York Jets,4,"Dom., 1 de Oct.",P,23,20,local,Kansas City,0,1,0,3
4,New York Jets,5,"Dom., 8 de Oct.",G,31,21,visitante,Denver,1,0,0,10
5,New York Jets,6,"Dom., 15 de Oct.",G,20,14,local,Philadelphia,1,0,0,6
6,New York Jets,8,"Dom., 29 de Oct.",G,13,10,visitante,New York,1,0,0,3

In [113]:
rDet = requests.get(urlDet, cookies=cookies, headers=headers)
html_contentsDet = rDet.text

In [114]:
html_soupDet = BeautifulSoup(html_contentsDet, 'html.parser')

In [115]:
calendarioDet = html_soupDet.find_all('table', class_='Table')

In [116]:
Detroit = pd.DataFrame(columns = TabGen)

In [117]:
for table in calendarioDet:
    for row in table.find_all('tr')[2:21]:
        values = []
        for col in row.find_all(['th','td']):
            values.append(col.text)
        if len(values) == len(TabGen):
            Detroit.loc[len(Detroit)] = values

In [118]:
Detroit.insert(0, 'Equipo', 'Detroit')
Detroit['Resultado_L'] = Detroit['Resultado'].str.extract(r'([A-Za-z]+)')
Detroit['Resultado_Numeros'] = Detroit['Resultado'].str.extract(r'(\d+-\d+)')
Detroit[['R1', 'R2']] = Detroit['Resultado_Numeros'].str.split('-', expand=True)
Detroit['Local/Visitante'] = Detroit['Oponente'].str.split().str[0].str.replace('.', '')
Detroit['Local/Visitante'] = Detroit['Local/Visitante'].str.replace('vs', 'local').str.replace('en', 'visitante')
Detroit['Equipo_Oponente'] = Detroit['Oponente'].str.extract(r'(vs\.|en\s)([^,]+)')[1]
# Agregar las columnas "G," "P," y "E" basadas en la columna "Resultado_L"
Detroit['G'] = (Detroit['Resultado_L'] == 'G').astype(int)
Detroit['P'] = (Detroit['Resultado_L'] == 'P').astype(int)
Detroit['E'] = (Detroit['Resultado_L'] == 'E').astype(int)
columnas_deseadas = ['Equipo', 'Semana', 'Fecha', 'Resultado_L', 'R1', 'R2', 'Local/Visitante', 'Equipo_Oponente', 'G', 'P', 'E']
Detroit_select = Detroit[columnas_deseadas]
Detroit_select.loc[:, ['Semana', 'R1', 'R2', 'G', 'P', 'E']] = Detroit_select[['Semana', 'R1', 'R2', 'G', 'P', 'E']].astype(int)
Detroit_select = Detroit_select.copy()
Detroit_select['Diferencia_Pts.'] = Detroit_select['R1'] - Detroit_select['R2']

In [119]:
Detroit_select

,Equipo,Semana,Fecha,Resultado_L,R1,R2,Local/Visitante,Equipo_Oponente,G,P,E,Diferencia_Pts.
0,Detroit,1,"Jue., 7 de Sep.",G,21,20,visitante,Kansas City,1,0,0,1
1,Detroit,2,"Dom., 17 de Sep.",P,37,31,local,Seattle,0,1,0,6
2,Detroit,3,"Dom., 24 de Sep.",G,20,6,local,Atlanta,1,0,0,14
3,Detroit,4,"Jue., 28 de Sep.",G,34,20,visitante,Green Bay,1,0,0,14
4,Detroit,5,"Dom., 8 de Oct.",G,42,24,local,Carolina,1,0,0,18
5,Detroit,6,"Dom., 15 de Oct.",G,20,6,visitante,Tampa Bay,1,0,0,14
6,Detroit,7,"Dom., 22 de Oct.",P,38,6,visitante,Baltimore,0,1,0,32
7,Detroit,8,"Lun., 30 de Oct.",G,26,14,local,Las Vegas,1,0,0,12

In [120]:
rTb = requests.get(urlTb, cookies=cookies, headers=headers)
html_contentsTb = rTb.text

In [121]:
html_soupTb = BeautifulSoup(html_contentsTb, 'html.parser')

In [122]:
calendarioTb = html_soupTb.find_all('table', class_='Table')

In [123]:
Tampa_Bay = pd.DataFrame(columns = TabGen)

In [124]:
for table in calendarioTb:
    for row in table.find_all('tr')[2:21]:
        values = []
        for col in row.find_all(['th','td']):
            values.append(col.text)
        if len(values) == len(TabGen):
            Tampa_Bay.loc[len(Tampa_Bay)] = values

In [125]:
Tampa_Bay.insert(0, 'Equipo', 'Tampa Bay')
Tampa_Bay['Resultado_L'] = Tampa_Bay['Resultado'].str.extract(r'([A-Za-z]+)')
Tampa_Bay['Resultado_Numeros'] = Tampa_Bay['Resultado'].str.extract(r'(\d+-\d+)')
Tampa_Bay[['R1', 'R2']] = Tampa_Bay['Resultado_Numeros'].str.split('-', expand=True)
Tampa_Bay['Local/Visitante'] = Tampa_Bay['Oponente'].str.split().str[0].str.replace('.', '')
Tampa_Bay['Local/Visitante'] = Tampa_Bay['Local/Visitante'].str.replace('vs', 'local').str.replace('en', 'visitante')
Tampa_Bay['Equipo_Oponente'] = Tampa_Bay['Oponente'].str.extract(r'(vs\.|en\s)([^,]+)')[1]
# Agregar las columnas "G," "P," y "E" basadas en la columna "Resultado_L"
Tampa_Bay['G'] = (Tampa_Bay['Resultado_L'] == 'G').astype(int)
Tampa_Bay['P'] = (Tampa_Bay['Resultado_L'] == 'P').astype(int)
Tampa_Bay['E'] = (Tampa_Bay['Resultado_L'] == 'E').astype(int)
columnas_deseadas = ['Equipo', 'Semana', 'Fecha', 'Resultado_L', 'R1', 'R2', 'Local/Visitante', 'Equipo_Oponente', 'G', 'P', 'E']
Tampa_Bay_select = Tampa_Bay[columnas_deseadas]
Tampa_Bay_select.loc[:, ['Semana', 'R1', 'R2', 'G', 'P', 'E']] = Tampa_Bay_select[['Semana', 'R1', 'R2', 'G', 'P', 'E']].astype(int)
Tampa_Bay_select = Tampa_Bay_select.copy()
Tampa_Bay_select['Diferencia_Pts.'] = Tampa_Bay_select['R1'] - Tampa_Bay_select['R2']

In [126]:
Tampa_Bay_select

,Equipo,Semana,Fecha,Resultado_L,R1,R2,Local/Visitante,Equipo_Oponente,G,P,E,Diferencia_Pts.
0,Tampa Bay,1,"Dom., 10 de Sep.",G,20,17,visitante,Minnesota,1,0,0,3
1,Tampa Bay,2,"Dom., 17 de Sep.",G,27,17,local,Chicago,1,0,0,10
2,Tampa Bay,3,"Lun., 25 de Sep.",P,25,11,local,Philadelphia,0,1,0,14
3,Tampa Bay,4,"Dom., 1 de Oct.",G,26,9,visitante,New Orleans,1,0,0,17
4,Tampa Bay,6,"Dom., 15 de Oct.",P,20,6,local,Detroit,0,1,0,14
5,Tampa Bay,7,"Dom., 22 de Oct.",P,16,13,local,Atlanta,0,1,0,3
6,Tampa Bay,8,"Jue., 26 de Oct.",P,24,18,visitante,Buffalo,0,1,0,6

In [127]:
rWsh = requests.get(urlWsh, cookies=cookies, headers=headers)
html_contentsWsh = rWsh.text

In [128]:
html_soupWsh = BeautifulSoup(html_contentsWsh, 'html.parser')

In [129]:
calendarioWsh = html_soupWsh.find_all('table', class_='Table')

In [130]:
Washington = pd.DataFrame(columns = TabGen)

In [131]:
for table in calendarioWsh:
    for row in table.find_all('tr')[2:21]:
        values = []
        for col in row.find_all(['th','td']):
            values.append(col.text)
        if len(values) == len(TabGen):
            Washington.loc[len(Washington)] = values

In [132]:
Washington.insert(0, 'Equipo', 'Washington')
Washington['Resultado_L'] = Washington['Resultado'].str.extract(r'([A-Za-z]+)')
Washington['Resultado_Numeros'] = Washington['Resultado'].str.extract(r'(\d+-\d+)')
Washington[['R1', 'R2']] = Washington['Resultado_Numeros'].str.split('-', expand=True)
Washington['Local/Visitante'] = Washington['Oponente'].str.split().str[0].str.replace('.', '')
Washington['Local/Visitante'] = Washington['Local/Visitante'].str.replace('vs', 'local').str.replace('en', 'visitante')
Washington['Equipo_Oponente'] = Washington['Oponente'].str.extract(r'(vs\.|en\s)([^,]+)')[1]
# Agregar las columnas "G," "P," y "E" basadas en la columna "Resultado_L"
Washington['G'] = (Washington['Resultado_L'] == 'G').astype(int)
Washington['P'] = (Washington['Resultado_L'] == 'P').astype(int)
Washington['E'] = (Washington['Resultado_L'] == 'E').astype(int)
columnas_deseadas = ['Equipo', 'Semana', 'Fecha', 'Resultado_L', 'R1', 'R2', 'Local/Visitante', 'Equipo_Oponente', 'G', 'P', 'E']
Washington_select = Washington[columnas_deseadas]
Washington_select.loc[:, ['Semana', 'R1', 'R2', 'G', 'P', 'E']] = Washington_select[['Semana', 'R1', 'R2', 'G', 'P', 'E']].astype(int)
Washington_select = Washington_select.copy()
Washington_select['Diferencia_Pts.'] = Washington_select['R1'] - Washington_select['R2']

In [133]:
Washington_select

,Equipo,Semana,Fecha,Resultado_L,R1,R2,Local/Visitante,Equipo_Oponente,G,P,E,Diferencia_Pts.
0,Washington,1,"Dom., 10 de Sep.",G,20,16,local,Arizona,1,0,0,4
1,Washington,2,"Dom., 17 de Sep.",G,35,33,visitante,Denver,1,0,0,2
2,Washington,3,"Dom., 24 de Sep.",P,37,3,local,Buffalo,0,1,0,34
3,Washington,4,"Dom., 1 de Oct.",P,34,31,visitante,Philadelphia,0,1,0,3
4,Washington,5,"Jue., 5 de Oct.",P,40,20,local,Chicago,0,1,0,20
5,Washington,6,"Dom., 15 de Oct.",G,24,16,visitante,Atlanta,1,0,0,8
6,Washington,7,"Dom., 22 de Oct.",P,14,7,visitante,New York,0,1,0,7
7,Washington,8,"Dom., 29 de Oct.",P,38,31,local,Philadelphia,0,1,0,7

In [134]:
rLv = requests.get(urlLv, cookies=cookies, headers=headers)
html_contentsLv = rLv.text

In [135]:
html_soupLv = BeautifulSoup(html_contentsLv, 'html.parser')

In [136]:
calendarioLv = html_soupLv.find_all('table', class_='Table')

In [137]:
Las_Vegas = pd.DataFrame(columns = TabGen)

In [138]:
for table in calendarioLv:
    for row in table.find_all('tr')[2:21]:
        values = []
        for col in row.find_all(['th','td']):
            values.append(col.text)
        if len(values) == len(TabGen):
            Las_Vegas.loc[len(Las_Vegas)] = values

In [139]:
Las_Vegas.insert(0, 'Equipo', 'Las Vegas')
Las_Vegas['Resultado_L'] = Las_Vegas['Resultado'].str.extract(r'([A-Za-z]+)')
Las_Vegas['Resultado_Numeros'] = Las_Vegas['Resultado'].str.extract(r'(\d+-\d+)')
Las_Vegas[['R1', 'R2']] = Las_Vegas['Resultado_Numeros'].str.split('-', expand=True)
Las_Vegas['Local/Visitante'] = Las_Vegas['Oponente'].str.split().str[0].str.replace('.', '')
Las_Vegas['Local/Visitante'] = Las_Vegas['Local/Visitante'].str.replace('vs', 'local').str.replace('en', 'visitante')
Las_Vegas['Equipo_Oponente'] = Las_Vegas['Oponente'].str.extract(r'(vs\.|en\s)([^,]+)')[1]
# Agregar las columnas "G," "P," y "E" basadas en la columna "Resultado_L"
Las_Vegas['G'] = (Las_Vegas['Resultado_L'] == 'G').astype(int)
Las_Vegas['P'] = (Las_Vegas['Resultado_L'] == 'P').astype(int)
Las_Vegas['E'] = (Las_Vegas['Resultado_L'] == 'E').astype(int)
columnas_deseadas = ['Equipo', 'Semana', 'Fecha', 'Resultado_L', 'R1', 'R2', 'Local/Visitante', 'Equipo_Oponente', 'G', 'P', 'E']
Las_Vegas_select = Las_Vegas[columnas_deseadas]
Las_Vegas_select.loc[:, ['Semana', 'R1', 'R2', 'G', 'P', 'E']] = Las_Vegas_select[['Semana', 'R1', 'R2', 'G', 'P', 'E']].astype(int)
Las_Vegas_select = Las_Vegas_select.copy()
Las_Vegas_select['Diferencia_Pts.'] = Las_Vegas_select['R1'] - Las_Vegas_select['R2']

In [140]:
Las_Vegas_select

,Equipo,Semana,Fecha,Resultado_L,R1,R2,Local/Visitante,Equipo_Oponente,G,P,E,Diferencia_Pts.
0,Las Vegas,1,"Dom., 10 de Sep.",G,17,16,visitante,Denver,1,0,0,1
1,Las Vegas,2,"Dom., 17 de Sep.",P,38,10,visitante,Buffalo,0,1,0,28
2,Las Vegas,3,"Dom., 24 de Sep.",P,23,18,local,Pittsburgh,0,1,0,5
3,Las Vegas,4,"Dom., 1 de Oct.",P,24,17,visitante,Los Angeles,0,1,0,7
4,Las Vegas,5,"Lun., 9 de Oct.",G,17,13,local,Green Bay,1,0,0,4
5,Las Vegas,6,"Dom., 15 de Oct.",G,21,17,local,New England,1,0,0,4
6,Las Vegas,7,"Dom., 22 de Oct.",P,30,12,visitante,Chicago,0,1,0,18
7,Las Vegas,8,"Lun., 30 de Oct.",P,26,14,visitante,Detroit,0,1,0,12

In [141]:
rNo = requests.get(urlNo, cookies=cookies, headers=headers)
html_contentsNo = rNo.text

In [142]:
html_soupNo = BeautifulSoup(html_contentsNo, 'html.parser')

In [143]:
calendarioNo = html_soupNo.find_all('table', class_='Table')

In [144]:
New_Orleans = pd.DataFrame(columns = TabGen)

In [145]:
for table in calendarioNo:
    for row in table.find_all('tr')[2:21]:
        values = []
        for col in row.find_all(['th','td']):
            values.append(col.text)
        if len(values) == len(TabGen):
            New_Orleans.loc[len(New_Orleans)] = values

In [146]:
New_Orleans.insert(0, 'Equipo', 'New Orleans')
New_Orleans['Resultado_L'] = New_Orleans['Resultado'].str.extract(r'([A-Za-z]+)')
New_Orleans['Resultado_Numeros'] = New_Orleans['Resultado'].str.extract(r'(\d+-\d+)')
New_Orleans[['R1', 'R2']] = New_Orleans['Resultado_Numeros'].str.split('-', expand=True)
New_Orleans['Local/Visitante'] = New_Orleans['Oponente'].str.split().str[0].str.replace('.', '')
New_Orleans['Local/Visitante'] = New_Orleans['Local/Visitante'].str.replace('vs', 'local').str.replace('en', 'visitante')
New_Orleans['Equipo_Oponente'] = New_Orleans['Oponente'].str.extract(r'(vs\.|en\s)([^,]+)')[1]
# Agregar las columnas "G," "P," y "E" basadas en la columna "Resultado_L"
New_Orleans['G'] = (New_Orleans['Resultado_L'] == 'G').astype(int)
New_Orleans['P'] = (New_Orleans['Resultado_L'] == 'P').astype(int)
New_Orleans['E'] = (New_Orleans['Resultado_L'] == 'E').astype(int)
columnas_deseadas = ['Equipo', 'Semana', 'Fecha', 'Resultado_L', 'R1', 'R2', 'Local/Visitante', 'Equipo_Oponente', 'G', 'P', 'E']
New_Orleans_select = New_Orleans[columnas_deseadas]
New_Orleans_select.loc[:, ['Semana', 'R1', 'R2', 'G', 'P', 'E']] = New_Orleans_select[['Semana', 'R1', 'R2', 'G', 'P', 'E']].astype(int)
New_Orleans_select = New_Orleans_select.copy()
New_Orleans_select['Diferencia_Pts.'] = New_Orleans_select['R1'] - New_Orleans_select['R2']

In [147]:
New_Orleans_select

,Equipo,Semana,Fecha,Resultado_L,R1,R2,Local/Visitante,Equipo_Oponente,G,P,E,Diferencia_Pts.
0,New Orleans,1,"Dom., 10 de Sep.",G,16,15,local,Tennessee,1,0,0,1
1,New Orleans,2,"Lun., 18 de Sep.",G,20,17,visitante,Carolina,1,0,0,3
2,New Orleans,3,"Dom., 24 de Sep.",P,18,17,visitante,Green Bay,0,1,0,1
3,New Orleans,4,"Dom., 1 de Oct.",P,26,9,local,Tampa Bay,0,1,0,17
4,New Orleans,5,"Dom., 8 de Oct.",G,34,0,visitante,New England,1,0,0,34
5,New Orleans,6,"Dom., 15 de Oct.",P,20,13,visitante,Houston,0,1,0,7
6,New Orleans,7,"Jue., 19 de Oct.",P,31,24,local,Jacksonville,0,1,0,7
7,New Orleans,8,"Dom., 29 de Oct.",G,38,27,visitante,Indianapolis,1,0,0,11

In [148]:
rLac= requests.get(urlLac, cookies=cookies, headers=headers)
html_contentsLac = rLac.text

In [149]:
html_soupLac = BeautifulSoup(html_contentsLac, 'html.parser')

In [150]:
calendarioLac = html_soupLac.find_all('table', class_='Table')

In [151]:
Los_Angeles_Chargers = pd.DataFrame(columns = TabGen)

In [152]:
for table in calendarioLac:
    for row in table.find_all('tr')[2:21]:
        values = []
        for col in row.find_all(['th','td']):
            values.append(col.text)
        if len(values) == len(TabGen):
            Los_Angeles_Chargers.loc[len(Los_Angeles_Chargers)] = values

In [153]:
Los_Angeles_Chargers.insert(0, 'Equipo', 'Los Angeles Chargers')
Los_Angeles_Chargers['Resultado_L'] = Los_Angeles_Chargers['Resultado'].str.extract(r'([A-Za-z]+)')
Los_Angeles_Chargers['Resultado_Numeros'] = Los_Angeles_Chargers['Resultado'].str.extract(r'(\d+-\d+)')
Los_Angeles_Chargers[['R1', 'R2']] = Los_Angeles_Chargers['Resultado_Numeros'].str.split('-', expand=True)
Los_Angeles_Chargers['Local/Visitante'] = Los_Angeles_Chargers['Oponente'].str.split().str[0].str.replace('.', '')
Los_Angeles_Chargers['Local/Visitante'] = Los_Angeles_Chargers['Local/Visitante'].str.replace('vs', 'local').str.replace('en', 'visitante')
Los_Angeles_Chargers['Equipo_Oponente'] = Los_Angeles_Chargers['Oponente'].str.extract(r'(vs\.|en\s)([^,]+)')[1]
# Agregar las columnas "G," "P," y "E" basadas en la columna "Resultado_L"
Los_Angeles_Chargers['G'] = (Los_Angeles_Chargers['Resultado_L'] == 'G').astype(int)
Los_Angeles_Chargers['P'] = (Los_Angeles_Chargers['Resultado_L'] == 'P').astype(int)
Los_Angeles_Chargers['E'] = (Los_Angeles_Chargers['Resultado_L'] == 'E').astype(int)
columnas_deseadas = ['Equipo', 'Semana', 'Fecha', 'Resultado_L', 'R1', 'R2', 'Local/Visitante', 'Equipo_Oponente', 'G', 'P', 'E']
Los_Angeles_Chargers_select = Los_Angeles_Chargers[columnas_deseadas]
Los_Angeles_Chargers_select.loc[:, ['Semana', 'R1', 'R2', 'G', 'P', 'E']] = Los_Angeles_Chargers_select[['Semana', 'R1', 'R2', 'G', 'P', 'E']].astype(int)
Los_Angeles_Chargers_select = Los_Angeles_Chargers_select.copy()
Los_Angeles_Chargers_select['Diferencia_Pts.'] = Los_Angeles_Chargers_select['R1'] - Los_Angeles_Chargers_select['R2']

In [154]:
Los_Angeles_Chargers_select

,Equipo,Semana,Fecha,Resultado_L,R1,R2,Local/Visitante,Equipo_Oponente,G,P,E,Diferencia_Pts.
0,Los Angeles Chargers,1,"Dom., 10 de Sep.",P,36,34,local,Miami,0,1,0,2
1,Los Angeles Chargers,2,"Dom., 17 de Sep.",P,27,24,visitante,Tennessee,0,1,0,3
2,Los Angeles Chargers,3,"Dom., 24 de Sep.",G,28,24,visitante,Minnesota,1,0,0,4
3,Los Angeles Chargers,4,"Dom., 1 de Oct.",G,24,17,local,Las Vegas,1,0,0,7
4,Los Angeles Chargers,6,"Lun., 16 de Oct.",P,20,17,local,Dallas,0,1,0,3
5,Los Angeles Chargers,7,"Dom., 22 de Oct.",P,31,17,visitante,Kansas City,0,1,0,14
6,Los Angeles Chargers,8,"Dom., 29 de Oct.",G,30,13,local,Chicago,1,0,0,17

In [155]:
rInd = requests.get(urlInd, cookies=cookies, headers=headers)
html_contentsInd = rInd.text

In [156]:
html_soupInd = BeautifulSoup(html_contentsInd, 'html.parser')

In [157]:
calendarioInd = html_soupInd.find_all('table', class_='Table')

In [158]:
Indianapolis = pd.DataFrame(columns = TabGen)

In [159]:
for table in calendarioInd:
    for row in table.find_all('tr')[2:21]:
        values = []
        for col in row.find_all(['th','td']):
            values.append(col.text)
        if len(values) == len(TabGen):
            Indianapolis.loc[len(Indianapolis)] = values

In [160]:
Indianapolis.insert(0, 'Equipo', 'Indianapolis')
Indianapolis['Resultado_L'] = Indianapolis['Resultado'].str.extract(r'([A-Za-z]+)')
Indianapolis['Resultado_Numeros'] = Indianapolis['Resultado'].str.extract(r'(\d+-\d+)')
Indianapolis[['R1', 'R2']] = Indianapolis['Resultado_Numeros'].str.split('-', expand=True)
Indianapolis['Local/Visitante'] = Indianapolis['Oponente'].str.split().str[0].str.replace('.', '')
Indianapolis['Local/Visitante'] = Indianapolis['Local/Visitante'].str.replace('vs', 'local').str.replace('en', 'visitante')
Indianapolis['Equipo_Oponente'] = Indianapolis['Oponente'].str.extract(r'(vs\.|en\s)([^,]+)')[1]
# Agregar las columnas "G," "P," y "E" basadas en la columna "Resultado_L"
Indianapolis['G'] = (Indianapolis['Resultado_L'] == 'G').astype(int)
Indianapolis['P'] = (Indianapolis['Resultado_L'] == 'P').astype(int)
Indianapolis['E'] = (Indianapolis['Resultado_L'] == 'E').astype(int)
columnas_deseadas = ['Equipo', 'Semana', 'Fecha', 'Resultado_L', 'R1', 'R2', 'Local/Visitante', 'Equipo_Oponente', 'G', 'P', 'E']
Indianapolis_select = Indianapolis[columnas_deseadas]
Indianapolis_select.loc[:, ['Semana', 'R1', 'R2', 'G', 'P', 'E']] = Indianapolis_select[['Semana', 'R1', 'R2', 'G', 'P', 'E']].astype(int)
Indianapolis_select = Indianapolis_select.copy()
Indianapolis_select['Diferencia_Pts.'] = Indianapolis_select['R1'] - Indianapolis_select['R2']

In [161]:
Indianapolis_select

,Equipo,Semana,Fecha,Resultado_L,R1,R2,Local/Visitante,Equipo_Oponente,G,P,E,Diferencia_Pts.
0,Indianapolis,1,"Dom., 10 de Sep.",P,31,21,local,Jacksonville,0,1,0,10
1,Indianapolis,2,"Dom., 17 de Sep.",G,31,20,visitante,Houston,1,0,0,11
2,Indianapolis,3,"Dom., 24 de Sep.",G,22,19,visitante,Baltimore,1,0,0,3
3,Indianapolis,4,"Dom., 1 de Oct.",P,29,23,local,Los Angeles,0,1,0,6
4,Indianapolis,5,"Dom., 8 de Oct.",G,23,16,local,Tennessee,1,0,0,7
5,Indianapolis,6,"Dom., 15 de Oct.",P,37,20,visitante,Jacksonville,0,1,0,17
6,Indianapolis,7,"Dom., 22 de Oct.",P,39,38,local,Cleveland,0,1,0,1
7,Indianapolis,8,"Dom., 29 de Oct.",P,38,27,local,New Orleans,0,1,0,11

In [162]:
rChi = requests.get(urlChi, cookies=cookies, headers=headers)
html_contentsChi = rChi.text

In [163]:
html_soupChi = BeautifulSoup(html_contentsChi, 'html.parser')

In [164]:
calendarioChi = html_soupChi.find_all('table', class_='Table')

In [165]:
Chicago = pd.DataFrame(columns = TabGen)

In [166]:
for table in calendarioChi:
    for row in table.find_all('tr')[2:21]:
        values = []
        for col in row.find_all(['th','td']):
            values.append(col.text)
        if len(values) == len(TabGen):
            Chicago.loc[len(Chicago)] = values

In [167]:
Chicago.insert(0, 'Equipo', 'Chicago')
Chicago['Resultado_L'] = Chicago['Resultado'].str.extract(r'([A-Za-z]+)')
Chicago['Resultado_Numeros'] = Chicago['Resultado'].str.extract(r'(\d+-\d+)')
Chicago[['R1', 'R2']] = Chicago['Resultado_Numeros'].str.split('-', expand=True)
Chicago['Local/Visitante'] = Chicago['Oponente'].str.split().str[0].str.replace('.', '')
Chicago['Local/Visitante'] = Chicago['Local/Visitante'].str.replace('vs', 'local').str.replace('en', 'visitante')
Chicago['Equipo_Oponente'] = Chicago['Oponente'].str.extract(r'(vs\.|en\s)([^,]+)')[1]
# Agregar las columnas "G," "P," y "E" basadas en la columna "Resultado_L"
Chicago['G'] = (Chicago['Resultado_L'] == 'G').astype(int)
Chicago['P'] = (Chicago['Resultado_L'] == 'P').astype(int)
Chicago['E'] = (Chicago['Resultado_L'] == 'E').astype(int)
columnas_deseadas = ['Equipo', 'Semana', 'Fecha', 'Resultado_L', 'R1', 'R2', 'Local/Visitante', 'Equipo_Oponente', 'G', 'P', 'E']
Chicago_select = Chicago[columnas_deseadas]
Chicago_select.loc[:, ['Semana', 'R1', 'R2', 'G', 'P', 'E']] = Chicago_select[['Semana', 'R1', 'R2', 'G', 'P', 'E']].astype(int)
Chicago_select = Chicago_select.copy()
Chicago_select['Diferencia_Pts.'] = Chicago_select['R1'] - Chicago_select['R2']

In [168]:
Chicago_select

,Equipo,Semana,Fecha,Resultado_L,R1,R2,Local/Visitante,Equipo_Oponente,G,P,E,Diferencia_Pts.
0,Chicago,1,"Dom., 10 de Sep.",P,38,20,local,Green Bay,0,1,0,18
1,Chicago,2,"Dom., 17 de Sep.",P,27,17,visitante,Tampa Bay,0,1,0,10
2,Chicago,3,"Dom., 24 de Sep.",P,41,10,visitante,Kansas City,0,1,0,31
3,Chicago,4,"Dom., 1 de Oct.",P,31,28,local,Denver,0,1,0,3
4,Chicago,5,"Jue., 5 de Oct.",G,40,20,visitante,Washington,1,0,0,20
5,Chicago,6,"Dom., 15 de Oct.",P,19,13,local,Minnesota,0,1,0,6
6,Chicago,7,"Dom., 22 de Oct.",G,30,12,local,Las Vegas,1,0,0,18
7,Chicago,8,"Dom., 29 de Oct.",P,30,13,visitante,Los Angeles,0,1,0,17

In [169]:
rKc = requests.get(urlKc, cookies=cookies, headers=headers)
html_contentsKc = rKc.text

In [170]:
html_soupKc = BeautifulSoup(html_contentsKc, 'html.parser')

In [171]:
calendarioKc = html_soupKc.find_all('table', class_='Table')

In [172]:
Kansas_City = pd.DataFrame(columns = TabGen)

In [173]:
for table in calendarioKc:
    for row in table.find_all('tr')[2:21]:
        values = []
        for col in row.find_all(['th','td']):
            values.append(col.text)
        if len(values) == len(TabGen):
            Kansas_City.loc[len(Kansas_City)] = values

In [174]:
Kansas_City.insert(0, 'Equipo', 'Kansas City')
Kansas_City['Resultado_L'] = Kansas_City['Resultado'].str.extract(r'([A-Za-z]+)')
Kansas_City['Resultado_Numeros'] = Kansas_City['Resultado'].str.extract(r'(\d+-\d+)')
Kansas_City[['R1', 'R2']] = Kansas_City['Resultado_Numeros'].str.split('-', expand=True)
Kansas_City['Local/Visitante'] = Kansas_City['Oponente'].str.split().str[0].str.replace('.', '')
Kansas_City['Local/Visitante'] = Kansas_City['Local/Visitante'].str.replace('vs', 'local').str.replace('en', 'visitante')
Kansas_City['Equipo_Oponente'] = Kansas_City['Oponente'].str.extract(r'(vs\.|en\s)([^,]+)')[1]
# Agregar las columnas "G," "P," y "E" basadas en la columna "Resultado_L"
Kansas_City['G'] = (Kansas_City['Resultado_L'] == 'G').astype(int)
Kansas_City['P'] = (Kansas_City['Resultado_L'] == 'P').astype(int)
Kansas_City['E'] = (Kansas_City['Resultado_L'] == 'E').astype(int)
columnas_deseadas = ['Equipo', 'Semana', 'Fecha', 'Resultado_L', 'R1', 'R2', 'Local/Visitante', 'Equipo_Oponente', 'G', 'P', 'E']
Kansas_City_select = Kansas_City[columnas_deseadas]
Kansas_City_select.loc[:, ['Semana', 'R1', 'R2', 'G', 'P', 'E']] = Kansas_City_select[['Semana', 'R1', 'R2', 'G', 'P', 'E']].astype(int)
Kansas_City_select = Kansas_City_select.copy()
Kansas_City_select['Diferencia_Pts.'] = Kansas_City_select['R1'] - Kansas_City_select['R2']

In [175]:
Kansas_City_select

,Equipo,Semana,Fecha,Resultado_L,R1,R2,Local/Visitante,Equipo_Oponente,G,P,E,Diferencia_Pts.
0,Kansas City,1,"Jue., 7 de Sep.",P,21,20,local,Detroit,0,1,0,1
1,Kansas City,2,"Dom., 17 de Sep.",G,17,9,visitante,Jacksonville,1,0,0,8
2,Kansas City,3,"Dom., 24 de Sep.",G,41,10,local,Chicago,1,0,0,31
3,Kansas City,4,"Dom., 1 de Oct.",G,23,20,visitante,New York,1,0,0,3
4,Kansas City,5,"Dom., 8 de Oct.",G,27,20,visitante,Minnesota,1,0,0,7
5,Kansas City,6,"Jue., 12 de Oct.",G,19,8,local,Denver,1,0,0,11
6,Kansas City,7,"Dom., 22 de Oct.",G,31,17,local,Los Angeles,1,0,0,14
7,Kansas City,8,"Dom., 29 de Oct.",P,24,9,visitante,Denver,0,1,0,15

In [176]:
rNe = requests.get(urlNe, cookies=cookies, headers=headers)
html_contentsNe = rNe.text

In [177]:
html_soupNe = BeautifulSoup(html_contentsNe, 'html.parser')

In [178]:
calendarioNe = html_soupNe.find_all('table', class_='Table')

In [179]:
New_England  = pd.DataFrame(columns = TabGen)

In [180]:
for table in calendarioNe:
    for row in table.find_all('tr')[2:21]:
        values = []
        for col in row.find_all(['th','td']):
            values.append(col.text)
        if len(values) == len(TabGen):
            New_England.loc[len(New_England)] = values

In [181]:
New_England.insert(0, 'Equipo', 'New England')
New_England['Resultado_L'] = New_England['Resultado'].str.extract(r'([A-Za-z]+)')
New_England['Resultado_Numeros'] = New_England['Resultado'].str.extract(r'(\d+-\d+)')
New_England[['R1', 'R2']] = New_England['Resultado_Numeros'].str.split('-', expand=True)
New_England['Local/Visitante'] = New_England['Oponente'].str.split().str[0].str.replace('.', '')
New_England['Local/Visitante'] = New_England['Local/Visitante'].str.replace('vs', 'local').str.replace('en', 'visitante')
New_England['Equipo_Oponente'] = New_England['Oponente'].str.extract(r'(vs\.|en\s)([^,]+)')[1]
# Agregar las columnas "G," "P," y "E" basadas en la columna "Resultado_L"
New_England['G'] = (New_England['Resultado_L'] == 'G').astype(int)
New_England['P'] = (New_England['Resultado_L'] == 'P').astype(int)
New_England['E'] = (New_England['Resultado_L'] == 'E').astype(int)
columnas_deseadas = ['Equipo', 'Semana', 'Fecha', 'Resultado_L', 'R1', 'R2', 'Local/Visitante', 'Equipo_Oponente', 'G', 'P', 'E']
New_England_select = New_England[columnas_deseadas]
New_England_select.loc[:, ['Semana', 'R1', 'R2', 'G', 'P', 'E']] = New_England_select[['Semana', 'R1', 'R2', 'G', 'P', 'E']].astype(int)
New_England_select = New_England_select.copy()
New_England_select['Diferencia_Pts.'] = New_England_select['R1'] - New_England_select['R2']

In [182]:
New_England_select

,Equipo,Semana,Fecha,Resultado_L,R1,R2,Local/Visitante,Equipo_Oponente,G,P,E,Diferencia_Pts.
0,New England,1,"Dom., 10 de Sep.",P,25,20,local,Philadelphia,0,1,0,5
1,New England,2,"Dom., 17 de Sep.",P,24,17,local,Miami,0,1,0,7
2,New England,3,"Dom., 24 de Sep.",G,15,10,visitante,New York,1,0,0,5
3,New England,4,"Dom., 1 de Oct.",P,38,3,visitante,Dallas,0,1,0,35
4,New England,5,"Dom., 8 de Oct.",P,34,0,local,New Orleans,0,1,0,34
5,New England,6,"Dom., 15 de Oct.",P,21,17,visitante,Las Vegas,0,1,0,4
6,New England,7,"Dom., 22 de Oct.",G,29,25,local,Buffalo,1,0,0,4
7,New England,8,"Dom., 29 de Oct.",P,31,17,visitante,Miami,0,1,0,14

In [183]:
rMin = requests.get(urlMin, cookies=cookies, headers=headers)
html_contentsMin = rMin.text

In [184]:
html_soupMin = BeautifulSoup(html_contentsMin, 'html.parser')

In [185]:
calendarioMin = html_soupMin.find_all('table', class_='Table')

In [186]:
Minnesota  = pd.DataFrame(columns = TabGen)

In [187]:
for table in calendarioMin:
    for row in table.find_all('tr')[2:21]:
        values = []
        for col in row.find_all(['th','td']):
            values.append(col.text)
        if len(values) == len(TabGen):
            Minnesota.loc[len(Minnesota)] = values

In [188]:
Minnesota.insert(0, 'Equipo', 'Minnesota')
Minnesota['Resultado_L'] = Minnesota['Resultado'].str.extract(r'([A-Za-z]+)')
Minnesota['Resultado_Numeros'] = Minnesota['Resultado'].str.extract(r'(\d+-\d+)')
Minnesota[['R1', 'R2']] = Minnesota['Resultado_Numeros'].str.split('-', expand=True)
Minnesota['Local/Visitante'] = Minnesota['Oponente'].str.split().str[0].str.replace('.', '')
Minnesota['Local/Visitante'] = Minnesota['Local/Visitante'].str.replace('vs', 'local').str.replace('en', 'visitante')
Minnesota['Equipo_Oponente'] = Minnesota['Oponente'].str.extract(r'(vs\.|en\s)([^,]+)')[1]
# Agregar las columnas "G," "P," y "E" basadas en la columna "Resultado_L"
Minnesota['G'] = (Minnesota['Resultado_L'] == 'G').astype(int)
Minnesota['P'] = (Minnesota['Resultado_L'] == 'P').astype(int)
Minnesota['E'] = (Minnesota['Resultado_L'] == 'E').astype(int)
columnas_deseadas = ['Equipo', 'Semana', 'Fecha', 'Resultado_L', 'R1', 'R2', 'Local/Visitante', 'Equipo_Oponente', 'G', 'P', 'E']
Minnesota_select = Minnesota[columnas_deseadas]
Minnesota_select.loc[:, ['Semana', 'R1', 'R2', 'G', 'P', 'E']] = Minnesota_select[['Semana', 'R1', 'R2', 'G', 'P', 'E']].astype(int)
Minnesota_select = Minnesota_select.copy()
Minnesota_select['Diferencia_Pts.'] = Minnesota_select['R1'] - Minnesota_select['R2']

In [189]:
Minnesota_select

,Equipo,Semana,Fecha,Resultado_L,R1,R2,Local/Visitante,Equipo_Oponente,G,P,E,Diferencia_Pts.
0,Minnesota,1,"Dom., 10 de Sep.",P,20,17,local,Tampa Bay,0,1,0,3
1,Minnesota,2,"Jue., 14 de Sep.",P,34,28,visitante,Philadelphia,0,1,0,6
2,Minnesota,3,"Dom., 24 de Sep.",P,28,24,local,Los Angeles,0,1,0,4
3,Minnesota,4,"Dom., 1 de Oct.",G,21,13,visitante,Carolina,1,0,0,8
4,Minnesota,5,"Dom., 8 de Oct.",P,27,20,local,Kansas City,0,1,0,7
5,Minnesota,6,"Dom., 15 de Oct.",G,19,13,visitante,Chicago,1,0,0,6
6,Minnesota,7,"Lun., 23 de Oct.",G,22,17,local,San Francisco,1,0,0,5
7,Minnesota,8,"Dom., 29 de Oct.",G,24,10,visitante,Green Bay,1,0,0,14

In [190]:
rAri = requests.get(urlAri, cookies=cookies, headers=headers)
html_contentsAri = rAri.text

In [191]:
html_soupAri = BeautifulSoup(html_contentsAri, 'html.parser')

In [192]:
calendarioAri = html_soupAri.find_all('table', class_='Table')

In [193]:
Arizona  = pd.DataFrame(columns = TabGen)

In [194]:
for table in calendarioAri:
    for row in table.find_all('tr')[2:21]:
        values = []
        for col in row.find_all(['th','td']):
            values.append(col.text)
        if len(values) == len(TabGen):
            Arizona.loc[len(Arizona)] = values

In [195]:
Arizona.insert(0, 'Equipo', 'Arizona')
Arizona['Resultado_L'] = Arizona['Resultado'].str.extract(r'([A-Za-z]+)')
Arizona['Resultado_Numeros'] = Arizona['Resultado'].str.extract(r'(\d+-\d+)')
Arizona[['R1', 'R2']] = Arizona['Resultado_Numeros'].str.split('-', expand=True)
Arizona['Local/Visitante'] = Arizona['Oponente'].str.split().str[0].str.replace('.', '')
Arizona['Local/Visitante'] = Arizona['Local/Visitante'].str.replace('vs', 'local').str.replace('en', 'visitante')
Arizona['Equipo_Oponente'] = Arizona['Oponente'].str.extract(r'(vs\.|en\s)([^,]+)')[1]
# Agregar las columnas "G," "P," y "E" basadas en la columna "Resultado_L"
Arizona['G'] = (Arizona['Resultado_L'] == 'G').astype(int)
Arizona['P'] = (Arizona['Resultado_L'] == 'P').astype(int)
Arizona['E'] = (Arizona['Resultado_L'] == 'E').astype(int)
columnas_deseadas = ['Equipo', 'Semana', 'Fecha', 'Resultado_L', 'R1', 'R2', 'Local/Visitante', 'Equipo_Oponente', 'G', 'P', 'E']
Arizona_select = Arizona[columnas_deseadas]
Arizona_select.loc[:, ['Semana', 'R1', 'R2', 'G', 'P', 'E']] = Arizona_select[['Semana', 'R1', 'R2', 'G', 'P', 'E']].astype(int)
Arizona_select = Arizona_select.copy()
Arizona_select['Diferencia_Pts.'] = Arizona_select['R1'] - Arizona_select['R2']

In [196]:
Arizona_select

,Equipo,Semana,Fecha,Resultado_L,R1,R2,Local/Visitante,Equipo_Oponente,G,P,E,Diferencia_Pts.
0,Arizona,1,"Dom., 10 de Sep.",P,20,16,visitante,Washington,0,1,0,4
1,Arizona,2,"Dom., 17 de Sep.",P,31,28,local,New York,0,1,0,3
2,Arizona,3,"Dom., 24 de Sep.",G,28,16,local,Dallas,1,0,0,12
3,Arizona,4,"Dom., 1 de Oct.",P,35,16,visitante,San Francisco,0,1,0,19
4,Arizona,5,"Dom., 8 de Oct.",P,34,20,local,Cincinnati,0,1,0,14
5,Arizona,6,"Dom., 15 de Oct.",P,26,9,visitante,Los Angeles,0,1,0,17
6,Arizona,7,"Dom., 22 de Oct.",P,20,10,visitante,Seattle,0,1,0,10
7,Arizona,8,"Dom., 29 de Oct.",P,31,24,local,Baltimore,0,1,0,7

In [197]:
rBuf = requests.get(urlBuf, cookies=cookies, headers=headers)
html_contentsBuf = rBuf.text

In [198]:
html_soupBuf = BeautifulSoup(html_contentsBuf, 'html.parser')

In [199]:
calendarioBuf = html_soupBuf.find_all('table', class_='Table')

In [200]:
Buffalo  = pd.DataFrame(columns = TabGen)

In [201]:
for table in calendarioBuf:
    for row in table.find_all('tr')[2:21]:
        values = []
        for col in row.find_all(['th','td']):
            values.append(col.text)
        if len(values) == len(TabGen):
            Buffalo.loc[len(Buffalo)] = values

In [202]:
Buffalo.insert(0, 'Equipo', 'Buffalo')
Buffalo['Resultado_L'] = Buffalo['Resultado'].str.extract(r'([A-Za-z]+)')
Buffalo['Resultado_Numeros'] = Buffalo['Resultado'].str.extract(r'(\d+-\d+)')
Buffalo[['R1', 'R2']] = Buffalo['Resultado_Numeros'].str.split('-', expand=True)
Buffalo['Local/Visitante'] = Buffalo['Oponente'].str.split().str[0].str.replace('.', '')
Buffalo['Local/Visitante'] = Buffalo['Local/Visitante'].str.replace('vs', 'local').str.replace('en', 'visitante')
Buffalo['Equipo_Oponente'] = Buffalo['Oponente'].str.extract(r'(vs\.|en\s)([^,]+)')[1]
# Agregar las columnas "G," "P," y "E" basadas en la columna "Resultado_L"
Buffalo['G'] = (Buffalo['Resultado_L'] == 'G').astype(int)
Buffalo['P'] = (Buffalo['Resultado_L'] == 'P').astype(int)
Buffalo['E'] = (Buffalo['Resultado_L'] == 'E').astype(int)
columnas_deseadas = ['Equipo', 'Semana', 'Fecha', 'Resultado_L', 'R1', 'R2', 'Local/Visitante', 'Equipo_Oponente', 'G', 'P', 'E']
Buffalo_select = Buffalo[columnas_deseadas]
Buffalo_select.loc[:, ['Semana', 'R1', 'R2', 'G', 'P', 'E']] = Buffalo_select[['Semana', 'R1', 'R2', 'G', 'P', 'E']].astype(int)
Buffalo_select = Buffalo_select.copy()
Buffalo_select['Diferencia_Pts.'] = Buffalo_select['R1'] - Buffalo_select['R2']

In [203]:
Buffalo_select

,Equipo,Semana,Fecha,Resultado_L,R1,R2,Local/Visitante,Equipo_Oponente,G,P,E,Diferencia_Pts.
0,Buffalo,1,"Lun., 11 de Sep.",P,22,16,visitante,New York,0,1,0,6
1,Buffalo,2,"Dom., 17 de Sep.",G,38,10,local,Las Vegas,1,0,0,28
2,Buffalo,3,"Dom., 24 de Sep.",G,37,3,visitante,Washington,1,0,0,34
3,Buffalo,4,"Dom., 1 de Oct.",G,48,20,local,Miami,1,0,0,28
4,Buffalo,5,"Dom., 8 de Oct.",P,25,20,local,Jacksonville *,0,1,0,5
5,Buffalo,6,"Dom., 15 de Oct.",G,14,9,local,New York,1,0,0,5
6,Buffalo,7,"Dom., 22 de Oct.",P,29,25,visitante,New England,0,1,0,4
7,Buffalo,8,"Jue., 26 de Oct.",G,24,18,local,Tampa Bay,1,0,0,6

In [204]:
rDen = requests.get(urlDen, cookies=cookies, headers=headers)
html_contentsDen = rDen.text

In [205]:
html_soupDen = BeautifulSoup(html_contentsDen, 'html.parser')

In [206]:
calendarioDen = html_soupDen.find_all('table', class_='Table')

In [207]:
Denver  = pd.DataFrame(columns = TabGen)

In [208]:
for table in calendarioDen:
    for row in table.find_all('tr')[2:21]:
        values = []
        for col in row.find_all(['th','td']):
            values.append(col.text)
        if len(values) == len(TabGen):
            Denver.loc[len(Denver)] = values

In [209]:
Denver.insert(0, 'Equipo', 'Denver')
Denver['Resultado_L'] = Denver['Resultado'].str.extract(r'([A-Za-z]+)')
Denver['Resultado_Numeros'] = Denver['Resultado'].str.extract(r'(\d+-\d+)')
Denver[['R1', 'R2']] = Denver['Resultado_Numeros'].str.split('-', expand=True)
Denver['Local/Visitante'] = Denver['Oponente'].str.split().str[0].str.replace('.', '')
Denver['Local/Visitante'] = Denver['Local/Visitante'].str.replace('vs', 'local').str.replace('en', 'visitante')
Denver['Equipo_Oponente'] = Denver['Oponente'].str.extract(r'(vs\.|en\s)([^,]+)')[1]
# Agregar las columnas "G," "P," y "E" basadas en la columna "Resultado_L"
Denver['G'] = (Denver['Resultado_L'] == 'G').astype(int)
Denver['P'] = (Denver['Resultado_L'] == 'P').astype(int)
Denver['E'] = (Denver['Resultado_L'] == 'E').astype(int)
columnas_deseadas = ['Equipo', 'Semana', 'Fecha', 'Resultado_L', 'R1', 'R2', 'Local/Visitante', 'Equipo_Oponente', 'G', 'P', 'E']
Denver_select = Denver[columnas_deseadas]
Denver_select.loc[:, ['Semana', 'R1', 'R2', 'G', 'P', 'E']] = Denver_select[['Semana', 'R1', 'R2', 'G', 'P', 'E']].astype(int)
Denver_select = Denver_select.copy()
Denver_select['Diferencia_Pts.'] = Denver_select['R1'] - Denver_select['R2']

In [210]:
Denver_select

,Equipo,Semana,Fecha,Resultado_L,R1,R2,Local/Visitante,Equipo_Oponente,G,P,E,Diferencia_Pts.
0,Denver,1,"Dom., 10 de Sep.",P,17,16,local,Las Vegas,0,1,0,1
1,Denver,2,"Dom., 17 de Sep.",P,35,33,local,Washington,0,1,0,2
2,Denver,3,"Dom., 24 de Sep.",P,70,20,visitante,Miami,0,1,0,50
3,Denver,4,"Dom., 1 de Oct.",G,31,28,visitante,Chicago,1,0,0,3
4,Denver,5,"Dom., 8 de Oct.",P,31,21,local,New York,0,1,0,10
5,Denver,6,"Jue., 12 de Oct.",P,19,8,visitante,Kansas City,0,1,0,11
6,Denver,7,"Dom., 22 de Oct.",G,19,17,local,Green Bay,1,0,0,2
7,Denver,8,"Dom., 29 de Oct.",G,24,9,local,Kansas City,1,0,0,15

In [211]:
rTen = requests.get(urlTen, cookies=cookies, headers=headers)
html_contentsTen = rTen.text

In [212]:
html_soupTen = BeautifulSoup(html_contentsTen, 'html.parser')

In [213]:
calendarioTen = html_soupTen.find_all('table', class_='Table')

In [214]:
Tennessee  = pd.DataFrame(columns = TabGen)

In [215]:
for table in calendarioTen:
    for row in table.find_all('tr')[2:21]:
        values = []
        for col in row.find_all(['th','td']):
            values.append(col.text)
        if len(values) == len(TabGen):
            Tennessee.loc[len(Tennessee)] = values

In [216]:
Tennessee.insert(0, 'Equipo', 'Tennessee')
Tennessee['Resultado_L'] = Tennessee['Resultado'].str.extract(r'([A-Za-z]+)')
Tennessee['Resultado_Numeros'] = Tennessee['Resultado'].str.extract(r'(\d+-\d+)')
Tennessee[['R1', 'R2']] = Tennessee['Resultado_Numeros'].str.split('-', expand=True)
Tennessee['Local/Visitante'] = Tennessee['Oponente'].str.split().str[0].str.replace('.', '')
Tennessee['Local/Visitante'] = Tennessee['Local/Visitante'].str.replace('vs', 'local').str.replace('en', 'visitante')
Tennessee['Equipo_Oponente'] = Tennessee['Oponente'].str.extract(r'(vs\.|en\s)([^,]+)')[1]
# Agregar las columnas "G," "P," y "E" basadas en la columna "Resultado_L"
Tennessee['G'] = (Tennessee['Resultado_L'] == 'G').astype(int)
Tennessee['P'] = (Tennessee['Resultado_L'] == 'P').astype(int)
Tennessee['E'] = (Tennessee['Resultado_L'] == 'E').astype(int)
columnas_deseadas = ['Equipo', 'Semana', 'Fecha', 'Resultado_L', 'R1', 'R2', 'Local/Visitante', 'Equipo_Oponente', 'G', 'P', 'E']
Tennessee_select = Tennessee[columnas_deseadas]
Tennessee_select.loc[:, ['Semana', 'R1', 'R2', 'G', 'P', 'E']] = Tennessee_select[['Semana', 'R1', 'R2', 'G', 'P', 'E']].astype(int)
Tennessee_select = Tennessee_select.copy()
Tennessee_select['Diferencia_Pts.'] = Tennessee_select['R1'] - Tennessee_select['R2']

In [217]:
Tennessee_select

,Equipo,Semana,Fecha,Resultado_L,R1,R2,Local/Visitante,Equipo_Oponente,G,P,E,Diferencia_Pts.
0,Tennessee,1,"Dom., 10 de Sep.",P,16,15,visitante,New Orleans,0,1,0,1
1,Tennessee,2,"Dom., 17 de Sep.",G,27,24,local,Los Angeles,1,0,0,3
2,Tennessee,3,"Dom., 24 de Sep.",P,27,3,visitante,Cleveland,0,1,0,24
3,Tennessee,4,"Dom., 1 de Oct.",G,27,3,local,Cincinnati,1,0,0,24
4,Tennessee,5,"Dom., 8 de Oct.",P,23,16,visitante,Indianapolis,0,1,0,7
5,Tennessee,6,"Dom., 15 de Oct.",P,24,16,local,Baltimore *,0,1,0,8
6,Tennessee,8,"Dom., 29 de Oct.",G,28,23,local,Atlanta,1,0,0,5

In [218]:
rSea = requests.get(urlSea, cookies=cookies, headers=headers)
html_contentsSea = rSea.text

In [219]:
html_soupSea = BeautifulSoup(html_contentsSea, 'html.parser')

In [220]:
calendarioSea = html_soupSea.find_all('table', class_='Table')

In [221]:
Seattle  = pd.DataFrame(columns = TabGen)

In [222]:
for table in calendarioSea:
    for row in table.find_all('tr')[2:21]:
        values = []
        for col in row.find_all(['th','td']):
            values.append(col.text)
        if len(values) == len(TabGen):
            Seattle.loc[len(Seattle)] = values

In [223]:
Seattle.insert(0, 'Equipo', 'Seattle')
Seattle['Resultado_L'] = Seattle['Resultado'].str.extract(r'([A-Za-z]+)')
Seattle['Resultado_Numeros'] = Seattle['Resultado'].str.extract(r'(\d+-\d+)')
Seattle[['R1', 'R2']] = Seattle['Resultado_Numeros'].str.split('-', expand=True)
Seattle['Local/Visitante'] = Seattle['Oponente'].str.split().str[0].str.replace('.', '')
Seattle['Local/Visitante'] = Seattle['Local/Visitante'].str.replace('vs', 'local').str.replace('en', 'visitante')
Seattle['Equipo_Oponente'] = Seattle['Oponente'].str.extract(r'(vs\.|en\s)([^,]+)')[1]
# Agregar las columnas "G," "P," y "E" basadas en la columna "Resultado_L"
Seattle['G'] = (Seattle['Resultado_L'] == 'G').astype(int)
Seattle['P'] = (Seattle['Resultado_L'] == 'P').astype(int)
Seattle['E'] = (Seattle['Resultado_L'] == 'E').astype(int)
columnas_deseadas = ['Equipo', 'Semana', 'Fecha', 'Resultado_L', 'R1', 'R2', 'Local/Visitante', 'Equipo_Oponente', 'G', 'P', 'E']
Seattle_select = Seattle[columnas_deseadas]
Seattle_select.loc[:, ['Semana', 'R1', 'R2', 'G', 'P', 'E']] = Seattle_select[['Semana', 'R1', 'R2', 'G', 'P', 'E']].astype(int)
Seattle_select = Seattle_select.copy()
Seattle_select['Diferencia_Pts.'] = Seattle_select['R1'] - Seattle_select['R2']

In [224]:
Seattle_select

,Equipo,Semana,Fecha,Resultado_L,R1,R2,Local/Visitante,Equipo_Oponente,G,P,E,Diferencia_Pts.
0,Seattle,1,"Dom., 10 de Sep.",P,30,13,local,Los Angeles,0,1,0,17
1,Seattle,2,"Dom., 17 de Sep.",G,37,31,visitante,Detroit,1,0,0,6
2,Seattle,3,"Dom., 24 de Sep.",G,37,27,local,Carolina,1,0,0,10
3,Seattle,4,"Lun., 2 de Oct.",G,24,3,visitante,New York,1,0,0,21
4,Seattle,6,"Dom., 15 de Oct.",P,17,13,visitante,Cincinnati,0,1,0,4
5,Seattle,7,"Dom., 22 de Oct.",G,20,10,local,Arizona,1,0,0,10
6,Seattle,8,"Dom., 29 de Oct.",G,24,20,local,Cleveland,1,0,0,4

In [225]:
rCar = requests.get(urlCar, cookies=cookies, headers=headers)
html_contentsCar = rCar.text

In [226]:
html_soupCar = BeautifulSoup(html_contentsCar, 'html.parser')

In [227]:
calendarioCar = html_soupCar.find_all('table', class_='Table')

In [228]:
Carolina   = pd.DataFrame(columns = TabGen)

In [229]:
for table in calendarioCar:
    for row in table.find_all('tr')[2:21]:
        values = []
        for col in row.find_all(['th','td']):
            values.append(col.text)
        if len(values) == len(TabGen):
            Carolina.loc[len(Carolina)] = values

In [230]:
Carolina.insert(0, 'Equipo', 'Carolina')
Carolina['Resultado_L'] = Carolina['Resultado'].str.extract(r'([A-Za-z]+)')
Carolina['Resultado_Numeros'] = Carolina['Resultado'].str.extract(r'(\d+-\d+)')
Carolina[['R1', 'R2']] = Carolina['Resultado_Numeros'].str.split('-', expand=True)
Carolina['Local/Visitante'] = Carolina['Oponente'].str.split().str[0].str.replace('.', '')
Carolina['Local/Visitante'] = Carolina['Local/Visitante'].str.replace('vs', 'local').str.replace('en', 'visitante')
Carolina['Equipo_Oponente'] = Carolina['Oponente'].str.extract(r'(vs\.|en\s)([^,]+)')[1]
# Agregar las columnas "G," "P," y "E" basadas en la columna "Resultado_L"
Carolina['G'] = (Carolina['Resultado_L'] == 'G').astype(int)
Carolina['P'] = (Carolina['Resultado_L'] == 'P').astype(int)
Carolina['E'] = (Carolina['Resultado_L'] == 'E').astype(int)
columnas_deseadas = ['Equipo', 'Semana', 'Fecha', 'Resultado_L', 'R1', 'R2', 'Local/Visitante', 'Equipo_Oponente', 'G', 'P', 'E']
Carolina_select = Carolina[columnas_deseadas]
Carolina_select.loc[:, ['Semana', 'R1', 'R2', 'G', 'P', 'E']] = Carolina_select[['Semana', 'R1', 'R2', 'G', 'P', 'E']].astype(int)
Carolina_select = Carolina_select.copy()
Carolina_select['Diferencia_Pts.'] = Carolina_select['R1'] - Carolina_select['R2']

In [231]:
Carolina_select

,Equipo,Semana,Fecha,Resultado_L,R1,R2,Local/Visitante,Equipo_Oponente,G,P,E,Diferencia_Pts.
0,Carolina,1,"Dom., 10 de Sep.",P,24,10,visitante,Atlanta,0,1,0,14
1,Carolina,2,"Lun., 18 de Sep.",P,20,17,local,New Orleans,0,1,0,3
2,Carolina,3,"Dom., 24 de Sep.",P,37,27,visitante,Seattle,0,1,0,10
3,Carolina,4,"Dom., 1 de Oct.",P,21,13,local,Minnesota,0,1,0,8
4,Carolina,5,"Dom., 8 de Oct.",P,42,24,visitante,Detroit,0,1,0,18
5,Carolina,6,"Dom., 15 de Oct.",P,42,21,visitante,Miami,0,1,0,21
6,Carolina,8,"Dom., 29 de Oct.",G,15,13,local,Houston,1,0,0,2

In [232]:
rHou = requests.get(urlHou, cookies=cookies, headers=headers)
html_contentsHou = rHou.text

In [233]:
html_soupHou = BeautifulSoup(html_contentsHou, 'html.parser')

In [234]:
calendarioHou = html_soupHou.find_all('table', class_='Table')

In [235]:
Houston = pd.DataFrame(columns = TabGen)

In [236]:
for table in calendarioHou:
    for row in table.find_all('tr')[2:21]:
        values = []
        for col in row.find_all(['th','td']):
            values.append(col.text)
        if len(values) == len(TabGen):
            Houston.loc[len(Houston)] = values

In [237]:
Houston.insert(0, 'Equipo', 'Houston')
Houston['Resultado_L'] = Houston['Resultado'].str.extract(r'([A-Za-z]+)')
Houston['Resultado_Numeros'] = Houston['Resultado'].str.extract(r'(\d+-\d+)')
Houston[['R1', 'R2']] = Houston['Resultado_Numeros'].str.split('-', expand=True)
Houston['Local/Visitante'] = Houston['Oponente'].str.split().str[0].str.replace('.', '')
Houston['Local/Visitante'] = Houston['Local/Visitante'].str.replace('vs', 'local').str.replace('en', 'visitante')
Houston['Equipo_Oponente'] = Houston['Oponente'].str.extract(r'(vs\.|en\s)([^,]+)')[1]
# Agregar las columnas "G," "P," y "E" basadas en la columna "Resultado_L"
Houston['G'] = (Houston['Resultado_L'] == 'G').astype(int)
Houston['P'] = (Houston['Resultado_L'] == 'P').astype(int)
Houston['E'] = (Houston['Resultado_L'] == 'E').astype(int)
columnas_deseadas = ['Equipo', 'Semana', 'Fecha', 'Resultado_L', 'R1', 'R2', 'Local/Visitante', 'Equipo_Oponente', 'G', 'P', 'E']
Houston_select = Houston[columnas_deseadas]
Houston_select.loc[:, ['Semana', 'R1', 'R2', 'G', 'P', 'E']] = Houston_select[['Semana', 'R1', 'R2', 'G', 'P', 'E']].astype(int)
Houston_select = Houston_select.copy()
Houston_select['Diferencia_Pts.'] = Houston_select['R1'] - Houston_select['R2']

In [238]:
Houston_select

,Equipo,Semana,Fecha,Resultado_L,R1,R2,Local/Visitante,Equipo_Oponente,G,P,E,Diferencia_Pts.
0,Houston,1,"Dom., 10 de Sep.",P,25,9,visitante,Baltimore,0,1,0,16
1,Houston,2,"Dom., 17 de Sep.",P,31,20,local,Indianapolis,0,1,0,11
2,Houston,3,"Dom., 24 de Sep.",G,37,17,visitante,Jacksonville,1,0,0,20
3,Houston,4,"Dom., 1 de Oct.",G,30,6,local,Pittsburgh,1,0,0,24
4,Houston,5,"Dom., 8 de Oct.",P,21,19,visitante,Atlanta,0,1,0,2
5,Houston,6,"Dom., 15 de Oct.",G,20,13,local,New Orleans,1,0,0,7
6,Houston,8,"Dom., 29 de Oct.",P,15,13,visitante,Carolina,0,1,0,2

In [239]:
rPit = requests.get(urlPit, cookies=cookies, headers=headers)
html_contentsPit = rPit.text

In [240]:
html_soupPit = BeautifulSoup(html_contentsPit, 'html.parser')

In [241]:
calendarioPit = html_soupPit.find_all('table', class_='Table')

In [242]:
Pittsburgh  = pd.DataFrame(columns = TabGen)

In [243]:
for table in calendarioPit:
    for row in table.find_all('tr')[2:21]:
        values = []
        for col in row.find_all(['th','td']):
            values.append(col.text)
        if len(values) == len(TabGen):
            Pittsburgh.loc[len(Pittsburgh)] = values

In [244]:
Pittsburgh.insert(0, 'Equipo', 'Pittsburgh')
Pittsburgh['Resultado_L'] = Pittsburgh['Resultado'].str.extract(r'([A-Za-z]+)')
Pittsburgh['Resultado_Numeros'] = Pittsburgh['Resultado'].str.extract(r'(\d+-\d+)')
Pittsburgh[['R1', 'R2']] = Pittsburgh['Resultado_Numeros'].str.split('-', expand=True)
Pittsburgh['Local/Visitante'] = Pittsburgh['Oponente'].str.split().str[0].str.replace('.', '')
Pittsburgh['Local/Visitante'] = Pittsburgh['Local/Visitante'].str.replace('vs', 'local').str.replace('en', 'visitante')
Pittsburgh['Equipo_Oponente'] = Pittsburgh['Oponente'].str.extract(r'(vs\.|en\s)([^,]+)')[1]
# Agregar las columnas "G," "P," y "E" basadas en la columna "Resultado_L"
Pittsburgh['G'] = (Pittsburgh['Resultado_L'] == 'G').astype(int)
Pittsburgh['P'] = (Pittsburgh['Resultado_L'] == 'P').astype(int)
Pittsburgh['E'] = (Pittsburgh['Resultado_L'] == 'E').astype(int)
columnas_deseadas = ['Equipo', 'Semana', 'Fecha', 'Resultado_L', 'R1', 'R2', 'Local/Visitante', 'Equipo_Oponente', 'G', 'P', 'E']
Pittsburgh_select = Pittsburgh[columnas_deseadas]
Pittsburgh_select.loc[:, ['Semana', 'R1', 'R2', 'G', 'P', 'E']] = Pittsburgh_select[['Semana', 'R1', 'R2', 'G', 'P', 'E']].astype(int)
Pittsburgh_select = Pittsburgh_select.copy()
Pittsburgh_select['Diferencia_Pts.'] = Pittsburgh_select['R1'] - Pittsburgh_select['R2']

In [245]:
Pittsburgh_select

,Equipo,Semana,Fecha,Resultado_L,R1,R2,Local/Visitante,Equipo_Oponente,G,P,E,Diferencia_Pts.
0,Pittsburgh,1,"Dom., 10 de Sep.",P,30,7,local,San Francisco,0,1,0,23
1,Pittsburgh,2,"Lun., 18 de Sep.",G,26,22,local,Cleveland,1,0,0,4
2,Pittsburgh,3,"Dom., 24 de Sep.",G,23,18,visitante,Las Vegas,1,0,0,5
3,Pittsburgh,4,"Dom., 1 de Oct.",P,30,6,visitante,Houston,0,1,0,24
4,Pittsburgh,5,"Dom., 8 de Oct.",G,17,10,local,Baltimore,1,0,0,7
5,Pittsburgh,7,"Dom., 22 de Oct.",G,24,17,visitante,Los Angeles,1,0,0,7
6,Pittsburgh,8,"Dom., 29 de Oct.",P,20,10,local,Jacksonville,0,1,0,10

In [246]:
rCin = requests.get(urlCin, cookies=cookies, headers=headers)
html_contentsCin = rCin.text

In [247]:
html_soupCin = BeautifulSoup(html_contentsCin, 'html.parser')

In [248]:
calendarioCin = html_soupCin.find_all('table', class_='Table')

In [249]:
Cincinnati = pd.DataFrame(columns = TabGen)

In [250]:
for table in calendarioCin:
    for row in table.find_all('tr')[2:21]:
        values = []
        for col in row.find_all(['th','td']):
            values.append(col.text)
        if len(values) == len(TabGen):
            Cincinnati.loc[len(Cincinnati)] = values

In [251]:
Cincinnati.insert(0, 'Equipo', 'Cincinnati')
Cincinnati['Resultado_L'] = Cincinnati['Resultado'].str.extract(r'([A-Za-z]+)')
Cincinnati['Resultado_Numeros'] = Cincinnati['Resultado'].str.extract(r'(\d+-\d+)')
Cincinnati[['R1', 'R2']] = Cincinnati['Resultado_Numeros'].str.split('-', expand=True)
Cincinnati['Local/Visitante'] = Cincinnati['Oponente'].str.split().str[0].str.replace('.', '')
Cincinnati['Local/Visitante'] = Cincinnati['Local/Visitante'].str.replace('vs', 'local').str.replace('en', 'visitante')
Cincinnati['Equipo_Oponente'] = Cincinnati['Oponente'].str.extract(r'(vs\.|en\s)([^,]+)')[1]
# Agregar las columnas "G," "P," y "E" basadas en la columna "Resultado_L"
Cincinnati['G'] = (Cincinnati['Resultado_L'] == 'G').astype(int)
Cincinnati['P'] = (Cincinnati['Resultado_L'] == 'P').astype(int)
Cincinnati['E'] = (Cincinnati['Resultado_L'] == 'E').astype(int)
columnas_deseadas = ['Equipo', 'Semana', 'Fecha', 'Resultado_L', 'R1', 'R2', 'Local/Visitante', 'Equipo_Oponente', 'G', 'P', 'E']
Cincinnati_select = Cincinnati[columnas_deseadas]
Cincinnati_select.loc[:, ['Semana', 'R1', 'R2', 'G', 'P', 'E']] = Cincinnati_select[['Semana', 'R1', 'R2', 'G', 'P', 'E']].astype(int)
Cincinnati_select = Cincinnati_select.copy()
Cincinnati_select['Diferencia_Pts.'] = Cincinnati_select['R1'] - Cincinnati_select['R2']

In [252]:
Cincinnati_select

,Equipo,Semana,Fecha,Resultado_L,R1,R2,Local/Visitante,Equipo_Oponente,G,P,E,Diferencia_Pts.
0,Cincinnati,1,"Dom., 10 de Sep.",P,24,3,visitante,Cleveland,0,1,0,21
1,Cincinnati,2,"Dom., 17 de Sep.",P,27,24,local,Baltimore,0,1,0,3
2,Cincinnati,3,"Lun., 25 de Sep.",G,19,16,local,Los Angeles,1,0,0,3
3,Cincinnati,4,"Dom., 1 de Oct.",P,27,3,visitante,Tennessee,0,1,0,24
4,Cincinnati,5,"Dom., 8 de Oct.",G,34,20,visitante,Arizona,1,0,0,14
5,Cincinnati,6,"Dom., 15 de Oct.",G,17,13,local,Seattle,1,0,0,4
6,Cincinnati,8,"Dom., 29 de Oct.",G,31,17,visitante,San Francisco,1,0,0,14

In [253]:
rNyg = requests.get(urlNyg, cookies=cookies, headers=headers)
html_contentsNyg = rNyg.text

In [254]:
html_soupNyg = BeautifulSoup(html_contentsNyg, 'html.parser')

In [255]:
calendarioNyg = html_soupNyg.find_all('table', class_='Table')

In [256]:
New_York_Giants = pd.DataFrame(columns = TabGen)

In [257]:
for table in calendarioNyg:
    for row in table.find_all('tr')[2:21]:
        values = []
        for col in row.find_all(['th','td']):
            values.append(col.text)
        if len(values) == len(TabGen):
            New_York_Giants.loc[len(New_York_Giants)] = values

In [258]:
New_York_Giants

,Semana,Fecha,Oponente,Resultado,G-P,L.Pases,L. Corr,L. Recib
0,1,"Dom., 10 de Sep.",vs. Dallas,P40-0,0-1,Jones 104,Barkley 51,Waller 36
1,2,"Dom., 17 de Sep.",en Arizona,G31-28,1-1,Jones 321,Barkley 63,Hyatt 89
2,3,"Jue., 21 de Sep.",en San Francisco,P30-12,1-2,Jones 137,Breida 17,Slayton 32
3,4,"Lun., 2 de Oct.",vs. Seattle,P24-3,1-3,Jones 203,Jones 66,Breida 48
4,5,"Dom., 8 de Oct.",en Miami,P31-16,1-4,Jones 119,Gray 25,Waller 86
5,6,"Dom., 15 de Oct.",en Buffalo,P14-9,1-5,Taylor 200,Barkley 93,Slayton 69
6,7,"Dom., 22 de Oct.",vs. Washington,G14-7,2-5,Taylor 279,Barkley 77,Waller 98
7,8,"Dom., 29 de Oct.",vs. New York,P13-10 TE,2-6,Taylor 8,Barkley 128,Waller 4

In [259]:
New_York_Giants.insert(0, 'Equipo', 'New York Giants')
New_York_Giants['Resultado_L'] = New_York_Giants['Resultado'].str.extract(r'([A-Za-z]+)')
New_York_Giants['Resultado_Numeros'] = New_York_Giants['Resultado'].str.extract(r'(\d+-\d+)')
New_York_Giants[['R1', 'R2']] = New_York_Giants['Resultado_Numeros'].str.split('-', expand=True)
New_York_Giants['Local/Visitante'] = New_York_Giants['Oponente'].str.split().str[0].str.replace('.', '')
New_York_Giants['Local/Visitante'] = New_York_Giants['Local/Visitante'].str.replace('vs', 'local').str.replace('en', 'visitante')
New_York_Giants['Equipo_Oponente'] = New_York_Giants['Oponente'].str.extract(r'(vs\.|en\s)([^,]+)')[1]
# Agregar las columnas "G," "P," y "E" basadas en la columna "Resultado_L"
New_York_Giants['G'] = (New_York_Giants['Resultado_L'] == 'G').astype(int)
New_York_Giants['P'] = (New_York_Giants['Resultado_L'] == 'P').astype(int)
New_York_Giants['E'] = (New_York_Giants['Resultado_L'] == 'E').astype(int)
columnas_deseadas = ['Equipo', 'Semana', 'Fecha', 'Resultado_L', 'R1', 'R2', 'Local/Visitante', 'Equipo_Oponente', 'G', 'P', 'E']
New_York_Giants_select = New_York_Giants[columnas_deseadas]
New_York_Giants_select.loc[:, ['Semana', 'R1', 'R2', 'G', 'P', 'E']] = New_York_Giants_select[['Semana', 'R1', 'R2', 'G', 'P', 'E']].astype(int)
New_York_Giants_select = New_York_Giants_select.copy()
New_York_Giants_select['Diferencia_Pts.'] = New_York_Giants_select['R1'] - New_York_Giants_select['R2']

In [260]:
New_York_Giants

,Equipo,Semana,Fecha,Oponente,Resultado,G-P,L.Pases,L. Corr,L. Recib,Resultado_L,Resultado_Numeros,R1,R2,Local/Visitante,Equipo_Oponente,G,P,E
0,New York Giants,1,"Dom., 10 de Sep.",vs. Dallas,P40-0,0-1,Jones 104,Barkley 51,Waller 36,P,40-0,40,0,local,Dallas,0,1,0
1,New York Giants,2,"Dom., 17 de Sep.",en Arizona,G31-28,1-1,Jones 321,Barkley 63,Hyatt 89,G,31-28,31,28,visitante,Arizona,1,0,0
2,New York Giants,3,"Jue., 21 de Sep.",en San Francisco,P30-12,1-2,Jones 137,Breida 17,Slayton 32,P,30-12,30,12,visitante,San Francisco,0,1,0
3,New York Giants,4,"Lun., 2 de Oct.",vs. Seattle,P24-3,1-3,Jones 203,Jones 66,Breida 48,P,24-3,24,3,local,Seattle,0,1,0
4,New York Giants,5,"Dom., 8 de Oct.",en Miami,P31-16,1-4,Jones 119,Gray 25,Waller 86,P,31-16,31,16,visitante,Miami,0,1,0
5,New York Giants,6,"Dom., 15 de Oct.",en Buffalo,P14-9,1-5,Taylor 200,Barkley 93,Slayton 69,P,14-9,14,9,visitante,Buffalo,0,1,0
6,New York Giants,7,"Dom., 22 de Oct.",vs. Washington,G14-7,2-5,Taylor 279,Barkley 77,Waller 98,G,14-7,14,7,local,Washington,1,0,0
7,New York Giants,8,"Dom., 29 de Oct.",vs. New York,P13-10 TE,2-6,Taylor 8,Barkley 128,Waller 4,P,13-10,13,10,local,New York,0,1,0

In [261]:
New_York_Giants_select

,Equipo,Semana,Fecha,Resultado_L,R1,R2,Local/Visitante,Equipo_Oponente,G,P,E,Diferencia_Pts.
0,New York Giants,1,"Dom., 10 de Sep.",P,40,0,local,Dallas,0,1,0,40
1,New York Giants,2,"Dom., 17 de Sep.",G,31,28,visitante,Arizona,1,0,0,3
2,New York Giants,3,"Jue., 21 de Sep.",P,30,12,visitante,San Francisco,0,1,0,18
3,New York Giants,4,"Lun., 2 de Oct.",P,24,3,local,Seattle,0,1,0,21
4,New York Giants,5,"Dom., 8 de Oct.",P,31,16,visitante,Miami,0,1,0,15
5,New York Giants,6,"Dom., 15 de Oct.",P,14,9,visitante,Buffalo,0,1,0,5
6,New York Giants,7,"Dom., 22 de Oct.",G,14,7,local,Washington,1,0,0,7
7,New York Giants,8,"Dom., 29 de Oct.",P,13,10,local,New York,0,1,0,3

In [262]:
New_York_Giants_select['P']

0    1
1    0
2    1
3    1
4    1
5    1
6    0
7    1
Name: P, dtype: int32

In [263]:
# Extraer la semana 1 de Dallas_select
week_1_DAL = Dallas_select[Dallas_select['Semana'] == 1]
# Extraer la semana 1 de Miami_select
week_1_MIA = Miami_select[Miami_select['Semana'] == 1]
# Extraer la semana 1 de San_Francisco_select
week_1_SF = San_Francisco_select[San_Francisco_select['Semana'] == 1]
# Extraer la semana 1 de Baltimore_Ravens_select
week_1_BAL = Baltimore_Ravens_select[Baltimore_Ravens_select['Semana'] == 1]
# Extraer la semana 1 de Atlanta_select
week_1_ATL = Atlanta_select[Atlanta_select['Semana'] == 1]
# Extraer la semana 1 de New_Orleans_select
week_1_NO = New_Orleans_select[New_Orleans_select['Semana'] == 1]
# Extraer la semana 1 de Tampa_Bay_select
week_1_TB = Tampa_Bay_select[Tampa_Bay_select['Semana'] == 1]
# Extraer la semana 1 de Philadelphia_select
week_1_PHI = Philadelphia_select[Philadelphia_select['Semana'] == 1]
# Extraer la semana 1 de Washington_select
week_1_WSH = Washington_select[Washington_select['Semana'] == 1]
# Extraer la semana 1 de Jacksonville_select
week_1_JAX = Jacksonville_select[Jacksonville_select['Semana'] == 1]
# Extraer la semana 1 de Green_Bay_select
week_1_GB = Green_Bay_select[Green_Bay_select['Semana'] == 1]
# Extraer la semana 1 de Las_Vegas_Raiders_select
week_1_LV = Las_Vegas_select[Las_Vegas_select['Semana'] == 1]
# Extraer la semana 1 de Pittsburgh_select
week_1_PIT = Pittsburgh_select[Pittsburgh_select['Semana'] == 1]
# Extraer la semana 1 de New_York_Jets_select
week_1_NYJ = New_York_Jets_select[New_York_Jets_select['Semana'] == 1]
# Extraer la semana 1 de Kansas_City_select
week_1_KC = Kansas_City_select[Kansas_City_select['Semana'] == 1]
# Extraer la semana 1 de Buffalo_select
week_1_BUF = Buffalo_select[Buffalo_select['Semana'] == 1]
# Extraer la semana 1 de Indianapolis_select
week_1_IND = Indianapolis_select[Indianapolis_select['Semana'] == 1]
# Extraer la semana 1 de Los_Angeles_Rams_select
week_1_LAR = Los_Angeles_Rams_select[Los_Angeles_Rams_select['Semana'] == 1]
# Extraer la semana 1 de Tennessee_select
week_1_TEN = Tennessee_select[Tennessee_select['Semana'] == 1]
# Extraer la semana 1 de Seattle_select
week_1_SEA = Seattle_select[Seattle_select['Semana'] == 1]
# Extraer la semana 1 de Cleveland_select
week_1_CLE = Cleveland_select[Cleveland_select['Semana'] == 1]
# Extraer la semana 1 de New_York_Giants_select
week_1_NYG = New_York_Giants_select[New_York_Giants_select['Semana'] == 1]
# Extraer la semana 1 de Detroit_select
week_1_DET = Detroit_select[Detroit_select['Semana'] == 1]
# Extraer la semana 1 de New_England_select
week_1_NE = New_England_select[New_England_select['Semana'] == 1]
# Extraer la semana 1 de Minnesota_select
week_1_MIN = Minnesota_select[Minnesota_select['Semana'] == 1]
# Extraer la semana 1 de Los_Angeles_Chargers_select
week_1_LAC = Los_Angeles_Chargers_select[Los_Angeles_Chargers_select['Semana'] == 1]
# Extraer la semana 1 de Carolina_select
week_1_CAR = Carolina_select[Carolina_select['Semana'] == 1]
# Extraer la semana 1 de Houston_select
week_1_HOU = Houston_select[Houston_select['Semana'] == 1]
# Extraer la semana 1 de Cincinnati_select
week_1_CIN = Cincinnati_select[Cincinnati_select['Semana'] == 1]
# Extraer la semana 1 de Arizona_select
week_1_ARI = Arizona_select[Arizona_select['Semana'] == 1]
# Extraer la semana 1 de Chicago_select
week_1_CHI = Chicago_select[Chicago_select['Semana'] == 1]
# Extraer la semana 1 de Denver_select
week_1_DEN = Denver_select[Denver_select['Semana'] == 1]


# Crear un nuevo DataFrame que contenga solo la semana 1 de ambas tablas
week_1_df = pd.concat([week_1_DAL, week_1_MIA, week_1_SF, week_1_BAL, week_1_ATL, week_1_NO, week_1_TB, week_1_PHI, week_1_WSH, week_1_JAX,
                       week_1_GB, week_1_LV, week_1_PIT, week_1_NYJ, week_1_KC, week_1_BUF, week_1_IND, week_1_LAR, week_1_TEN, week_1_SEA,
                       week_1_CLE, week_1_NYG, week_1_DET, week_1_NE, week_1_MIN, week_1_LAC, week_1_CAR, week_1_HOU, week_1_CIN, week_1_ARI, 
                       week_1_CHI, week_1_DEN], ignore_index=True)

In [264]:
week_1_df

,Equipo,Semana,Fecha,Resultado_L,R1,R2,Local/Visitante,Equipo_Oponente,G,P,E,Diferencia_Pts.
0,Dallas,1,"Dom., 10 de Sep.",G,40,0,visitante,New York,1,0,0,40
1,Miami,1,"Dom., 10 de Sep.",G,36,34,visitante,Los Angeles,1,0,0,2
2,San Francisco,1,"Dom., 10 de Sep.",G,30,7,visitante,Pittsburgh,1,0,0,23
3,Baltimore Ravens,1,"Dom., 10 de Sep.",G,25,9,local,Houston,1,0,0,16
4,Atlanta,1,"Dom., 10 de Sep.",G,24,10,local,Carolina,1,0,0,14
5,New Orleans,1,"Dom., 10 de Sep.",G,16,15,local,Tennessee,1,0,0,1
6,Tampa Bay,1,"Dom., 10 de Sep.",G,20,17,visitante,Minnesota,1,0,0,3
7,Philadelphia,1,"Dom., 10 de Sep.",G,25,20,visitante,New England,1,0,0,5
8,Washington,1,"Dom., 10 de Sep.",G,20,16,local,Arizona,1,0,0,4
9,Jacksonville,1,"Dom., 10 de Sep.",G,31,21,visitante,Indianapolis,1,0,0,10
10,Green Bay,1,"Dom., 10 de Sep.",G,38,20,visitante,Chicago,1,0,0,18
11,Las Vegas,1,"Dom., 10 de Sep.",G,17,16,visitante,Denver,1,0,0,1
12,Pittsburgh,1,"Dom., 10 de Sep.",P,30,7,local,San Francisco,0,1,0,23
13,New York Jets,1,"Lun., 11 de Sep.",G,22,16,local,Buffalo,1,0,0,6
14,Kansas City,1,"Jue., 7 de Sep.",P,21,20,local,Detroit,0,1,0,1
15,Buffalo,1,"Lun., 11 de Sep.",P,22,16,visitante,New York,0,1,0,6
16,Indianapolis,1,"Dom., 10 de Sep.",P,31,21,local,Jacksonville,0,1,0,10
17,Los Angeles Rams,1,"Dom., 10 de Sep.",G,30,13,visitante,Seattle,1,0,0,17
18,Tennessee,1,"Dom., 10 de Sep.",P,16,15,visitante,New Orleans,0,1,0,1
19,Seattle,1,"Dom., 10 de Sep.",P,30,13,local,Los Angeles,0,1,0,17
20,Cleveland,1,"Dom., 10 de Sep.",G,24,3,local,Cincinnati,1,0,0,21
21,New York Giants,1,"Dom., 10 de Sep.",P,40,0,local,Dallas,0,1,0,40
22,Detroit,1,"Jue., 7 de Sep.",G,21,20,visitante,Kansas City,1,0,0,1
23,New England,1,"Dom., 10 de Sep.",P,25,20,local,Philadelphia,0,1,0,5
24,Minnesota,1,"Dom., 10 de Sep.",P,20,17,local,Tampa Bay,0,1,0,3
25,Los Angeles Chargers,1,"Dom., 10 de Sep.",P,36,34,local,Miami,0,1,0,2
26,Carolina,1,"Dom., 10 de Sep.",P,24,10,visitante,Atlanta,0,1,0,14
27,Houston,1,"Dom., 10 de Sep.",P,25,9,visitante,Baltimore,0,1,0,16
28,Cincinnati,1,"Dom., 10 de Sep.",P,24,3,visitante,Cleveland,0,1,0,21
29,Arizona,1,"Dom., 10 de Sep.",P,20,16,visitante,Washington,0,1,0,4
30,Chicago,1,"Dom., 10 de Sep.",P,38,20,local,Green Bay,0,1,0,18
31,Denver,1,"Dom., 10 de Sep.",P,17,16,local,Las Vegas,0,1,0,1

In [265]:
# Extraer la semana 1 de Dallas_select
week_2_DAL = Dallas_select[Dallas_select['Semana'] == 2]
# Extraer la semana 1 de Miami_select
week_2_MIA = Miami_select[Miami_select['Semana'] == 2]
# Extraer la semana 1 de San_Francisco_select
week_2_SF = San_Francisco_select[San_Francisco_select['Semana'] == 2]
# Extraer la semana 1 de Baltimore_Ravens_select
week_2_BAL = Baltimore_Ravens_select[Baltimore_Ravens_select['Semana'] == 2]
# Extraer la semana 1 de Atlanta_select
week_2_ATL = Atlanta_select[Atlanta_select['Semana'] == 2]
# Extraer la semana 1 de New_Orleans_select
week_2_NO = New_Orleans_select[New_Orleans_select['Semana'] == 2]
# Extraer la semana 1 de Tampa_Bay_select
week_2_TB = Tampa_Bay_select[Tampa_Bay_select['Semana'] == 2]
# Extraer la semana 1 de Philadelphia_select
week_2_PHI = Philadelphia_select[Philadelphia_select['Semana'] == 2]
# Extraer la semana 1 de Washington_select
week_2_WSH = Washington_select[Washington_select['Semana'] == 2]
# Extraer la semana 1 de Jacksonville_select
week_2_JAX = Jacksonville_select[Jacksonville_select['Semana'] == 2]
# Extraer la semana 1 de Green_Bay_select
week_2_GB = Green_Bay_select[Green_Bay_select['Semana'] == 2]
# Extraer la semana 1 de Las_Vegas_Raiders_select
week_2_LV = Las_Vegas_select[Las_Vegas_select['Semana'] == 2]
# Extraer la semana 1 de Pittsburgh_select
week_2_PIT = Pittsburgh_select[Pittsburgh_select['Semana'] == 2]
# Extraer la semana 1 de New_York_Jets_select
week_2_NYJ = New_York_Jets_select[New_York_Jets_select['Semana'] == 2]
# Extraer la semana 1 de Kansas_City_select
week_2_KC = Kansas_City_select[Kansas_City_select['Semana'] == 2]
# Extraer la semana 1 de Buffalo_select
week_2_BUF = Buffalo_select[Buffalo_select['Semana'] == 2]
# Extraer la semana 1 de Indianapolis_select
week_2_IND = Indianapolis_select[Indianapolis_select['Semana'] == 2]
# Extraer la semana 1 de Los_Angeles_Rams_select
week_2_LAR = Los_Angeles_Rams_select[Los_Angeles_Rams_select['Semana'] == 2]
# Extraer la semana 1 de Tennessee_select
week_2_TEN = Tennessee_select[Tennessee_select['Semana'] == 2]
# Extraer la semana 1 de Seattle_select
week_2_SEA = Seattle_select[Seattle_select['Semana'] == 2]
# Extraer la semana 1 de Cleveland_select
week_2_CLE = Cleveland_select[Cleveland_select['Semana'] == 2]
# Extraer la semana 1 de New_York_Giants_select
week_2_NYG = New_York_Giants_select[New_York_Giants_select['Semana'] == 2]
# Extraer la semana 1 de Detroit_select
week_2_DET = Detroit_select[Detroit_select['Semana'] == 2]
# Extraer la semana 1 de New_England_select
week_2_NE = New_England_select[New_England_select['Semana'] == 2]
# Extraer la semana 1 de Minnesota_select
week_2_MIN = Minnesota_select[Minnesota_select['Semana'] == 2]
# Extraer la semana 1 de Los_Angeles_Chargers_select
week_2_LAC = Los_Angeles_Chargers_select[Los_Angeles_Chargers_select['Semana'] == 2]
# Extraer la semana 1 de Carolina_select
week_2_CAR = Carolina_select[Carolina_select['Semana'] == 2]
# Extraer la semana 1 de Houston_select
week_2_HOU = Houston_select[Houston_select['Semana'] == 2]
# Extraer la semana 1 de Cincinnati_select
week_2_CIN = Cincinnati_select[Cincinnati_select['Semana'] == 2]
# Extraer la semana 1 de Arizona_select
week_2_ARI = Arizona_select[Arizona_select['Semana'] == 2]
# Extraer la semana 1 de Chicago_select
week_2_CHI = Chicago_select[Chicago_select['Semana'] == 2]
# Extraer la semana 1 de Denver_select
week_2_DEN = Denver_select[Denver_select['Semana'] == 2]


# Crear un nuevo DataFrame que contenga solo la semana 1 de ambas tablas
week_2_df = pd.concat([week_2_DAL, week_2_MIA, week_2_SF, week_2_BAL, week_2_ATL, week_2_NO, week_2_TB, week_2_PHI, week_2_WSH, week_2_JAX,
                       week_2_GB, week_2_LV, week_2_PIT, week_2_NYJ, week_2_KC, week_2_BUF, week_2_IND, week_2_LAR, week_2_TEN, week_2_SEA,
                       week_2_CLE, week_2_NYG, week_2_DET, week_2_NE, week_2_MIN, week_2_LAC, week_2_CAR, week_2_HOU, week_2_CIN, week_2_ARI, 
                       week_2_CHI, week_2_DEN], ignore_index=True)

In [266]:
week_2_df

,Equipo,Semana,Fecha,Resultado_L,R1,R2,Local/Visitante,Equipo_Oponente,G,P,E,Diferencia_Pts.
0,Dallas,2,"Dom., 17 de Sep.",G,30,10,local,New York,1,0,0,20
1,Miami,2,"Dom., 17 de Sep.",G,24,17,visitante,New England,1,0,0,7
2,San Francisco,2,"Dom., 17 de Sep.",G,30,23,visitante,Los Angeles,1,0,0,7
3,Baltimore Ravens,2,"Dom., 17 de Sep.",G,27,24,visitante,Cincinnati,1,0,0,3
4,Atlanta,2,"Dom., 17 de Sep.",G,25,24,local,Green Bay,1,0,0,1
5,New Orleans,2,"Lun., 18 de Sep.",G,20,17,visitante,Carolina,1,0,0,3
6,Tampa Bay,2,"Dom., 17 de Sep.",G,27,17,local,Chicago,1,0,0,10
7,Philadelphia,2,"Jue., 14 de Sep.",G,34,28,local,Minnesota,1,0,0,6
8,Washington,2,"Dom., 17 de Sep.",G,35,33,visitante,Denver,1,0,0,2
9,Jacksonville,2,"Dom., 17 de Sep.",P,17,9,local,Kansas City,0,1,0,8
10,Green Bay,2,"Dom., 17 de Sep.",P,25,24,visitante,Atlanta,0,1,0,1
11,Las Vegas,2,"Dom., 17 de Sep.",P,38,10,visitante,Buffalo,0,1,0,28
12,Pittsburgh,2,"Lun., 18 de Sep.",G,26,22,local,Cleveland,1,0,0,4
13,New York Jets,2,"Dom., 17 de Sep.",P,30,10,visitante,Dallas,0,1,0,20
14,Kansas City,2,"Dom., 17 de Sep.",G,17,9,visitante,Jacksonville,1,0,0,8
15,Buffalo,2,"Dom., 17 de Sep.",G,38,10,local,Las Vegas,1,0,0,28
16,Indianapolis,2,"Dom., 17 de Sep.",G,31,20,visitante,Houston,1,0,0,11
17,Los Angeles Rams,2,"Dom., 17 de Sep.",P,30,23,local,San Francisco,0,1,0,7
18,Tennessee,2,"Dom., 17 de Sep.",G,27,24,local,Los Angeles,1,0,0,3
19,Seattle,2,"Dom., 17 de Sep.",G,37,31,visitante,Detroit,1,0,0,6
20,Cleveland,2,"Lun., 18 de Sep.",P,26,22,visitante,Pittsburgh,0,1,0,4
21,New York Giants,2,"Dom., 17 de Sep.",G,31,28,visitante,Arizona,1,0,0,3
22,Detroit,2,"Dom., 17 de Sep.",P,37,31,local,Seattle,0,1,0,6
23,New England,2,"Dom., 17 de Sep.",P,24,17,local,Miami,0,1,0,7
24,Minnesota,2,"Jue., 14 de Sep.",P,34,28,visitante,Philadelphia,0,1,0,6
25,Los Angeles Chargers,2,"Dom., 17 de Sep.",P,27,24,visitante,Tennessee,0,1,0,3
26,Carolina,2,"Lun., 18 de Sep.",P,20,17,local,New Orleans,0,1,0,3
27,Houston,2,"Dom., 17 de Sep.",P,31,20,local,Indianapolis,0,1,0,11
28,Cincinnati,2,"Dom., 17 de Sep.",P,27,24,local,Baltimore,0,1,0,3
29,Arizona,2,"Dom., 17 de Sep.",P,31,28,local,New York,0,1,0,3
30,Chicago,2,"Dom., 17 de Sep.",P,27,17,visitante,Tampa Bay,0,1,0,10
31,Denver,2,"Dom., 17 de Sep.",P,35,33,local,Washington,0,1,0,2

In [267]:
# Extraer la semana 3 de Dallas_select
week_3_DAL = Dallas_select[Dallas_select['Semana'] == 3]
# Extraer la semana 3 de Miami_select
week_3_MIA = Miami_select[Miami_select['Semana'] == 3]
# Extraer la semana 3 de San_Francisco_select
week_3_SF = San_Francisco_select[San_Francisco_select['Semana'] == 3]
# Extraer la semana 3 de Baltimore_Ravens_select
week_3_BAL = Baltimore_Ravens_select[Baltimore_Ravens_select['Semana'] == 3]
# Extraer la semana 3 de Atlanta_select
week_3_ATL = Atlanta_select[Atlanta_select['Semana'] == 3]
# Extraer la semana 3 de New_Orleans_select
week_3_NO = New_Orleans_select[New_Orleans_select['Semana'] == 3]
# Extraer la semana 3 de Tampa_Bay_select
week_3_TB = Tampa_Bay_select[Tampa_Bay_select['Semana'] == 3]
# Extraer la semana 3 de Philadelphia_select
week_3_PHI = Philadelphia_select[Philadelphia_select['Semana'] == 3]
# Extraer la semana 3 de Washington_select
week_3_WSH = Washington_select[Washington_select['Semana'] == 3]
# Extraer la semana 3 de Jacksonville_select
week_3_JAX = Jacksonville_select[Jacksonville_select['Semana'] == 3]
# Extraer la semana 3 de Green_Bay_select
week_3_GB = Green_Bay_select[Green_Bay_select['Semana'] == 3]
# Extraer la semana 3 de Las_Vegas_Raiders_select
week_3_LV = Las_Vegas_select[Las_Vegas_select['Semana'] == 3]
# Extraer la semana 3 de Pittsburgh_select
week_3_PIT = Pittsburgh_select[Pittsburgh_select['Semana'] == 3]
# Extraer la semana 3 de New_York_Jets_select
week_3_NYJ = New_York_Jets_select[New_York_Jets_select['Semana'] == 3]
# Extraer la semana 3 de Kansas_City_select
week_3_KC = Kansas_City_select[Kansas_City_select['Semana'] == 3]
# Extraer la semana 3 de Buffalo_select
week_3_BUF = Buffalo_select[Buffalo_select['Semana'] == 3]
# Extraer la semana 3 de Indianapolis_select
week_3_IND = Indianapolis_select[Indianapolis_select['Semana'] == 3]
# Extraer la semana 3 de Los_Angeles_Rams_select
week_3_LAR = Los_Angeles_Rams_select[Los_Angeles_Rams_select['Semana'] == 3]
# Extraer la semana 3 de Tennessee_select
week_3_TEN = Tennessee_select[Tennessee_select['Semana'] == 3]
# Extraer la semana 3 de Seattle_select
week_3_SEA = Seattle_select[Seattle_select['Semana'] == 3]
# Extraer la semana 3 de Cleveland_select
week_3_CLE = Cleveland_select[Cleveland_select['Semana'] == 3]
# Extraer la semana 3 de New_York_Giants_select
week_3_NYG = New_York_Giants_select[New_York_Giants_select['Semana'] == 3]
# Extraer la semana 3 de Detroit_select
week_3_DET = Detroit_select[Detroit_select['Semana'] == 3]
# Extraer la semana 3 de New_England_select
week_3_NE = New_England_select[New_England_select['Semana'] == 3]
# Extraer la semana 3 de Minnesota_select
week_3_MIN = Minnesota_select[Minnesota_select['Semana'] == 3]
# Extraer la semana 3 de Los_Angeles_Chargers_select
week_3_LAC = Los_Angeles_Chargers_select[Los_Angeles_Chargers_select['Semana'] == 3]
# Extraer la semana 3 de Carolina_select
week_3_CAR = Carolina_select[Carolina_select['Semana'] == 3]
# Extraer la semana 3 de Houston_select
week_3_HOU = Houston_select[Houston_select['Semana'] == 3]
# Extraer la semana 3 de Cincinnati_select
week_3_CIN = Cincinnati_select[Cincinnati_select['Semana'] == 3]
# Extraer la semana 3 de Arizona_select
week_3_ARI = Arizona_select[Arizona_select['Semana'] == 3]
# Extraer la semana 3 de Chicago_select
week_3_CHI = Chicago_select[Chicago_select['Semana'] == 3]
# Extraer la semana 3 de Denver_select
week_3_DEN = Denver_select[Denver_select['Semana'] == 3]


# Crear un nuevo DataFrame que contenga solo la semana 3 de ambas tablas
week_3_df = pd.concat([week_3_DAL, week_3_MIA, week_3_SF, week_3_BAL, week_3_ATL, week_3_NO, week_3_TB, week_3_PHI, week_3_WSH, week_3_JAX,
                       week_3_GB, week_3_LV, week_3_PIT, week_3_NYJ, week_3_KC, week_3_BUF, week_3_IND, week_3_LAR, week_3_TEN, week_3_SEA,
                       week_3_CLE, week_3_NYG, week_3_DET, week_3_NE, week_3_MIN, week_3_LAC, week_3_CAR, week_3_HOU, week_3_CIN, week_3_ARI, 
                       week_3_CHI, week_3_DEN], ignore_index=True)

In [268]:
week_3_df

,Equipo,Semana,Fecha,Resultado_L,R1,R2,Local/Visitante,Equipo_Oponente,G,P,E,Diferencia_Pts.
0,Dallas,3,"Dom., 24 de Sep.",P,28,16,visitante,Arizona,0,1,0,12
1,Miami,3,"Dom., 24 de Sep.",G,70,20,local,Denver,1,0,0,50
2,San Francisco,3,"Jue., 21 de Sep.",G,30,12,local,New York,1,0,0,18
3,Baltimore Ravens,3,"Dom., 24 de Sep.",P,22,19,local,Indianapolis,0,1,0,3
4,Atlanta,3,"Dom., 24 de Sep.",P,20,6,visitante,Detroit,0,1,0,14
5,New Orleans,3,"Dom., 24 de Sep.",P,18,17,visitante,Green Bay,0,1,0,1
6,Tampa Bay,3,"Lun., 25 de Sep.",P,25,11,local,Philadelphia,0,1,0,14
7,Philadelphia,3,"Lun., 25 de Sep.",G,25,11,visitante,Tampa Bay,1,0,0,14
8,Washington,3,"Dom., 24 de Sep.",P,37,3,local,Buffalo,0,1,0,34
9,Jacksonville,3,"Dom., 24 de Sep.",P,37,17,local,Houston,0,1,0,20
10,Green Bay,3,"Dom., 24 de Sep.",G,18,17,local,New Orleans,1,0,0,1
11,Las Vegas,3,"Dom., 24 de Sep.",P,23,18,local,Pittsburgh,0,1,0,5
12,Pittsburgh,3,"Dom., 24 de Sep.",G,23,18,visitante,Las Vegas,1,0,0,5
13,New York Jets,3,"Dom., 24 de Sep.",P,15,10,local,New England,0,1,0,5
14,Kansas City,3,"Dom., 24 de Sep.",G,41,10,local,Chicago,1,0,0,31
15,Buffalo,3,"Dom., 24 de Sep.",G,37,3,visitante,Washington,1,0,0,34
16,Indianapolis,3,"Dom., 24 de Sep.",G,22,19,visitante,Baltimore,1,0,0,3
17,Los Angeles Rams,3,"Lun., 25 de Sep.",P,19,16,visitante,Cincinnati,0,1,0,3
18,Tennessee,3,"Dom., 24 de Sep.",P,27,3,visitante,Cleveland,0,1,0,24
19,Seattle,3,"Dom., 24 de Sep.",G,37,27,local,Carolina,1,0,0,10
20,Cleveland,3,"Dom., 24 de Sep.",G,27,3,local,Tennessee,1,0,0,24
21,New York Giants,3,"Jue., 21 de Sep.",P,30,12,visitante,San Francisco,0,1,0,18
22,Detroit,3,"Dom., 24 de Sep.",G,20,6,local,Atlanta,1,0,0,14
23,New England,3,"Dom., 24 de Sep.",G,15,10,visitante,New York,1,0,0,5
24,Minnesota,3,"Dom., 24 de Sep.",P,28,24,local,Los Angeles,0,1,0,4
25,Los Angeles Chargers,3,"Dom., 24 de Sep.",G,28,24,visitante,Minnesota,1,0,0,4
26,Carolina,3,"Dom., 24 de Sep.",P,37,27,visitante,Seattle,0,1,0,10
27,Houston,3,"Dom., 24 de Sep.",G,37,17,visitante,Jacksonville,1,0,0,20
28,Cincinnati,3,"Lun., 25 de Sep.",G,19,16,local,Los Angeles,1,0,0,3
29,Arizona,3,"Dom., 24 de Sep.",G,28,16,local,Dallas,1,0,0,12
30,Chicago,3,"Dom., 24 de Sep.",P,41,10,visitante,Kansas City,0,1,0,31
31,Denver,3,"Dom., 24 de Sep.",P,70,20,visitante,Miami,0,1,0,50

In [269]:
# Extraer la semana 4 de Dallas_select
week_4_DAL = Dallas_select[Dallas_select['Semana'] == 4]
# Extraer la semana 4 de Miami_select
week_4_MIA = Miami_select[Miami_select['Semana'] == 4]
# Extraer la semana 4 de San_Francisco_select
week_4_SF = San_Francisco_select[San_Francisco_select['Semana'] == 4]
# Extraer la semana 4 de Baltimore_Ravens_select
week_4_BAL = Baltimore_Ravens_select[Baltimore_Ravens_select['Semana'] == 4]
# Extraer la semana 4 de Atlanta_select
week_4_ATL = Atlanta_select[Atlanta_select['Semana'] == 4]
# Extraer la semana 4 de New_Orleans_select
week_4_NO = New_Orleans_select[New_Orleans_select['Semana'] == 4]
# Extraer la semana 4 de Tampa_Bay_select
week_4_TB = Tampa_Bay_select[Tampa_Bay_select['Semana'] == 4]
# Extraer la semana 4 de Philadelphia_select
week_4_PHI = Philadelphia_select[Philadelphia_select['Semana'] == 4]
# Extraer la semana 4 de Washington_select
week_4_WSH = Washington_select[Washington_select['Semana'] == 4]
# Extraer la semana 4 de Jacksonville_select
week_4_JAX = Jacksonville_select[Jacksonville_select['Semana'] == 4]
# Extraer la semana 4 de Green_Bay_select
week_4_GB = Green_Bay_select[Green_Bay_select['Semana'] == 4]
# Extraer la semana 4 de Las_Vegas_Raiders_select
week_4_LV = Las_Vegas_select[Las_Vegas_select['Semana'] == 4]
# Extraer la semana 4 de Pittsburgh_select
week_4_PIT = Pittsburgh_select[Pittsburgh_select['Semana'] == 4]
# Extraer la semana 4 de New_York_Jets_select
week_4_NYJ = New_York_Jets_select[New_York_Jets_select['Semana'] == 4]
# Extraer la semana 4 de Kansas_City_select
week_4_KC = Kansas_City_select[Kansas_City_select['Semana'] == 4]
# Extraer la semana 4 de Buffalo_select
week_4_BUF = Buffalo_select[Buffalo_select['Semana'] == 4]
# Extraer la semana 4 de Indianapolis_select
week_4_IND = Indianapolis_select[Indianapolis_select['Semana'] == 4]
# Extraer la semana 4 de Los_Angeles_Rams_select
week_4_LAR = Los_Angeles_Rams_select[Los_Angeles_Rams_select['Semana'] == 4]
# Extraer la semana 4 de Tennessee_select
week_4_TEN = Tennessee_select[Tennessee_select['Semana'] == 4]
# Extraer la semana 4 de Seattle_select
week_4_SEA = Seattle_select[Seattle_select['Semana'] == 4]
# Extraer la semana 4 de Cleveland_select
week_4_CLE = Cleveland_select[Cleveland_select['Semana'] == 4]
# Extraer la semana 4 de New_York_Giants_select
week_4_NYG = New_York_Giants_select[New_York_Giants_select['Semana'] == 4]
# Extraer la semana 4 de Detroit_select
week_4_DET = Detroit_select[Detroit_select['Semana'] == 4]
# Extraer la semana 4 de New_England_select
week_4_NE = New_England_select[New_England_select['Semana'] == 4]
# Extraer la semana 4 de Minnesota_select
week_4_MIN = Minnesota_select[Minnesota_select['Semana'] == 4]
# Extraer la semana 4 de Los_Angeles_Chargers_select
week_4_LAC = Los_Angeles_Chargers_select[Los_Angeles_Chargers_select['Semana'] == 4]
# Extraer la semana 4 de Carolina_select
week_4_CAR = Carolina_select[Carolina_select['Semana'] == 4]
# Extraer la semana 4 de Houston_select
week_4_HOU = Houston_select[Houston_select['Semana'] == 4]
# Extraer la semana 4 de Cincinnati_select
week_4_CIN = Cincinnati_select[Cincinnati_select['Semana'] == 4]
# Extraer la semana 4 de Arizona_select
week_4_ARI = Arizona_select[Arizona_select['Semana'] == 4]
# Extraer la semana 4 de Chicago_select
week_4_CHI = Chicago_select[Chicago_select['Semana'] == 4]
# Extraer la semana 4 de Denver_select
week_4_DEN = Denver_select[Denver_select['Semana'] == 4]


# Crear un nuevo DataFrame que contenga solo la semana 4 de ambas tablas
week_4_df = pd.concat([week_4_DAL, week_4_MIA, week_4_SF, week_4_BAL, week_4_ATL, week_4_NO, week_4_TB, week_4_PHI, week_4_WSH, week_4_JAX,
                       week_4_GB, week_4_LV, week_4_PIT, week_4_NYJ, week_4_KC, week_4_BUF, week_4_IND, week_4_LAR, week_4_TEN, week_4_SEA,
                       week_4_CLE, week_4_NYG, week_4_DET, week_4_NE, week_4_MIN, week_4_LAC, week_4_CAR, week_4_HOU, week_4_CIN, week_4_ARI, 
                       week_4_CHI, week_4_DEN], ignore_index=True)

In [270]:
week_4_df

,Equipo,Semana,Fecha,Resultado_L,R1,R2,Local/Visitante,Equipo_Oponente,G,P,E,Diferencia_Pts.
0,Dallas,4,"Dom., 1 de Oct.",G,38,3,local,New England,1,0,0,35
1,Miami,4,"Dom., 1 de Oct.",P,48,20,visitante,Buffalo,0,1,0,28
2,San Francisco,4,"Dom., 1 de Oct.",G,35,16,local,Arizona,1,0,0,19
3,Baltimore Ravens,4,"Dom., 1 de Oct.",G,28,3,visitante,Cleveland,1,0,0,25
4,Atlanta,4,"Dom., 1 de Oct.",P,23,7,local,Jacksonville *,0,1,0,16
5,New Orleans,4,"Dom., 1 de Oct.",P,26,9,local,Tampa Bay,0,1,0,17
6,Tampa Bay,4,"Dom., 1 de Oct.",G,26,9,visitante,New Orleans,1,0,0,17
7,Philadelphia,4,"Dom., 1 de Oct.",G,34,31,local,Washington,1,0,0,3
8,Washington,4,"Dom., 1 de Oct.",P,34,31,visitante,Philadelphia,0,1,0,3
9,Jacksonville,4,"Dom., 1 de Oct.",G,23,7,local,Atlanta *,1,0,0,16
10,Green Bay,4,"Jue., 28 de Sep.",P,34,20,local,Detroit,0,1,0,14
11,Las Vegas,4,"Dom., 1 de Oct.",P,24,17,visitante,Los Angeles,0,1,0,7
12,Pittsburgh,4,"Dom., 1 de Oct.",P,30,6,visitante,Houston,0,1,0,24
13,New York Jets,4,"Dom., 1 de Oct.",P,23,20,local,Kansas City,0,1,0,3
14,Kansas City,4,"Dom., 1 de Oct.",G,23,20,visitante,New York,1,0,0,3
15,Buffalo,4,"Dom., 1 de Oct.",G,48,20,local,Miami,1,0,0,28
16,Indianapolis,4,"Dom., 1 de Oct.",P,29,23,local,Los Angeles,0,1,0,6
17,Los Angeles Rams,4,"Dom., 1 de Oct.",G,29,23,visitante,Indianapolis,1,0,0,6
18,Tennessee,4,"Dom., 1 de Oct.",G,27,3,local,Cincinnati,1,0,0,24
19,Seattle,4,"Lun., 2 de Oct.",G,24,3,visitante,New York,1,0,0,21
20,Cleveland,4,"Dom., 1 de Oct.",P,28,3,local,Baltimore,0,1,0,25
21,New York Giants,4,"Lun., 2 de Oct.",P,24,3,local,Seattle,0,1,0,21
22,Detroit,4,"Jue., 28 de Sep.",G,34,20,visitante,Green Bay,1,0,0,14
23,New England,4,"Dom., 1 de Oct.",P,38,3,visitante,Dallas,0,1,0,35
24,Minnesota,4,"Dom., 1 de Oct.",G,21,13,visitante,Carolina,1,0,0,8
25,Los Angeles Chargers,4,"Dom., 1 de Oct.",G,24,17,local,Las Vegas,1,0,0,7
26,Carolina,4,"Dom., 1 de Oct.",P,21,13,local,Minnesota,0,1,0,8
27,Houston,4,"Dom., 1 de Oct.",G,30,6,local,Pittsburgh,1,0,0,24
28,Cincinnati,4,"Dom., 1 de Oct.",P,27,3,visitante,Tennessee,0,1,0,24
29,Arizona,4,"Dom., 1 de Oct.",P,35,16,visitante,San Francisco,0,1,0,19
30,Chicago,4,"Dom., 1 de Oct.",P,31,28,local,Denver,0,1,0,3
31,Denver,4,"Dom., 1 de Oct.",G,31,28,visitante,Chicago,1,0,0,3

In [271]:
Unir_Semanas_df = pd.concat([week_1_df, week_2_df, week_3_df, week_4_df], ignore_index=True)

In [272]:
Unir_Semanas_df

,Equipo,Semana,Fecha,Resultado_L,R1,R2,Local/Visitante,Equipo_Oponente,G,P,E,Diferencia_Pts.
0,Dallas,1,"Dom., 10 de Sep.",G,40,0,visitante,New York,1,0,0,40
1,Miami,1,"Dom., 10 de Sep.",G,36,34,visitante,Los Angeles,1,0,0,2
2,San Francisco,1,"Dom., 10 de Sep.",G,30,7,visitante,Pittsburgh,1,0,0,23
3,Baltimore Ravens,1,"Dom., 10 de Sep.",G,25,9,local,Houston,1,0,0,16
4,Atlanta,1,"Dom., 10 de Sep.",G,24,10,local,Carolina,1,0,0,14
...,...,...,...,...,...,...,...,...,...,...,...,...
123,Houston,4,"Dom., 1 de Oct.",G,30,6,local,Pittsburgh,1,0,0,24
124,Cincinnati,4,"Dom., 1 de Oct.",P,27,3,visitante,Tennessee,0,1,0,24
125,Arizona,4,"Dom., 1 de Oct.",P,35,16,visitante,San Francisco,0,1,0,19
126,Chicago,4,"Dom., 1 de Oct.",P,31,28,local,Denver,0,1,0,3
127,Denver,4,"Dom., 1 de Oct.",G,31,28,visitante,Chicago,1,0,0,3

In [273]:
tipos_de_datos = Unir_Semanas_df.dtypes

In [274]:
tipos_de_datos

Equipo             object
Semana             object
Fecha              object
Resultado_L        object
R1                 object
R2                 object
Local/Visitante    object
Equipo_Oponente    object
G                   int32
P                   int32
E                   int32
Diferencia_Pts.    object
dtype: object

In [275]:
Unir_Semanas_df.to_excel('Export\\SemUnidas2.xlsx')

In [276]:
tipos_de_datos

Equipo             object
Semana             object
Fecha              object
Resultado_L        object
R1                 object
R2                 object
Local/Visitante    object
Equipo_Oponente    object
G                   int32
P                   int32
E                   int32
Diferencia_Pts.    object
dtype: object

In [277]:
Unir_Semanas_df

,Equipo,Semana,Fecha,Resultado_L,R1,R2,Local/Visitante,Equipo_Oponente,G,P,E,Diferencia_Pts.
0,Dallas,1,"Dom., 10 de Sep.",G,40,0,visitante,New York,1,0,0,40
1,Miami,1,"Dom., 10 de Sep.",G,36,34,visitante,Los Angeles,1,0,0,2
2,San Francisco,1,"Dom., 10 de Sep.",G,30,7,visitante,Pittsburgh,1,0,0,23
3,Baltimore Ravens,1,"Dom., 10 de Sep.",G,25,9,local,Houston,1,0,0,16
4,Atlanta,1,"Dom., 10 de Sep.",G,24,10,local,Carolina,1,0,0,14
...,...,...,...,...,...,...,...,...,...,...,...,...
123,Houston,4,"Dom., 1 de Oct.",G,30,6,local,Pittsburgh,1,0,0,24
124,Cincinnati,4,"Dom., 1 de Oct.",P,27,3,visitante,Tennessee,0,1,0,24
125,Arizona,4,"Dom., 1 de Oct.",P,35,16,visitante,San Francisco,0,1,0,19
126,Chicago,4,"Dom., 1 de Oct.",P,31,28,local,Denver,0,1,0,3
127,Denver,4,"Dom., 1 de Oct.",G,31,28,visitante,Chicago,1,0,0,3

In [278]:
conexion1 = psycopg2.connect(database="NFL", user="postgres", password="linux")

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 85: invalid continuation byte

In [ ]:
cursor1=conexion1.cursor()

In [ ]:
#semana_a_consultar = 5

In [ ]:
cursor1.execute("SELECT max(semana) from calendario")

In [ ]:
#cursor1.execute("SELECT * FROM calendario WHERE Semana = %s", (semana_a_consultar,))

In [ ]:
resultados = cursor1.fetchall()

In [ ]:
semana_siguiente = resultados[0][0]+1

In [ ]:
try:
    conexion1 = psycopg2.connect(database="NFL", user="postgres", password="linux")
    cursor1 = conexion1.cursor()

    # Comenzar una transacción
    conexion1.autocommit = False

    for index, row in Unir_Semanas_df.iterrows():
        # Realizar inserción
        cursor1.execute("INSERT INTO calendario (Equipo, Semana, Fecha, Resultado_L, R1, R2, Local_Visitante, Equipo_Oponente, G, P, E, Diferencia_Pts) "
                        "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)",
                        (row['Equipo'], int(row['Semana']), row['Fecha'], row['Resultado_L'], int(row['R1']), int(row['R2']),
                         row['Local/Visitante'], row['Equipo_Oponente'], int(row['G']), int(row['P']), int(row['E']), int(row['Diferencia_Pts.'])))

    # Confirmar la transacción
    conexion1.commit()

except Exception as e:
    # Revertir la transacción en caso de error
    conexion1.rollback()
    print("Error:", str(e))

finally:
    # Restaurar el modo de autocommit
    conexion1.autocommit = True
    cursor1.close()
    conexion1.close()